app/locale/es-ES.coffee
Hi everyone!
It's my first pull request. So I hope everything is OK.
Let me know if I need to change the parent repository branch. I have read this http://nvie.com/posts/a-successful-git-branching-model/, but I'm not sure how to proceed.
By now I will only make translations, but my intention is also to collaborate with code. So any hint on how to make correct pull request is welcome.
=> Added one translation to Spanish (es-ES). Testing github pull request.

app/locale/es-ES.coffee
New string translations for es-ES
=> Added es-ES translations

app/locale/ca.coffee
Added some translations and fixed spelling errors.
=> Added some translations

app/templates/play/level/level_loading.jade
Added the following tips:
1) play_level.tip_control_destiny
2) play_level.tip_no_code
3) play_level.tip_code_never_lies
4) play_level.tip_reusable_software
5) play_level.tip_optimization_operator
6) play_level.tip_lines_of_code
=> Added 6 new tips for the loading screen

app/locale/de-DE.coffee
new subscibe text added, was confusing to read codecombat does not want to make subsciptions in /legal
=> Propagated i18n.

README.md
Added links to the top image, the "getting in touch" section and the "getting started" section.
=> Added links to "README.MD"

app/styles/common/site-chrome.sass
Long player names overflow poorly on user dropdown
=> #2125 Long player names overflow

app/views/play/level/tome/SpellView.coffee, app/views/play/level/tome/TomeView.coffee
Fixed the issue for incorrect comments by correcting the syntax per language
=> Fixed Comment Out My Code for infinite loops for #1788

app/styles/common/site-chrome.sass, app/templates/base.jade
Fixed this issue, taken the advice:
`Could turn it into a background image with background-size: cover. That would center it along the largest dimension.`
=> Fix profile picture bug for #2157

app/templates/play/level/level_loading.jade
=> Added Tips

app/locale/nb.coffee
Kept all the old strings for future reference.
=> Translated share_progress_modal

app/styles/play/modal/leaderboard-modal.sass, app/styles/play/modal/leaderboard-tab-view.sass
The leaderboard view fits properly while scrolling down.
=> Fixed the issue with the Leaderboard view to fit properly for #2254

app/lib/world/names.coffee
I have added more names to Names.coffee
=> Added more names for #53

app/locale/sk.coffee
Completed translations of home, nav, diplomat_suggestion, play, common, general, almost whole play_level, buy_gems, skill_docs, versions
=> Around hundred new lines of Slovak translation

app/locale/en.coffee, app/models/User.coffee, app/templates/account/account-settings-view.jade, app/templates/play/campaign-view.jade, app/views/account/AccountSettingsView.coffee, app/views/play/CampaignView.coffee, server/users/User.coffee
I have added a checkbox that can be used to turn on the "god mode". (#2164)
If you turn on the "god mode" then: 
+ You will become a premium user 
+ You can play all the levels (including preminum levels)
+ You will receive 100000 gems  (but if you turn off the "god mode" then you lose those gems)
+ You will receive 1000000 xp points (if you turn off the "god mode" then you lose those xp points)
+ All the heroes are unlocked
=> Added a "god mode" button to the local dev environment  (issue #2164)

app/styles/modal/subscribe-modal.sass
Also reduced the size for tbody data to fit properly
=> Font size tweak for #2324

app/lib/world/names.coffee
Added 'Itachi', 'Madara' and 'Obito' to the set of ninja names.
=> Added more ninja names for #53

server/routes/db.coffee, server/users/User.coffee
Added getUserInfo function in User.coffee to which  returns information of current user.
=> Added user info to db error

app/locale/he.coffee
some of the translations were changed to a clearer/better form
=> Fixed errors and added more translations to he.coffee

app/views/play/menu/InventoryModal.coffee
=> Fix issue #1832 (Equipping with little equip button doesn't update big equip button)

app/views/play/menu/GuideView.coffee
Onhidden function was resetting volume to 1.0 in case volume is not defined. In case volume is not defined, means that onShown has not been called and hence volume should be same as  current volume.
=> Volume bug fix #2202

README.md
=> Fixed discourse link

app/views/editor/level/thangs/ThangsTabView.coffee
Check for number of remaining elements in currently deleted Thang's Name , if its zero then delete. Similarly check for Thang's Kind.
=> Issue #1785: Empty level editor folders removed

app/views/editor/level/components/ComponentsTabView.coffee
Solves problem of duplicate entries in level editor component view
=> Issue #2267: Removed duplicates from TreemaData

app/styles/play/ladder/ladder.sass, app/views/editor/campaign/CampaignEditorView.coffee
Reduced the max-width component to fit ellipsis properly.
=> Fix for long names in leader board for #2373

app/views/account/AccountSettingsView.coffee
Added input-changed trigger to toggle all.
=> Issue #2387: Accounts setting toggle all fix

app/templates/account/main-account-view.jade
=> Add Profile to account page (Issue #2388)

app/locale/en.coffee, app/templates/user/main-user-view.jade
=> Add "navigation bar" to user profile page (issue 2411)

CONTRIBUTING.md, headless_client.coffee
Now it includes the different ways to contribute
=> Edited Contributing

app/lib/world/names.coffee
I added 32 names in multiple "Thang" categories
=> Added multiple names

app/styles/play/modal/leaderboard-modal.sass
This fixed issue #2430. The tabs now look ok in Russian
=> Fixed issue #2430

app/lib/world/names.coffee
Added a few Thang names to wet my feet a bit
=> Adding a few names

scripts/copy-i18n-tags.coffee
Fixing the https://github.com/codecombat/codecombat/pull/2453#issuecomment-76815397
=> Adds escaping in {change} find

app/schemas/models/campaign.schema.coffee, app/schemas/models/level.coffee, app/views/play/level/tome/SpellView.coffee
=> Only lock spacebar and default code when the player is lower level (issue 2406)

app/locale/en.coffee, app/styles/modal/subscribe-modal.sass, app/styles/play/campaign-view.sass, app/templates/play/campaign-view.jade
As Nick says, we need to communicate that 1) the weapons are wands and staffs, 2) the hero can use magic, and 3) the hero has long-ranged attacks. Let me know what do you think @differentmatt.
=> A small fix for confusing Hero Modal weaopons list for #1774

app/styles/play/modal/play-heroes-modal.sass, app/styles/play/modal/play-items-modal.sass
This fixed issues #2497 and #2501. 
/play - items
/play - heroes
=> Fixed issues #2497 and #2501 (Text-fit bugs)

app/styles/play/modal/play-heroes-modal.sass
Quick fix for unlock/confirm buttons
For Issue #2501 and Issue https://github.com/codecombat/codecombat/issues/1918
=> Fix Issue #2501

app/locale/ru.coffee
=> Update ru.coffee. Fix accretion.

app/styles/play/modal/play-items-modal.sass
Just to check if this kind of cleanup doesn't mess with anything.
=> Some cleanup to play-items-modal.sass file

app/templates/account/main-account-view.jade
As said at https://github.com/codecombat/codecombat/pull/2527#issuecomment-82609513
=> Removing invoices from /account

app/templates/i18n/i18n-home-view.jade, app/views/i18n/I18NHomeView.coffee
Now you can find thang by its translated name, yay!
Looks like this:
=> Add "Translated Name" to /i18n

app/locale/eo.coffee
Diplomat, nav, modal, not_found blocks and slogan!
=> First eo lines

app/locale/en.coffee
For proper propagination after https://github.com/codecombat/codecombat/commit/fb8e184819c51f1eb2aaacda3984ba147c16d558
=> Update en.coffee. Add {change}

app/locale/es-ES.coffee
=> Fix Issue #2550

scripts/windows/SCOCODE.bat, scripts/windows/coco-dev-setup/batch/config/config.coco, scripts/windows/coco-dev-setup/batch/scripts/nab_automatic_script.bat
Recent update of aether forced me to run npm update & bower update (thanks Nick for tip).
So Nick and me decided to add this command to scocode and coco-dev-setup.
I think, we also need to add some comments to linux setup here https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Linux
=> Add npm&bower update to SCOCODE.bat. Update ver #

app/views/editor/ForkModal.coffee
If i got it right, this should fix this issue https://github.com/codecombat/codecombat/issues/2500
=> Clean i18n when forking an object

app/locale/fr.coffee
Old translation was "Encaisse" which means takes damages instead of takes time.
=> Correct action_cooldown translation (french translation).

app/views/play/level/tome/SpellView.coffee
Insertion is now language specific.
=> Update the shift-click insertion

app/locale/hu.coffee
'range' translation was too wide also
=> range translation too wide

bin/coco-mongodb, headless_client.coffee, scripts/devSetup/mongo.py, scripts/windows/install-mongodb.ps1
Watch out when merging this, I've tested this on Linux Ubuntu 14.04, but no other versions.  Should be tested before accepting pull request.
=> Update Mongo Version

app/lib/world/names.coffee
Female = Anabel, Paulark
Male = Eugen, Toremon
=> New female and male names added!

app/locale/de-DE.coffee
line 4: According to [1], "Leid tun" was actually an accepted spelling between 1996 and 2006.
line 839: Imperative form [2]
[1] http://www.korrekturen.de/wortliste/leidtun.shtml
[2] http://www.duden.de/rechtschreibung/beitreten
=> Fix typos in de-DE.coffee

app/locale/zh-HANS.coffee
1.Modify some wording error
2.Translated some items
=> improved Chinese localization

app/lib/world/names.coffee
This time in alphabetical order and without comma's
=> "Added more names for #53"

app/locale/zh-HANS.coffee
Since I don't how the payment for the server in China work， I don't want to mess up the teacher section.
=> few more translation

app/views/contribute/DiplomatView.coffee
Just red on the diplomat forum to do this..
=> Added my username in Italian translators

app/locale/uk.coffee
Правильніше "У бій!" за правилами вживання прийменників у/в.
=> 'viking' translation, 'fight' mistake fix

app/views/editor/level/modals/GenerateTerrainModal.coffee
As stated, added basic Ice Sheet surrounded by Ice Walls to the generator.
=> Added Ice Level to terrain generator

app/locale/uk.coffee
one message for parents and "invite to clan by link"
=> translate few strings

app/locale/en.coffee, app/views/play/level/tome/SpellView.coffee
Super simples PR. But I was playing the game in pt_BR, and would be nice to have this translated.
=> i18N press enter on spell view

app/templates/home-view.jade
=> Fixes #2854

app/templates/teachers-free-trial.jade, app/views/TeachersFreeTrialView.coffee
=> Fixes #2806 (radio buttons of teacher survey page)

app/views/play/menu/InventoryModal.coffee
Rings often have unique effects instead of progressively enhancing another ring's effect, hence let's make rings required even if there's already non-restricted rings equipped.
If, by any chance, there's ever a new ring which enhances the effect of a ring which is required for some level, then it should be easy enough to whitelist it in the given ring slot's allowed items array.
=> updateLevelRequiredItems: special-case rings, fixes #2740

app/templates/core/auth.jade, app/views/core/AuthModal.coffee
Closes https://github.com/codecombat/codecombat/issues/914
=> Fixed email requirement

app/views/core/SubscribeModal.coffee
For the issue https://github.com/codecombat/codecombat/issues/2694
=> Add close button to payment methods

app/locale/ko.coffee
I translated some words.
If you accept my request, I'll do more.
=> Translated some words.

app/lib/world/names.coffee
Just adding a few names to the list, as an early commit.
=> Added a few more names for issue #53

.travis.yml
Tests are now failing, but at least they should work.
Not sure if this entirely fixes #2776 though.
=> Disable coverage reporter in Travis CI

app/locale/en-US.coffee, app/locale/en.coffee, app/templates/play/level/level_loading.jade
Just adding a loading screen tip, as another small initial commit.
=> Add a tip for the loading screen #710

app/styles/clans/clan-details.sass, app/templates/clans/clan-details.jade, server/clans/clan_handler.coffee
[Before](https://cloud.githubusercontent.com/assets/6857146/8895571/d92a3e42-3393-11e5-964d-4a2885db7c8b.png)
After:
Things:
- I think the premium dashboard should remain unchanged
- Arryn and Nalfar have no hero icons, so it looks a little bit weird
=> Fix clan details style

app/locale/ko.coffee
Translated some words and sentences
=> Translated some words and sentences

app/locale/es-419.coffee
Translated the new strings added to the file.
=> Add translations up teacher's section

app/locale/zh-HANS.coffee
the word 吧is misused, should use 把 instead
=> there has a typos at #963

app/views/play/modal/BuyGemsModal.coffee, app/views/play/modal/PlayAchievementsModal.coffee, app/views/play/modal/PlayItemsModal.coffee
#2915 
#2916 — This however does not add sounds to AuthModal when opening/hiding.
=> Fix some campaign interface audio

app/locale/zh-HANT.coffee
=> just translate few sentences

app/locale/zh-HANS.coffee
fixed some wordings and sentences
=> fixed few things

app/locale/zh-HANS.coffee
Reverts codecombat/codecombat#2950
=> Revert "there has a typos at #963"

app/locale/pt-BR.coffee
=> First changes to pt-BR translation

README.md
- Mac dev URL was bad
- added Vagrant URL
=> fixed wiki URLs

app/locale/pt-BR.coffee
Translate some strings and correted the translation of some other ones
=> Translate and correct

app/views/ladder/MyMatchesTabView.coffee, app/views/play/level/LevelChatView.coffee, app/views/play/level/LevelGoalsView.coffee, app/views/play/level/LevelLoadingView.coffee, app/views/play/level/LevelPlaybackView.coffee, app/views/play/level/modal/HeroVictoryModal.coffee, app/views/play/level/modal/VictoryModal.coffee, app/views/play/level/tome/ProblemAlertView.coffee, app/views/play/level/tome/SpellListTabEntryView.coffee, app/views/play/level/tome/SpellPaletteEntryView.coffee, app/views/play/modal/PollModal.coffee
I'm not sure about 'SpellListTabEntryView.coffee', because it doesn't extend CocoView, and the ones that extend ModalView.
=> Use playSound across the code

app/styles/kinds/search.sass, app/templates/common/table.jade, app/templates/editor/thang/table.jade
I'm a total Sass/Jade noob and I wasn't able to test my changes. If anything looks funny, please let me know.
=> Fixed level/thang editor table for issue #3052

app/lib/world/names.coffee
=> Added a few names.

app/locale/zh-HANS.coffee
=> Update harry's tips

app/locale/zh-HANS.coffee
Modify some description,and add the new translations.
=> Update to zh-HANS.coffee

app/templates/account/job-profile-code-modal.jade, app/templates/careers.jade, app/templates/editor/campaign/save-campaign-modal.jade, app/templates/play/level/modal/infinite_loop.jade, app/templates/play/level/tome/spell_list_entry_thangs.jade, app/views/CareersView.coffee, app/views/editor/campaign/SaveCampaignModal.coffee, app/views/play/level/modal/InfiniteLoopModal.coffee, app/views/play/level/tome/SpellListEntryThangsView.coffee, app/views/play/menu/SaveLoadView.coffee, app/views/play/modal/PlaySettingsModal.coffee, app/views/user/JobProfileCodeModal.coffee
=> Refactor to use view in template for issue #3138

app/templates/admin.jade, app/templates/core/subscribe-modal.jade, app/templates/editor/achievement/edit.jade, app/templates/editor/level/thang/level-thang-edit-view.jade, app/templates/editor/poll/poll-edit-view.jade, app/templates/editor/thang/vector-icon-setup-modal.jade, app/templates/modal/model-modal.jade, app/templates/play/modal/play-achievements-modal.jade, app/views/admin/MainAdminView.coffee, app/views/core/SubscribeModal.coffee, app/views/editor/achievement/AchievementEditView.coffee, app/views/editor/level/thangs/LevelThangEditView.coffee, app/views/editor/poll/PollEditView.coffee, app/views/editor/thang/VectorIconSetupModal.coffee, app/views/modal/ModelModal.coffee, app/views/play/modal/PlayAchievementsModal.coffee
Refactored MainAdminView, SubscribeModal, AchievementEditView, PlayAchievementsModal, LevelThangEditView, PollEditView, VectorIconSetupModal, ModelModal, PlayAchievementsModal.
=> Refactor to use view in template

scripts/batchAddAchievements.js
When running the script, you'll want to download the latest version of the New Achievements spreadsheet as a CSV and toss it in the directory.
=> Adds the start of the batchAddAchievements node script.

app/locale/pt-BR.coffee
Traduzi a parte do "Hour of Code" que ainda estava em inglês.
E algumas outras coisinhas.
=> Atualização Tela inicial- Front page update

app/locale/pt-BR.coffee
=> Update Pt-Br -Translation

Vagrantfile, scripts/vagrant/fillMongo.sh, scripts/vagrant/provision.sh
* Use Ubuntu 14.04 box which supports both VMWare and Virtualbox
* Correctly set memory/CPU settings for vmware_fusion provider
* Use nodesource repo instead of deprecated chris-lea PPA for installing node.js
* Upgrade npm to latest version
* Correct permissions for provisioner script (npm module install)
=> Fix up vagrant config

app/templates/admin/level_sessions.jade, app/templates/core/modal-base.jade, app/templates/editor/component/thang-component-config-view.jade, app/templates/editor/level/component/new.jade, app/templates/editor/level/modal/new-achievement.jade, app/templates/editor/level/related-achievements.jade, app/templates/editor/level/system/level-system-edit-view.jade, app/templates/editor/modal/new-model-modal.jade, app/templates/editor/modal/save-version-modal.jade, app/views/admin/LevelSessionsView.coffee, app/views/core/ModalView.coffee, app/views/editor/component/ThangComponentConfigView.coffee, app/views/editor/level/RelatedAchievementsView.coffee, app/views/editor/level/components/NewLevelComponentModal.coffee, app/views/editor/level/modals/NewAchievementModal.coffee, app/views/editor/level/systems/LevelSystemEditView.coffee, app/views/editor/modal/NewModelModal.coffee, app/views/editor/modal/SaveVersionModal.coffee, app/views/play/modal/PlayAccountModal.coffee
LevelSessionsView, ModalView, ThangComponentConfigView, RelatedAchievementsView, NewLevelComponentModal, NewAchievementModal, LevelSystemEditView, NewModelModal, SaveVersionModal and PlayAccountModal.
Issue #3138
=> Use view in template

app/models/Level.coffee
The code has been shortened. The properties have been cached, so the performance has been improved.
=> Refactor Level.coffee

app/locale/fr.coffee, app/locale/ja.coffee
Updates on French locale file
I want to see what Clans et Courses are like before I translate their entries.
Ajouts d'entrées FR
Il reste les entrées Courses et Clans, où je voudrais voir à quoi ça ressemble avant de trouver les traductions.
=> Updates FR locale file

app/styles/sales-view.sass, app/templates/sales-view.jade
Fixed quote per teacher (Tim M.)’s request, added Twitter link
Adjusted font sizing and positioning on quotes.
Added smart (curly) quotes instead of straight quotes.
=> Cleaned up teacher testimonial area

app/locale/ko.coffee
This has translated this means.
265 : Holy smokes -> Surprise [놀라다]
=> My second ko translation.

app/views/play/level/tome/DocFormatter.coffee
=> Add additional formatting tags to Tome popup

app/collections/Achievements.coffee, app/collections/LevelSessions.coffee, app/collections/ThangTypes.coffee, app/styles/common/common.sass, app/styles/play/level/modal/course-victory-modal.sass, app/styles/play/level/modal/new-item-view.sass, app/styles/play/level/modal/progress-view.sass, app/templates/admin/design-elements-view.jade, app/templates/play/level/modal/course-victory-modal.jade, app/templates/play/level/modal/new-item-view.jade, app/templates/play/level/modal/progress-view.jade, app/views/core/CocoView.coffee, app/views/play/level/PlayLevelView.coffee, app/views/play/level/modal/CourseVictoryModal.coffee, app/views/play/level/modal/NewItemView.coffee, app/views/play/level/modal/ProgressView.coffee, test/app/views/play/level/modal/CourseVictoryModal.fixtures.coffee, test/app/views/play/level/modal/CourseVictoryModal.spec.coffee, vendor/scripts/jasmine-boot.js, vendor/scripts/jasmine.js
Creates a new victory modal, which is only set up for when you’re playing a level within a course. TODOs stemming from this first step:
* Finish rest of migration from VictoryModal and HeroVictoryModal to CourseVictoryModal (and rename back to VictoryModal).
* Animate the new item icon (@nwinter need to discuss animations with you).
* Create static or dynamic graphics for well-parchment, img-prize and label-banner.
=> Course victory modal

app/templates/play/level/tome/cast_button.jade, app/views/play/level/tome/CastButtonView.coffee
=> Refactor CastButtonView to use view in template

app/core/forms.coffee, app/locale/en.coffee, app/templates/request-quote-view.jade, app/views/RequestQuoteView.coffee, server/trial_requests/trial_request_handler.coffee
* If logged in => repopulate and lock email (and name if available)
* If logged out => disallow using an email for an existing account and display a validation message + login link
=> Restrict request quote emails

app/styles/about.sass
This just shrinks the margins on the labels at tiny screens. Looks pretty okay IMO. Doesn't quite fit the smallest window size I could manage but at least all they buttons are partially visible.
=> Improve responsiveness on fixed nav

app/locale/en.coffee, app/templates/play/level/level_loading.jade
Some lines added to the level loading screen text selector, just to test out the workflow of the project, as suggested in the wiki.
=> Added some lines for #710

app/assets/main.html, app/core/forms.coffee, app/models/User.coffee, app/templates/admin.jade, app/views/admin/MainAdminView.coffee, app/views/core/RootView.coffee, server/middleware/auth.coffee, server/models/User.coffee, server/routes/auth.coffee, server/routes/index.coffee, server/users/User.coffee, server/users/user_handler.coffee, server_setup.coffee, spec/server/functional/auth.spec.coffee, spec/server/utils.coffee
Also:
* Refactor various related pieces (forms, endpoints)
* Add a keyboard shortcut for admins to navigate to the admin page
=> Add return-to-admin ability (turn off espionage mode)

app/locale/da.coffee, app/locale/en.coffee, app/locale/ms.coffee, app/locale/ro.coffee, app/locale/zh-WUU-HANT.coffee, app/templates/admin.jade, app/templates/admin/clas.jade, app/templates/admin/level_sessions.jade, app/templates/admin/pending-patches-view.jade, app/templates/admin/user-code-problems.jade, app/templates/admin/users.jade
I don't think it is necessary to have i18n in admin pages.
What do you think?
=> Remove i18n from admin pages

app/templates/base-flat.jade
=> updated new homepage header (i18n)

app/templates/editor/achievement/edit.jade, app/views/editor/achievement/AchievementEditView.coffee
Solves #3266 
Made the treema visible to be build, but disabled and hidden the buttons.
The: 
readOnly: me.get('anonymous')
In AchievementEditView.coffee
Seems to already make the Treema read only for admins if I'm correct? 
If you had something different in mind let me know.
=> Error when accessing achievement without being logged in

app/lib/LevelLoader.coffee, app/models/User.coffee, app/templates/play/level/control_bar.jade, app/templates/play/level/modal/progress-view.jade, app/views/play/level/ControlBarView.coffee, app/views/play/level/PlayLevelView.coffee, app/views/play/level/modal/CourseVictoryModal.coffee
This fixes the "broken campaign mode for teachers" bug introduced by https://github.com/codecombat/codecombat/commit/a524256b5b4694e1d97396dba90e050986a992a8 when they tried to play through `/play`.
=> Fix campaign for teachers

app/views/core/AuthModal.coffee
Added a subscription so the appropriate function is called when we get a server error, making the close button reappear.
=> Fix close button disappearing - fixes #3522

app/locale/uk.coffee
Found a better word for 'engaging'
Added more translations
=> Add some more translations

app/locale/uk.coffee
Found better phrase for 'codecombat_is'.
Added more translations.
=> Add more translations

app/views/courses/CoursesView.coffee, server/handlers/classroom_handler.coffee, server/middleware/classrooms.coffee, server/routes/index.coffee, spec/server/functional/classrooms.spec.coffee
Moved joining free CourseInstance logic from client to server, so that when you join a classroom, the same endpoint also adds you to any related, free CourseInstances.
=> Make joining classrooms more stable

app/templates/community-view.jade
=> fix community page layout

app/lib/world/rand.coffee
As in python random module. It can be useful for levels instead "someArray[@world.rand.rand(someArray.length)]".
=> Add `choice` method in `rand`

server/handlers/classroom_handler.coffee, server/middleware/classrooms.coffee
Add some manual error message logging for debugging sporadic problems with students joining classes.
=> Log forbiddens

app/locale/es-ES.coffee, app/locale/pt-PT.coffee, app/locale/sr.coffee
Uncomment headers and change translation
=> Fix some i18n files

app/locale/de-AT.coffee
In some strings the contexts are missing, so its hard to translate.
=> Adding some German words

app/views/editor/campaign/CampaignEditorView.coffee
Clicking on level in treema makes the level flash in the campaign view
=> Clicking on level in treema makes the level flash

app/locale/nl-NL.coffee
=> Spelling Update nl-NL.coffee

app/views/core/CreateAccountModal/SegmentCheckView.coffee
Bug reports:
* https://discourse.codecombat.com/t/changing-from-student-account/8336/7
* https://discourse.codecombat.com/t/cannot-register-a-free-account/8359
* https://discourse.codecombat.com/t/ive-possibly-run-into-a-login-bug/8349/2
=> Fix birthday form validation in signup

app/locale/ru.coffee
Add "hints" translations in the editor UI
=> Update ru.coffee - hints ui

app/views/play/CampaignView.coffee
So they point more accurately to the next level.
Campaign editor, not just public-facing campaign
=> Tweak campaign connecton arrows

app/styles/docs/components-documentation-view.sass, app/templates/editor/level/edit.jade, app/templates/editor/level/related-achievements.jade, app/templates/editor/level/tasks-tab.jade
Pretty much all the same issue.
=> fixes #3796 #3794 #3793 

app/locale/en.coffee, app/schemas/schemas.coffee, app/templates/play/level/tome/spell_palette_entry_popover.jade, app/views/play/level/tome/DocFormatter.coffee, app/views/play/level/tome/SpellPaletteView.coffee, app/views/play/level/tome/TomeView.coffee
This adds support for the `programming.UsesJQuery` and `programming.UsesWebJavaScript` components.
It also adds an "optional" flag for API arguments, which slightly alters the display of the doc popover.
=> Code review: Add support for optional arguments, and web components

app/core/urls.coffee, app/locale/en.coffee, app/styles/courses/teacher-class-view.sass, app/templates/courses/teacher-class-view.jade, app/views/courses/TeacherClassView.coffee
Also remove templating for deprecated progress tab
=> Add project/arena pills to course progress tab to TeacherClassView

app/lib/world/names.coffee
New thing names as first commit for beginner.
=> Thang name contributions

app/assets/markdown/cs1.md, app/assets/markdown/cs2.md, app/locale/en.coffee, app/styles/teachers/ResourceHubView.sass, app/styles/teachers/markdown-resource-view.sass, app/templates/teachers/markdown-resource-view.jade, app/templates/teachers/resource-hub-view.jade, app/views/teachers/MarkdownResourceView.coffee
- Add cs1.md, cs2.md for individual course guides
- Separated markdown-resource-view.sass from ResourceHubView.sass
- Modified MarkdownResourceView.coffee to template-ize guide pages better.
=> Create Markdown for CS1, CS2 Curriculum

app/assets/markdown/cs2.md
Fixing some line break issues with CS2 guide in Markdown that weren't caught earlier.
=> Update formatting on CS2 Guide

app/assets/markdown/getting-started.md, app/styles/teachers/markdown-resource-view.sass, app/templates/teachers/resource-hub-view.jade
- Add getting-started.md
- Edited some sass to make formatting/printing
- Replace PDF link on /teachers/resources
- Add .pngs to app/assets/images/pages/resources
@basicer -- should these .pngs live on files.codecombat.com or is this assets folder okay?
=> Add Getting Started guide in Markdown

app/locale/en.coffee, app/templates/new-home-view.jade
Should we use the same image as on the new About page? 
Looks like: 
https://www.dropbox.com/s/0vthces1toefutc/Screen%20Shot%202016-08-29%20at%206.13.48%20PM.png?dl=0
@differentmatt thoughts?
=> Remove Java from homepage, Update languages

app/assets/markdown/cs2.md, app/assets/markdown/cs3.md
Changes to course progression/levels reflected in updated guide,
properties and input handling moved to draft CS3 guide.
=> Update CS2 Guide

app/assets/javascripts/web-dev-listener.js, app/templates/play/level/web-surface-view.jade, app/views/play/level/WebSurfaceView.coffee, server_config.coffee, server_setup.coffee
Still TODO:
- Use ENV variables for URLs instead of hardcoding codecombatprojects.com, etc? Use different ones for production/staging?
- Point codecombatprojects.com at production server
=> Code Review: Filter domains for webdev iFrame

app/locale/en.coffee, app/models/CourseInstance.coffee, app/models/LevelSession.coffee, app/templates/play/level/modal/progress-view.jade, app/templates/play/level/tome/spell-top-bar-view.jade, app/views/play/level/tome/SpellTopBarView.coffee, test/app/models/CourseInstance.spec.coffee
=> Handle shareable levels when previewing them as a teacher

app/views/editor/campaign/CampaignEditorView.coffee, app/views/play/CampaignView.coffee, app/views/play/level/modal/HeroVictoryModal.coffee
Hedge Magic will need to be adjusted if we go with another project level.
Will also need to differentiate start/end tracking pixels by HoC activity, but we don't have those yet.
=> Add logic for /play/game-dev-hoc?hour_of_code=true new game dev HoC activity

app/locale/zh-HANS.coffee
Update FAQ Chinese translation to 常见问题
=> Translate FAQ

app/locale/ms.coffee
=> Update Malay translation

app/assets/javascripts/web-dev-listener.js, app/assets/web-dev-iframe.html, app/lib/HtmlExtractor.coffee, app/schemas/subscriptions/web-dev.coffee, app/views/play/level/WebSurfaceView.coffee, app/views/play/level/tome/SpellView.coffee, config.coffee, test/app/lib/HtmlExtractor.spec.coffee, test/app/views/play/level/WebSurfaceView.spec.coffee, vendor/scripts/css.js, vendor/scripts/deku.js, vendor/scripts/htmlparser2.js
This parses the user's stylesheet and JS and gets a list of all CSS selectors (as CSS, or jQuery calls). Then whenever you hover over a line that looks like one of those CSS selectors, it will tell the web-dev iframe to highlight any nodes that match that selector.
=> Highlight css selectors

app/locale/es-ES.coffee
Hi. I have some free minutes so i supossed it could be helpfull to translate some lines. Im testing the way to collaborate. If this is the correct way i will make more translations in the future !! Best regards.
Lines 1962-1972 translated
1960 changed from "ciclos" to "bucles While"
=> Lines 1962-1972 translated

app/lib/world/rand.coffee
Random `j` should be `0 <= j <= i`.
=> Fix random shuffle implementation

server/handlers/user_handler.coffee
Because, China Loading avatar 404 error!
So,I change it!
=> Because, China Loading avatar 404 error!

Vagrantfile, scripts/vagrant/core/provision.sh
1) certain versions (1.8.7 specifically) doesn't work with coco
2) set execute permissions for mongo dump script
=> Fix vagrant

app/views/editor/poll/PollEditView.coffee
Both html and js need to check for Admin. This fixes the js. The html was already correctly checking for it and erroring.
=> Fix #4006 - Poll Editing requires Admin permissions

app/templates/courses/teacher-classes-view.jade, app/templates/teachers/teacher-student-view.jade, app/views/courses/TeacherClassView.coffee, app/views/teachers/TeacherStudentView.coffee
This fixes teacher classes page from displaying in the wrong order.
=> Sort classes whenever getting classes

app/templates/courses/teacher-courses-view.jade, app/templates/teachers/create-teacher-account-view.jade, app/views/teachers/CreateTeacherAccountView.coffee
Check the teacher name and email for uniqueness and suggest login, exactly the same way CreateAccountModal does.
=> Teacher name check

app/core/utils.coffee, app/styles/play/campaign-view.sass, app/templates/play/campaign-view.jade, app/views/play/CampaignView.coffee
For every unlock, gotta figure out the Item type.
Instead of making (5 or more) * (# of levels with item) requests, we manually cache the result.
Once we have the result, we display it.
Tada!
=> Pet campaign images

app/lib/LevelLoader.coffee
This fixes the editor not loading, but I'm not sure I understand all the permutations of what's going on in this code, so it could be the wrong way to fix it.
=> Fix for level editor not loading

app/locale/en.coffee, app/templates/play/modal/announcement-modal.jade, app/templates/play/modal/announcements/1.jade, app/views/play/CampaignView.coffee, app/views/play/modal/AnnouncementModal.coffee
=> Implement copy fixes

app/locale/en.coffee, app/views/play/CampaignView.coffee, app/views/play/level/PlayLevelView.coffee
=> Disable minecraft modal

app/locale/en.coffee, app/templates/core/create-account-modal/coppa-deny-view.jade, app/views/core/CreateAccountModal/CoppaDenyView.coffee
Tell them to stop it if they put "team@codecombat.com" into CoppaDenyView.
=> Don't let them put team@codecombat.com in CoppaDenyView

app/views/core/CreateAccountModal/BasicInfoView.coffee, app/views/core/CreateAccountModal/CoppaDenyView.coffee, app/views/core/CreateAccountModal/CreateAccountModal.coffee, app/views/core/CreateAccountModal/ExtrasView.coffee, app/views/core/CreateAccountModal/teacher/DemographicsPanel.coffee, app/views/core/CreateAccountModal/teacher/SchoolInfoPanel.coffee, app/views/core/CreateAccountModal/teacher/SetupAccountPanel.coffee, app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee
Tracks when the user clicks the "next" button, when that next button succeeds (implicitly tracking when it fails), and when they click the "back" button.
=> Track signup modal panel nav button clicks

app/templates/play/campaign-view.jade, app/views/play/CampaignView.coffee
- Don't try to look up the course-instance if we already know what it is
- Make play button full width in student view.
=> Tweak Campaign Map View

app/lib/LevelSetupManager.coffee, app/locale/en.coffee, app/models/Classroom.coffee, app/templates/play/campaign-view.jade, app/templates/play/menu/inventory-modal.jade, app/templates/play/modal/earn-gems-prompt.jade, app/templates/play/modal/item-details-view.jade, app/views/play/CampaignView.coffee, app/views/play/menu/InventoryModal.coffee, app/views/play/modal/ItemDetailsView.coffee
Add the inventory to the classroom
This pull request contains:
Fixes to loading race conditions in the Classroom World Map.
Opens the InventoryModal every time the player starts a level, or clicks the newly added Classroom Items button in the World Map.
Tweaks InventoryModal to hide non-classroom things (such as the hero selector and item properties (health, moveRight, etc))
=> Classroom items

app/styles/play/campaign-view.sass, app/templates/play/campaign-view.jade, app/views/play/CampaignView.coffee
Visuals: https://www.dropbox.com/s/802fk40rbrtzt9m/Screen%20Shot%202017-05-16%20at%204.36.09%20PM.png?dl=0
Adds a premium button directly to the campaign menu bar.
Should open the subscribe modal when clicked, and have a trackable event tag. Shouldn't be visible to our free players (students, free servers, etc)
=> Adds Subscribe button to menu bar

server/handlers/user_handler.coffee, server/middleware/subscriptions.coffee, server/middleware/users.coffee, server/routes/index.coffee, spec/fixtures/sub-test-01.json, spec/fixtures/sub-test-02.json, spec/fixtures/sub-test-03.json, spec/fixtures/sub-test-04.json, spec/fixtures/sub-test-05.json, spec/fixtures/sub-test-06.json, spec/fixtures/sub-test-07.json, spec/fixtures/sub-test-08.json, spec/fixtures/sub-test-09.json, spec/fixtures/sub-test-10.json, spec/fixtures/sub-test-11.json, spec/fixtures/sub-test-12.json, spec/fixtures/sub-test-35.json, spec/fixtures/sub-test-36.json, spec/fixtures/sub-test-37.json, spec/fixtures/sub-test-38.json, spec/fixtures/sub-test-39.json, spec/fixtures/sub-test-41.json, spec/helpers/helper.js, spec/server/functional/subscription.spec.coffee, spec/server/functional/user.spec.coffee
Fixes unsubscribing on user delete.
Refactored the user-delete endpoint, and fixed up several related tests. Also regenerated the stripe request fixtures.
=> Refactor user delete endpoint, fix tests

app/core/Tracker.coffee, app/core/application.coffee, app/core/services/segment.coffee, app/models/User.coffee, app/schemas/models/user.coffee, app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coffee, app/views/teachers/CreateTeacherAccountView.coffee, package.json, server/lib/intercom.coffee, server/middleware/levels.coffee, server_config.coffee, test/app/core/Tracker.spec.coffee
Reports some new intercom-related values to Intercom and makes sure the user gets the intercom bubble opened when they happen.
=> Intercom triggers

app/core/services/paypal.coffee, app/locale/en.coffee, app/models/Product.coffee, app/schemas/models/payment.schema.coffee, app/schemas/models/user.coffee, app/styles/modal/subscribe-modal.sass, app/templates/account/payments-view.jade, app/templates/core/subscribe-modal.jade, app/views/core/SubscribeModal.coffee, package.json, server/lib/paypal.coffee, server/lib/stripe_utils.coffee, server/middleware/subscriptions.coffee, server_config.coffee, spec/server/functional/subscription.spec.coffee, test/app/views/core/SubscribeModal.spec.coffee
Add the ability to purchase year or lifetime subscriptions through PayPal.
=> Paypal Sync Subscription Payments

app/styles/play/modal/play-items-modal.sass, app/templates/play/modal/item-details-view.jade, app/templates/play/modal/play-items-modal.jade, app/views/play/modal/PlayItemsModal.coffee
=> Add Subscribe button for subscriber only items in item store.

app/core/application.coffee, app/styles/play/level/game_dev_track_view.sass, app/templates/play/level/game_dev_track_view.jade, app/templates/play/level/modal/hero-victory-modal.jade, app/views/play/CampaignView.coffee, app/views/play/level/ControlBarView.coffee, app/views/play/level/GameDevTrackView.coffee, app/views/play/level/modal/HeroVictoryModal.coffee, app/views/play/menu/InventoryModal.coffee, app/views/play/modal/PlayHeroesModal.coffee, app/views/play/modal/PlayItemsModal.coffee, server/middleware/level-sessions.coffee, server/middleware/levels.coffee, server/routes/index.coffee, spec/server/functional/level.spec.coffee, spec/server/functional/level_session.spec.coffee
Updates to the game for the Game Dev Hour of Code activity.
* Make accessible all game-dev levels and game-dev db functionality to anonymous HoC players
* Further suppress signup and payment prompts
* UI bug fixes and updates
=> Game dev hoc

app/locale/en.coffee, app/styles/courses/teacher-class-view.sass, app/templates/courses/teacher-class-view.jade
Adds an "create new classroom" nag to the top of classrooms that were created over 6 months ago.
=> Create classroom nag

app/lib/coursesHelper.coffee, app/templates/courses/teacher-classes-view.jade, app/templates/teachers/hovers/progress-dot-whole-course.jade, app/views/courses/TeacherClassesView.coffee
Skip sessions for archived classrooms
Render UI before all sessions loaded
Only create and insert course nag subview once
Artificially threw random 503s for member-sessions calls to ensure it
works alright.  Course bubbles with 503s remain in Loading.. state.
=> Classes view loading improvements

app/assets/javascripts/web-dev-listener.js
This fixes issues where line numbers were misreported or missing in web-dev levels when an error occurs.
Some errors unfortunately are unable to be parsed for line numbers because of the way that `window.onerror` (and global error event listeners) work, which do not include the stack trace that ends up in the console. For those errors, we return line:0, column:0 which points the user to the `<script>` line.
This fix revealed a behavior that we may want to change: When typing code, if an error occurs in the code you've typed, and you haven't clicked "run" recently, it will display `This error was generated by old code — Try running your new code first` every time you type a character. The fix for this is probably to make `userCodeHasChangedSinceLastCast` be determined differently. This bug …
=> Fix webdev error line numbers where possible

app/views/admin/MainAdminView.coffee, app/views/play/level/tome/TomeView.coffee, server/middleware/api.coffee, server/middleware/users.coffee, server/models/APIClient.coffee, spec/server/functional/api.spec.coffee
Looks like I had some old localhost search fixes commit on there too for some reason, oops.
=> Brazil api subscriptions

app/core/Tracker.coffee, app/core/ViewLoadTimer.coffee, server.coffee, server_config.coffee, webpack.base.config.js
Add extra filtering and options for measuring load times
=> Improve view load timer

karma.conf.js
This seems to make it better. Tried rebuilding the same thing 10 times in a row, Firefox always loaded.
=> Travis karma tolerance

app/lib/LevelSetupManager.coffee
Fix typos in last commit:
Omarn, not Pender
Griffin, not Cougar
=> Escort Duty setup

app/views/play/level/PlayLevelView.coffee
Fix hero to Omarn and pet to griffin.
=> Update for Escort Duty

app/locale/locale.coffee, app/views/contribute/DiplomatView.coffee, app/views/core/RootView.coffee, app/views/editor/verifier/i18nVerifierView.coffee, server/routes/index.coffee, server/routes/languages.coffee, spec/server/unit/locale.spec.coffee
See https://github.com/codecombat/codecombat/commit/b470c3890efa840d8612edbf37eb41698af51a57#commitcomment-25491649
=> Don't enumerate locale helper functions

app/lib/ThangTypeLib.coffee, app/locale/he.coffee, app/schemas/models/thang_type.coffee, app/views/courses/CoursesView.coffee, app/views/editor/thang/ThangTypeEditView.coffee, app/views/i18n/I18NEditThangTypeView.coffee, app/views/play/level/modal/HeroVictoryModal.coffee, app/views/play/modal/PlayHeroesModal.coffee, scripts/mongodb/translation-import.js, server/handlers/thang_type_handler.coffee
Update some related i18n systems accordingly.
=> Move ThangType short names and genders to the ThangType models

app/assets/apcsp-local/index.md, app/assets/apcsp-local/nested/1.md, app/core/Router.coffee, app/core/api/apcsp.coffee, app/core/api/index.coffee, app/core/api/markdown.coffee, app/lib/dynamicRequire.coffee, app/schemas/models/user.coffee, app/styles/teachers/markdown-resource-view.sass, app/templates/admin/administer-user-modal.jade, app/templates/teachers/dynamic-apcsp-view.jade, app/views/admin/AdministerUserModal.coffee, app/views/teachers/DynamicAPCSPView.coffee, server/commons/errors.coffee, server/middleware/apcsp.coffee, server/middleware/index.coffee, server/middleware/users.coffee, server/routes/index.coffee, server_config.coffee, spec/server/functional/apcsp.spec.coffee, spec/server/functional/user.spec.coffee
This is a page which, through the server, proxies files served separately. For development, the page will show the files in `/app/assets/apcsp-local`. Also add verified teacher property and admin interface for it. Only verified teachers can access this content. Reused some logic from the existing markdown view.
=> Add APCSP hub

app/templates/courses/teacher-classes-view.jade, app/views/courses/TeacherClassesView.coffee
Temporarily disabled for HoC server stability
=> Put back /teachers/classes progress dots and teacher quests

app/lib/LevelSetupManager.coffee, app/views/play/level/PlayLevelView.coffee
The pet there allows blocking enemy peasant totally. Also, it has cut functionality and spell pallete shows it as full.
=> Removed the pet from escrot-duty

app/lib/world/line_segment.coffee
If both segments are vertical (slope is +-Infinity) and they have the same `x` coordinate.
=> The special case for line segment intersection

app/locale/en.coffee, app/models/Level.coffee, app/styles/teachers/teacher-student-view.sass, app/templates/courses/teacher-class-view.jade, app/templates/teachers/hovers/progress-dot-all-students-single-level.jade, app/templates/teachers/hovers/progress-dot-single-student-level.jade, app/templates/teachers/teacher-student-view.jade, app/views/teachers/TeacherStudentView.coffee
Putting student code and solutions in student profile pages linked off
teacher class view.
=> Allow teachers to review student code

app/lib/surface/Surface.coffee, app/lib/world/world.coffee, app/lib/world/world_frame.coffee, app/locale/en.coffee, app/models/LevelSession.coffee, app/schemas/models/level.coffee, app/schemas/models/level_session.coffee, app/schemas/schemas.coffee, app/schemas/subscriptions/play.coffee, app/styles/play/level/control-bar-view.sass, app/templates/play/level/control-bar-view.jade, app/views/play/level/ControlBarView.coffee
Can only test by setting a level assessment type to `open-ended` and adding a `scoreType` (will use the first one in the list). Here's a test level configured that way: https://staging.codecombat.com/play/level/desert-maze-open-scoreboard-test
=> Scoreboard

app/locale/en.coffee, app/locale/fr.coffee, app/templates/play/modal/item-details-view.jade, app/templates/play/modal/play-items-modal.jade
Hello, i'm a new to open source so sorry in advance for anything, i could have gotten wrong. 
I fixed the issue 4382. I added 3 new strings translation in the coffee.en ( and their corresponding translation in french ) cause i think there might be some language where u can't just translate it with 2 words or in the same order. So that's why i didnt concatenate from heroClass + adding a translation for "Only".
Any feedback is really appreciated.
=> Fixed #4382

app/styles/teachers/teacher-student-view.sass, app/templates/teachers/teacher-student-view.jade, app/views/teachers/TeacherStudentView.coffee
Fix anchor linking with dropdown filtering
Replace question mark tooltips with better ones
Add text if no provided solution
=> :bug:Student code review fixes

app/collections/Levels.coffee, app/models/Level.coffee, app/styles/teachers/teacher-course-solution-view.sass, app/styles/teachers/teacher-student-view.sass, app/templates/teachers/teacher-course-solution-view.jade, app/templates/teachers/teacher-student-view.jade, app/views/teachers/TeacherCourseSolutionView.coffee, app/views/teachers/TeacherStudentView.coffee
Add tabbed solutions in teacher student view and course solutions.
Update solutions to be localized.
Fix a few ace editor syntax highlighting problems for wd2.
Add fingerprinting to student view.
=> Add support for multiple solutions in classroom UI

app/core/store/modules/game.coffee, app/lib/LevelBus.coffee, app/schemas/models/level_session.coffee, app/views/play/level/PlayLevelView.coffee, app/views/play/level/tome/editor/snippets.coffee, server/models/LevelSession.coffee
Save these values to level sessions
=> Add tracking for autocompletes, code runs, hint time

app/core/Router.coffee, app/core/api/campaigns.coffee, app/core/api/levels.coffee, app/lib/dynamicRequire.js, app/templates/artisans/artisans-view.jade, app/views/artisans/ArrayInput.vue, app/views/artisans/BulkLevelEditComponent.vue, app/views/artisans/BulkLevelEditView.coffee, app/views/artisans/BulkLevelEditorComponent.vue
Initial attempt at bulk level edit tool. Likely to add more editable fields later.
=> Bulk Level Edit v0

app/schemas/models/user.coffee, server/handlers/user_handler.coffee, server/middleware/users.coffee, server/models/User.coffee
For new users, do not save the lastIP, instead get the geo location object using the IP and save it in the db
=> Remove lastIP and add geo object for new users

app/core/Router.coffee, app/lib/dynamicRequire.js, app/models/User.coffee, app/schemas/models/user.coffee, app/styles/user/user-opt-in-view.sass, app/templates/user/user-opt-in-view.jade, app/views/user/UserOptInView.coffee, server/middleware/users.coffee, server/routes/index.coffee, spec/server/functional/user.spec.coffee
Based on query params:
Automatically prevent deletion of inactive users
Automatically subscribe to general announcements
Prompt to subscribe to general announcements
=> Add user opt-in page

app/core/utils.coffee, app/views/courses/TeacherCoursesView.coffee, app/views/teachers/TeacherCourseSolutionView.coffee, test/app/core/utils.spec.coffee
IE11 does not support Array.find
=> IE11 bug fixes

app/views/courses/TeacherClassAssessmentsTable.vue
Fix for following bug - 
https://app.asana.com/0/722742542311550/601790069057660
=> Fix for assessment tab to show message instead of empty table.

app/styles/play/level/control-bar-view.sass
Fix for - 
https://app.asana.com/0/722742542311550/474384180350653
=> Increased max-width of level-name-area to accomodate longest level name.

app/locale/en.coffee, app/models/Prepaid.coffee, app/templates/courses/enrollments-view.jade
Code changes for - 
https://app.asana.com/0/722742542311550/628667767388210
Change the second line of text on the license 'card' to follow this structure: 
18 out of 45 licenses used
=> Show total licenses in the message displayed on license card.

app/templates/play/modal/amazon-hoc-modal.jade, app/views/play/level/modal/HeroVictoryModal.coffee, app/views/play/modal/AmazonHocModal.coffee
This reverts the commit f0c6830e1d31b68a7d5d45b3d56e10604a4bbb37.
=> Revert "Add amazon HOC modal after level 4 (#4756)"

app/models/User.coffee, app/templates/core/auth-modal.jade, app/templates/core/create-account-modal/basic-info-view.jade, app/templates/teachers/create-teacher-account-view.jade, app/templates/teachers/request-quote-view.jade, server_config.coffee, server_setup.coffee
Adding new server configuration key chinaInfra, set by process.env.COCO_CHINA_INFRASTRUCTURE
=> Hide Facebook/Google login when on China infrastructure

app/views/courses/TeacherClassView.coffee
Our bulk student assign needs to handle student licenses with larger counts (e.g. 1 billion) for our test automation.
=> :bug:Fix big student license assigns

LICENSE
License year updated to the current year.
=> Updated license's year to 2018

app/styles/courses/enrollments-view.sass
Fix layout by removing the height CSS constraint.
=> Fix student licenses layout of 'Share Licenses' button

app/core/api/courses.coffee, app/locale/en.coffee, app/styles/courses/teacher-courses-view.sass, app/templates/courses/teacher-courses-view.jade, app/views/courses/TeacherCoursesView.coffee
Related changes in server- https://github.com/codecombat/codecombat-server/pull/6
=> Changes to show course change log in course guides

.travis.yml, app/assets/javascripts/run-tests.js, package.json, webpack.karma.config.js
- Local karma tests should also work now (under both environments)
=> Added client side china environment tests

app/core/Router.coffee, app/core/api/api-clients.coffee, app/core/application.coffee, app/core/services/segment.coffee, app/core/social-handlers/FacebookHandler.coffee, app/core/social-handlers/GPlusHandler.coffee, app/core/social-handlers/GitHubHandler.coffee, app/models/User.coffee, app/schemas/models/api-client.schema.coffee, app/schemas/models/feature.schema.coffee, app/schemas/models/user.coffee, app/templates/base-flat.jade, app/templates/base.jade, app/templates/core/auth-modal.jade, app/templates/core/create-account-modal/basic-info-view.jade, app/templates/teachers/create-teacher-account-view.jade, app/templates/teachers/request-quote-view.jade, app/views/LicensorViewComponent.vue, app/views/core/AuthModal.coffee, app/views/core/CreateAccountModal/CreateAccountModal.coffee, compile-static-templates.coffee, static-mock.coffee, test/app/views/core/AuthModal.spec.coffee, test/app/views/teachers/CreateTeacherAccountView.spec.coffee, test/app/views/teachers/RequestQuoteView.spec.coffee
Add /licensor UI to allow admins or licensors to update API Client feature flags dynamically.
Replace me.onChinaInfra with me.useSocialSignOn to make UX changes less coupled to low-level feature flag names.
Add feature flag schema and update user and api-client schemas to maintain feature flag settings.
=> Dynamic user feature flags

.babelrc, app/assets/javascripts/run-tests.js, app/views/admin/CLAsComponent.vue, package.json, webpack.base.config.js
Lets us use ES6 for new files and slowly move away from Coffeescript.
=> Add es6 loader to webpack

app/core/api/api-clients.coffee, app/schemas/models/api-client.schema.coffee, app/templates/contribute/diplomat.jade, app/views/LicensorViewComponent.vue, app/views/contribute/DiplomatView.coffee
Add licenseTimeGranted in APIClients and make it editable from /licensor page.
Please ignore the first commit related to diplomat changes: That commit is already in master, but not in api-client-permissions branch and since I am comparing this PR with api-client-permissions PR, thats why it is showing this change.
=> Api client license stats

app/core/api/api-clients.coffee, app/core/utils.coffee, app/models/User.coffee, app/schemas/models/api-client.schema.coffee, app/templates/courses/enrollments-view.jade, app/templates/courses/teacher-class-view.jade, app/templates/courses/teacher-classes-view.jade, app/templates/courses/teacher-dashboard-nav.jade, app/templates/teachers/edit-student-modal.jade, app/views/LicensorViewComponent.vue, app/views/courses/EnrollmentsView.coffee, app/views/courses/TeacherClassView.coffee, app/views/courses/TeacherClassesView.coffee, app/views/courses/TeacherCoursesView.coffee, app/views/teachers/ApCsPrinciplesView.coffee, app/views/teachers/DynamicAPCSPView.coffee, app/views/teachers/EditStudentModal.coffee, app/views/teachers/MarkdownResourceView.coffee, app/views/teachers/ResourceHubView.coffee, app/views/teachers/RestrictedToTeachersView.coffee, app/views/teachers/StarterLicenseUpsellView.coffee, app/views/teachers/TeacherCourseSolutionView.coffee, app/views/teachers/TeacherStudentView.coffee
Added permissions in APIClient schema and made them editable from /licensor page
Implemented UI permissions - to show/hide license management from UI for teachers based on their client's permissions
=> Add and implement permissions for APIClients

app/templates/home-view.jade
Implementation of UserLeap integration on the home page. 
https://app.asana.com/0/722742542311550/761793655033884/f
=> UserLeap integration on home page.

app/models/User.coffee, app/templates/static/layout.static.pug, compile-static-templates.coffee, static-mock.coffee
Not handling serviceWorker unregister if chinaInfra=true.
=> No Dexecure if chinaInfra=true

app/models/User.coffee, app/styles/play/level/modal/course-rewards-view.sass, app/templates/play/level/modal/course-rewards-view.jade, app/views/play/CampaignView.coffee, app/views/play/level/modal/CourseRewardsView.coffee, app/views/play/level/modal/CourseVictoryModal.coffee
Added a new view(CourseRewardsView) which will show up before the existing course victory component on completing a level. Basically, brought some logic from home HeroVictoryModal to this new view.
=> Show Gems, XP, Items in classroom levels if classroomItems flag is true.

app/locale/en.coffee, app/templates/editor/level/save-level-modal.jade, app/templates/editor/patch_modal.jade, app/views/editor/PatchModal.coffee, app/views/editor/PatchesView.coffee, app/views/editor/level/LevelEditView.coffee, app/views/editor/level/modals/SaveLevelModal.coffee
* Works for admin and levels only
=> Added "Accept&Save" feature for level patches.

app/views/play/menu/InventoryModal.coffee
Improved behavior of popup. It is handled in the various code paths that were causing it to be stuck on the screen.
=> :bug: Fix stuck popup on InventoryModal

app/templates/play/modal/item-details-view.jade
Interestingly, this is just a UI fix.
=> :bug: Allow pets to be bought with gems

app/core/Router.coffee
- Redirect `codecombat.com/demo` -> `codecombat.com/teachers/demo`
=> Add teacher demo redirect

app/core/Tracker.coffee
Fixed by correctly handling the `segmentLoaded` variable.
=> SegmentLoaded true when not loaded.

app/views/play/level/PlayLevelView.coffee
Fix for https://app.asana.com/0/133181809586930/819221842173581
=> Fixing multiple showVictory event triggers on click of DONE button.

app/core/utils.coffee, app/views/LicensorViewComponent.vue, test/app/core/utils.spec.coffee
- Allow admins to toggle feature flags of all api clients (#4889)
- Update GDPR countries
- Update ageOfConsent test now that Bulgaria changed its age of consent
=> Merge to production

app/templates/courses/teacher-classes-view.jade, app/views/courses/TeacherClassesView.coffee
This reverts commit 539f6999a5c87af6b3c8cd50eb5e1c8511cf339d.
=> Revert "Disable /teachers/classes progress dots"

app/views/core/ParentReferTeacherModal.coffee
Wasn't able to verify that event triggered locally. Email functionality not impacted.
=> Add "Refer Teacher by Parent" event to analytics

server_setup.coffee
* Fixes issue where proxy wasn't serving local files due to new client+server sha.
=> Update proxy config to support client+server sha

app/templates/play/level/control-bar-view.jade, app/templates/play/level/modal/game-dev-victory-modal.jade, app/templates/play/level/play-game-dev-level-view.jade, app/views/play/level/ControlBarView.coffee, app/views/play/level/GameDevTrackView.coffee, app/views/play/level/PlayGameDevLevelView.coffee, app/views/play/level/PlayLevelView.coffee, app/views/play/level/modal/GameDevVictoryModal.coffee
Status:
[x] "scoreLabel"
- Messy interaction with the current `ui.track` api behaviors.
[x] "directions"
[x] "victoryMessage"
[x] "levelName"
~"defeatMessage"~
=> HoC game dev front end code.

app/views/courses/TeacherClassesView.coffee
Depends on [this server side pull request](https://github.com/codecombat/codecombat-server/pull/27).
=> Add projection to member session call

app/templates/editor/thang/thang-type-edit-view.jade, app/views/editor/thang/ThangTypeEditView.coffee, package.json
Adds a new button to the editor allowing Animate files to be converted into a format understood by our parser.
This button should be a stand in for maka's specific art converting laptop.
=> Animate to Flash file converter btn added to editor

.gitignore, app/templates/play/level/tome/spell_palette_entry_popover.jade, app/views/play/level/tome/DocFormatter.coffee
Asana https://app.asana.com/0/790657906355597/833697510220009
Plus handler parameters issue (not in Asana)
=> Spell palette this + parameters

app/core/api/level-sessions.coffee, app/views/play/level/modal/CourseVictoryModal.coffee
In the server there is code that handles a `courseInstanceId`. Thus it wasn't handling the `courseInstanceID`.
=> Typo was preventing students from being added to the arena ladder.

app/locale/fr.coffee
=> update fr.coffee v0.3

app/locale/nl-NL.coffee, app/locale/nl.coffee, test/app/core/locale.spec.coffee
Fixes the `locale.spec.coffee` failing tests.
=> Fix Dutch translation

package.json
Fixes build issues after Mac os update.
=> Bump node-sass version to build on latest OS version.

app/templates/play/level/tome/cast-button-view.jade
https://app.asana.com/0/226022138373590/868572602387286
=> Changed the GD button text for playing

app/views/play/level/DuelStatsView.coffee
Required for the last Danny's arena (Singapore tournament) plus for other arenas UI customisation.
=> Allow to set teamPower from referee for Power UI in Arenas

app/views/play/level/tome/SpellView.coffee
* Scroll and set the cursor for each "restart code"
Issues
https://app.asana.com/0/search/883683040776229/833697510220014
and
https://app.asana.com/0/search/883683040776229/670922725898667
=> Scrolling on the first entry point (yellow arrow) when level starts

app/locale/es-ES.coffee
updated play section translations
=> Update es-ES with English to Spanish translations

app/core/Router.coffee, package.json
PlayGameDevLevelView was not receiving the query parameters for course and courseInstance. Due to this the edit button was not working as expected.
Update the backbone version to handle to URL's with query parameter.
=> Send query parameters to PlayGameDevLevelView and PlayWebDevLevelView

app/views/LicensorViewComponent.vue
This component didn't have any tests. I ended up testing manually.
This pull request includes usability improvements.
While processing the emails the user can see progress and the submit button is disabled.
Any emails that cause an error are listed beneath the button after everything has been processed.
This will allow netease to diagnose individual emails.
=> Add batch add Teacher licenses via a comma separated list

app/views/special_event/HoC2018Component.vue
- Updated HoC video.
- Moved `Create Teacher Account` button to fix layout on mobile.
=> Update video and slight UI tweak

app/lib/LevelBus.coffee, app/views/ladder/MyMatchesTabView.coffee, app/views/play/level/tome/CastButtonView.coffee
3 simple edits to make the level a mirror match.
I see this in the code, am I able to set this in my level so I don't have to come here?
@options.level.get('mirrorMatch')
=> Adding King of the Hill as a mirror match

app/lib/Angel.coffee
Remove unnecessary `publishGodEvent` from update loop.
=> Remove world-load-progress-changed from realTime

app/lib/coursesHelper.coffee, app/models/Classroom.coffee, app/templates/courses/courses-view.jade, app/templates/user/certificates-anon-view.pug, app/templates/user/certificates-view.jade, app/views/user/AnonCertificatesView.coffee
Using same utility method for course completed status as teacher dashboard, course complete now means all required course levels are complete instead of last course level complete.
=> :bug:Fix student course complete logic

app/templates/play/menu/options-view.jade, app/views/play/level/tome/SpellView.coffee, app/views/play/menu/OptionsView.coffee
Also removing show indent guides and show invisibles options from game menu.
=> :bug:Apply game menu smart behaviors immediately

app/views/editor/level/thangs/AddThangsView.coffee
Has taken the idea from the i18n home page
=> More than 1000 thangs fetched

app/lib/world/component.coffee, app/lib/world/thang.coffee, app/schemas/models/level_component.coffee, app/views/editor/level/components/LevelComponentEditView.coffee
- the context can be used inside 'Code' in components.
=> Added translatable context for components.

app/models/Classroom.coffee
Teacher dashboard already includes arena levels when determining course completeness.
=> :bug:Include arena levels in course completeness for students

app/styles/user/certificates-view.sass, app/templates/user/certificates-view.jade
Removed in-progress checks and styling in Front End.
=> Assume if viewing certificate that campaign is completed

app/locale/ja.coffee
change translation for "hero" from "へーロー" to "ヒーロー"
change translation for "language" from "プラグラミング" to "プラグラミング言語"
=> fix mistranslated words

app/templates/static/layout.static.pug, app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee
Add global Google AdWords library gtag.js to the global site.
Created a conversion tag function and added to unique teacher signups.
=> Google Ad Pixel Install for Unique Teacher Conversions

app/views/admin/OutcomesReportComponent.vue
Next should refresh with latest teacher email
=> :bug:Fix outcomes report next button

app/models/User.coffee, compile-static-templates.coffee, static-mock.coffee
Changes:
- Webpack will now handle static template files error in compilation
- Add mock methods to user to generate static home page
=> Fix static home page and add Webpack error to static compilation

app/core/api/classrooms.coffee, app/core/api/users.coffee, app/core/social-handlers/GPlusHandler.coffee, app/core/social-handlers/GoogleClassroomHandler.js, app/locale/en.coffee, app/models/Classroom.coffee, app/models/User.coffee, app/schemas/models/classroom.schema.coffee, app/schemas/models/user.coffee, app/styles/courses/teacher-class-view.sass, app/templates/courses/classroom-settings-modal.jade, app/templates/courses/teacher-class-view.jade, app/views/courses/ClassroomSettingsModal.coffee, app/views/courses/TeacherClassView.coffee, app/views/courses/TeacherClassesView.coffee, test/app/core/social-handlers/GoogleClassroomHandler.spec.js, test/app/views/teachers/TeacherClassView.spec.coffee
- 'Link Google Classroom' button on create new class modal
- It will let teachers select one of the google classrooms to import, and will then import the classroom with its students to codecombat
- 'Sync Google Classroom' button on TeacherClassView
- It will import students from google classroom to codecombat.
=> Changes for google classroom integration

app/app.js, app/app.sass, app/assets/web-dev-iframe.html, app/models/User.coffee, app/styles/bootstrap/_bootswatch.scss, app/styles/common/fontChina.sass, app/styles/common/fontUS.sass, app/templates/static/layout.static.pug, compile-static-templates.coffee, static-mock.coffee
This change loads the fonts dynamically and conditionally via `chinaUx` feature flag that is globally set in the database.
This change splits out the fonts into two separate files that can be imported as required.
If the font load time is slow the page is initially rendered with default fonts. Once fonts load the page fonts update.
Analytics are also not loaded if built with `chinaInfra=true`.
I am unable to reproduce the network requests being correct for the iframe used within the Web Dev levels. Will want to check with a team member in China that it is loading correctly.
=> China localization of fonts and analytics

app/core/Tracker.coffee, app/views/core/CreateAccountModal/BasicInfoView.coffee
Tracking occurrence of an error via google analytics for this intermittent bug: https://app.asana.com/0/654820789891907/1113232508815667
=> Track error in single-sign-on-confirm-view submit for teacher

.circleci/config.yml
Run copy-i18n-tags on every commit to master, create a PR if changes present
=> Run copy-i18n-tags against master

app/lib/surface/Label.coffee, app/lib/surface/Lank.coffee
For the 1UP Capstone Project content team needs more control on customizing of game labels (speech bubbles) and more info about them to manage them from the component code.
I've added options transferring from the game components to the Label class and returning data of speech bubbles, that allows to use custom parameters and track clicks on bubbles from component code.
=> Custom dialogue bubble

app/models/User.coffee, app/templates/home-view.jade, app/views/HomeView.coffee, static-mock.coffee
We can't play the current video on our china domain.
Self host the video just for the china version of the homepage.
=> Add video for Alibaba environment

app/assets/javascripts/web-dev-listener.js
Web dev is blocked on our china domain.
Add the domain to allowed origins.
=> Add koudashijie to allowed web-dev origins

app/assets/web-dev-iframe.html, app/styles/common/fontChina.sass
replace fonts.font.im with fonts.loli.net
I have already tested, the latter one can be much more faster, please have a review and deploy soon
=> update fonts mirror

app/views/ladder/LadderView.coffee
modify ladder view initialization for tarena hackthon classroom
=> Ladder tarena

test/app/lib/cinematic/AbstractCommand.spec.js, test/app/models/Cinematic.spec.js
DO NOT MERGE until #5206 merges
=> Foundation Cinematic Client Tests

app/views/editor/level/thangs/ThangsTabView.coffee
The server limit for ThangType collection is 1000 and we have 1000+ thangs there. So some of thangs out of the first 1000 can't be added on the game map.
Added the chunk loading of ThangType collection. I used listenOnce instead 'listen' because the collection is syncing on adding each thang on the map and we don't need to trigger the callback again there.
=> Added chunk loading for ThangType collection in the level editor

app/views/teachers/TeacherStudentView.coffee
Code Ninjas CEO was bugging me about user reports from Code Ninjas centers about this page. While investigating it to create an Asana bug, I got carried away and ended up fixing it.
In the example class with 94 students, https://codecombat.com/teachers/classes/5aba59aebfdf340023d5dc63/5c520b1c5cdcb0002e798e11, it took 37s to load, including a long UI hang. Changing the `calculateStandardDeviation` loop from:
```
for course in courses
for member in classroom
for level in courseLevels
for session in allSessions
if session == level and session == member
for levelData in allLevelData
if levelData == session
++playtime
++memberPlayed
```
to precalculating a couple maps:
```
make map of allSessions[member][level]
make map of allLevelData[level]
for course in courses
for member in classroom
for …
```
=> Improve performance of standard deviation calculation on TeacherStudentView

app/views/school-administrator/teachers/SchoolAdminTeacherListView.vue
Currently we don't have this stat.
Remove description acknowledging it.
=> Hide project stat description

app/locale/en.coffee, app/styles/user/certificates-view.sass, app/templates/user/certificates-view.jade, app/views/user/CertificatesView.coffee
Use user._id and course-instance-id to generate a hash integer as certificate number
=> cn add serial number on certificate

app/locale/en.coffee, app/templates/teachers/resource-hub-view.jade
The web development 1 curriculum guide is ready to go.
Updated wording slightly and enabled the link that was always there.
=> Enable the WD1 curriculum and update wording

app/schemas/models/cinematic.schema.js, app/schemas/selectors/cinematic.js, app/views/play/cinematic/CameraSystem.js, app/views/play/cinematic/CinematicLankBoss.js, app/views/play/cinematic/Loader.js, app/views/play/cinematic/cinematicController.js, test/app/models/Cinematic.spec.js
Adds a command-able camera to the cinematic system!
- Adds camera to schema
- Appropriate selector and tests
- CameraSystem that creates the move command.
=> Cinematic Camera

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/views/play/level/LevelGoals.vue
Concept goals title: Use at least one concept
Add to i18n
=> Concept goal i18n

app/views/courses/StudentLevelProgressDot.vue, app/views/courses/TeacherClassAssessmentsTable.vue
The progress dot component used did not differentiate between teacher and school admin.
Pass props through to the progress dot so it can use the correct path for the link.
=> Fix school admin back link for assessment dots

app/components/Root.vue, app/components/common/MetaManager.vue, app/locale/en.coffee, app/views/AboutView.coffee, app/views/HomeView.coffee, app/views/account/AccountSettingsRootView.coffee, app/views/account/InvoicesView.coffee, app/views/account/MainAccountView.coffee, app/views/account/PaymentsView.coffee, app/views/account/PrepaidView.coffee, app/views/account/SubscriptionView.coffee, app/views/account/UnsubscribeView.coffee, app/views/clans/ClanDetailsView.coffee, app/views/clans/ClansView.coffee, app/views/courses/CoursesView.coffee, app/views/editor/level/LevelEditView.coffee, app/views/ladder/LadderView.coffee, app/views/ladder/MainLadderView.coffee, app/views/play/CampaignView.coffee, app/views/play/level/PlayGameDevLevelView.coffee, app/views/play/level/PlayLevelVideoComponent.vue, app/views/play/level/PlayLevelVideoView.coffee, app/views/play/level/PlayLevelView.coffee, app/views/play/level/PlayWebDevLevelView.coffee, app/views/special_event/HoC2018Component.vue, app/views/special_event/HoC2018View.coffee, app/views/teachers/DynamicAPCSPView.coffee, app/views/user/MainUserView.coffee, test/app/views/play/level/PlayLevelVideoView.spec.js
Add specific titles and meta descriptions to views for SEO
=> SEO add titles and meta descriptions

app/models/User.coffee, app/templates/static/layout.static.pug
add features?.china for useGoogleAnalytics flag
disable loading analytics.js when load static files
=> fix static page loading google analytics in china

app/models/User.coffee, app/styles/modal/create-account-modal/choose-account-type-view.sass, app/templates/core/create-account-modal/choose-account-type-view.jade, app/views/core/CreateAccountModal/CreateAccountModal.coffee
remove entry for individual register in china mode 
adjust some layout for create-account-modal to fit with & without individual register entry
=> remove entry for individual register in china

.eslintignore, app/views/school-administrator/teachers/SchoolAdminTeacherListRow.vue, app/views/school-administrator/teachers/SchoolAdminTeacherListView.vue
- Add project created stat
- Lints SchoolAdminTeacherListRow.vue and SchoolAdminTeacherListView.vue
=> Add project created stat to school admin dashboard and lint

app/styles/user/certificates-view.sass, app/templates/user/certificates-view.jade, app/views/user/CertificatesView.coffee
add a toggle button when preferred language is not en
when click toggle button, it will convert translation between en and preferredLanguage
=> toggle language for certificate view when prefer language is not en

app/core/Router.coffee, app/lib/dynamicRequire.js, app/views/TestView.coffee, ozaria/site/api/interactive.js, ozaria/site/components/interactive/PageInteractive/draggableOrdering.vue, ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion.vue, ozaria/site/components/interactive/PageInteractive/index.vue, ozaria/site/components/interactive/PageInteractive/insertCode.vue, test/ozaria/site/components/interactive/PageInteractive.spec.js
- Added new route for interactives
- Created a parent vue component for interactives which renders the specific component based on the type of interactive.
=> Interactives frontend page

app/lib/dynamicRequire.js
Temporarily fixes dynamic routes for #5333
=> Fix the routesFix the dyamic Require for Fabrico

app/templates/base-flat.jade
update icp backup url to beian.miit.gov.cn
=> update china icp info

app/schemas/models/level.coffee, app/schemas/models/level_session.coffee, app/schemas/subscriptions/play.coffee, app/views/editor/level/settings/SettingsTabView.coffee
This PR only contains the schema changes that https://github.com/codecombat/codecombat/pull/5336 is based on. 
We are shipping these individually so https://github.com/codecombat/codecombat/pull/5336 can be tested on Next without any conflicts for the schema changes.
Do these descriptions all make sense? Thinking specifically about the term "stage" and "goals", and the way they are used together throughout.
=> Capstone levels: schema changes

ozaria/engine/cinematic/dialogsystem/DialogSystem.js
Tiny change to update dialog bubble dimensions.
=> Update cinematic dialogue bubble width to 300px

app/templates/core/create-account-modal/segment-check-view.jade
continue work of https://github.com/codecombat/codecombat/pull/5328
=> fix removing home register entry on cn

app/models/User.coffee
on koudashijie.com, although we disabled registration for home version, we should still leave an anonymous entry for a free trial. In this case, we should also make some level limitation.
=> add feature.china judge to function me.isOnPremiumServer

package-lock.json, package.json
Upgrade to first release version of `adobe-animate-parser`.  Also adds a package-lock.json file so that we can have consistent dependency trees.
I'll send out some information on package-lock files as well.
=> Upgrade adobe-animate-parser and add package-lock.json

app/schemas/models/interactives/common/interactive_types.schema.js, app/schemas/models/interactives/interactive.schema.js, app/views/admin/FilesComponent.vue, ozaria/site/api/interactive.js, ozaria/site/common/ozariaUtils.js, ozaria/site/components/interactive/PageInteractiveEditor/index.vue, test/app/models/Interactive.spec.js
- Added `lineToReplace` for insert-code
- Added `textStyleCode` for draggable ordering and statement completion
- Added `defaultArtAsset` property for overall interactives
- Added support to upload image file for art assets
- Added support to not allow saving without interactive programming language
- Increased noty timeouts in editor page
=> Interactive editor fixes

app/lib/aether/interpreter.coffee, app/lib/aether_utils.coffee, webpack.base.config.js
- Include the copy of aether shipped in lib instead of the built one in bower
- Patch ranges during flow
=> Fix up Aether

app/models/User.coffee, app/templates/about.jade, app/templates/base-flat.jade, static-mock.coffee
1. fix homepage footer FAQ url;
2. Show China team contact info
=> update some China resource 

app/core/Router.coffee, app/core/vueRouter.js, app/schemas/models/cutscene.schema.js, ozaria/site/api/cinematic.js, ozaria/site/api/cutscene.js, ozaria/site/components/cinematic/PageCinematicEditor/index.vue, ozaria/site/components/common/BaseListItem.vue, ozaria/site/components/cutscene/PageCutscene/index.vue, ozaria/site/components/cutscene/PageCutsceneEditor/index.vue, ozaria/site/components/cutscene/PageCutsceneEditorList/index.vue, ozaria/site/models/Cutscene.js
- Cutscene Editor
- Refactor Cinematic api endpoints
- Update the list view of the cinematic editor
- Use id's or slugs to get cutscenes or cinematics
=> Cutscene Editor and Schema

app/lib/surface/LayerAdapter.coffee, app/lib/surface/SegmentedSprite.coffee, app/schemas/models/thang_type.coffee, app/views/editor/thang/AnimateImportWorker.js, app/views/editor/thang/ThangTypeEditView.coffee, package-lock.json, package.json
- Adds support for shape bounds to thang type schema
- Upgrades `adobe-animation-parser` versions to support shape bound calculations (these will then be used in caching)
- Add support for async importing so browser doesn't hang during import process
=> Art pipeline: support for shape bounds and async import

app/locale/zh-HANS.coffee, app/templates/courses/courses-view.jade
Updated, although we may not use this tomorrow
=> update tournament translations

ozaria/site/components/cinematic/common/CinematicCanvas.vue
Adds a placeholder, dev art, "Click to Continue" visual element to the cinematic.
=> Click to Continue UI Cinematic element

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/styles/play/ladder/ladder.sass, app/templates/play/ladder/ladder.jade, app/views/ladder/LadderView.coffee
There's no need for parents and players to know rank info after the tournament, and maybe cause some trouble. So we decided to close the leaderboard list of magic-rush, except for admin
=> close china magic rush ladder rank page

app/views/editor/thang/AnimateImportWorker.js, app/views/editor/thang/ThangTypeEditView.coffee, package-lock.json
Updates `adobe-animate-parser` dependency to segmented sprite version
=> Update to new art import version

package-lock.json
=> Update to latest version of animate parser

app/models/User.coffee, app/views/core/RootView.coffee, static-mock.coffee
Remove Diplomat volunteer translator modal when switching to Chinese on China server
=> no need of diplomat suggestion modal for china B2B service

app/schemas/models/user.coffee, ozaria/engine/cinematic/cinematicController.js, ozaria/engine/cinematic/dialogsystem/DialogSystem.js
First commit:
- Ozaria hero name added to the schema.
Second commit:
- Use this name in the cinematic if set.
=> Add Ozaria hero name

app/lib/sprites/SpriteBuilder.coffee, app/styles/editor/thang/colors_tab.sass, app/templates/editor/thang/colors_tab.jade, app/views/editor/thang/ThangTypeColorsTabView.coffee, app/views/editor/thang/hslCalculator.vue
Color customization will work differently for Ozaria than in CodeCombat. This PR provides more tooling for importing our tints and selecting colors.
- Color Tab in the thang editor now includes a tiny stateless **hex to hsl** calculator.
- This is included to ensure it is quick to calculate the hsl for tints from a given hex.
- Selecting a color in the grid of colors is extremely tedious. Now there is an input that lets you select the colors with a given hex. Just type in the hex and click select.
- Ozaria type now changes how color is applied to the thang. The color is directly applied to give us fine grained control over color customization. In legacy types the color is shifted but it is not precise enough for what we are doing now.
**Example of ozaria absolute color applied**
**Example …
=> Absolute color swapping for Ozaria and Thang Editor extensions

.babelrc, app/core/Router.coffee, app/core/store/index.coffee, app/core/store/modules/tints.js, app/lib/dynamicRequire.js, app/models/User.coffee, app/schemas/models/user.coffee, ozaria/engine/cinematic/CinematicLankBoss.js, ozaria/engine/cinematic/Loader.js, ozaria/engine/cinematic/constants.js, ozaria/site/components/char_customization/PageCharCustomization/index.vue, ozaria/site/components/char_customization/common/Surface.vue, package-lock.json, package.json, test/ozaria/site/components/char_customization/PageCharCustomization.spec.js
Initial functional page of player character customization, with some minor cinematic changes so that the customization propagates into the cinematic.
- User can navigate to http://localhost:3000/ozaria/character-customization and see a character customization page.
- User can select a body, name and tints. These will be reflected in cinematics. (Not levels yet).
- If user has previously saved options, the form should be pre-populated, otherwise randomly selected.
1. Start a local proxied environment by running `npm run proxy` and `npm run dev` simultaneously.
1. Log in with your admin account
1. Navigate to http://localhost:3000/ozaria/character-customization
1. Character customize and press Next. (Your choices are saved!)
1. Navigate to http://localhost:3000/cinematic/1fhl1c1 and the …
=> Initial Functional Character Customization Screen

app/core/store/modules/interactives.js, ozaria/site/api/interactive.js, ozaria/site/components/interactive/PageInteractive/common/BaseButton.vue, ozaria/site/components/interactive/PageInteractive/common/ModalInteractive.vue, ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue, ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion/index.vue, ozaria/site/components/interactive/PageInteractive/index.vue, ozaria/site/components/interactive/PageInteractive/insertCode/index.vue, stories/Interactive.stories.js
Current status:
- insert sessions for insertCode.
- insertCode has modal. Fetches correct session. And propagates complete event.
=> Interactive backend write

app/views/play/CampaignView.coffee
open game-dev-2-final-project level manually for the Tarena hackthon national final, just in case of some players didn't finish all other levels before.
=> open game-dev-2-final-project for Tarena national final classroom

app/models/User.coffee, app/views/courses/TeacherClassesView.coffee, app/views/courses/TeacherCoursesView.coffee, app/views/teachers/TeacherCourseSolutionView.coffee
In China, unpaid teacher have no access to CS2 and later levels, so does API teacher.
We should let API teacher have access to all courses
=> modify paidTeacher with judge isCreatedByClient

app/styles/common/fontUS.sass, ozaria/site/components/interactive/PageInteractive/common/BaseDraggableSlot.vue, ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue, ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion/index.vue
- Final styling tweaks to draggable statement completion 
TODO
=> Interactives UX: Finalize draggable statement completion

app/core/application.coffee
This reverts the change to detecting the local environment.
=> Revert local windows development change

ozaria/site/common/utils.js, ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue, ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion/index.vue, ozaria/site/components/interactive/PageInteractive/insertCode/index.vue, package-lock.json, package.json
Deterministically randomize question inputs for a user and day
=> Interactive UX: randomize questions

app/styles/common/fontChina.sass, app/styles/common/fontUS.sass, ozaria/site/components/common/LayoutAspectRatioContainer.vue, ozaria/site/components/common/LayoutChrome.vue, ozaria/site/components/interactive/PageInteractive/common/BaseInteractiveLayout.vue, ozaria/site/components/interactive/PageInteractive/common/InteractiveTitle.vue
- Adds a 16:9 fixed aspect ratio to interactives, centering the interactive within the screen
- Maintains max width / height of interactive based on specs to ensure that art assets are rendered properly
- Adds chrome border
- Adds background color to scaled interactives
TODO
=> Interactives UX: Layout / Fixed aspect ratio

app/locale/en.coffee, ozaria/site/components/common/BaseModal.vue, ozaria/site/components/common/BaseSpeechBubble.vue, ozaria/site/components/interactive/PageInteractive/common/ModalInteractive.vue, ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue, ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion/index.vue, ozaria/site/components/interactive/PageInteractive/insertCode/index.vue
- Adds simple base modal 
- Changes InteractiveModal to use BaseModal under the hood
- Add modal i18n
- Add final modal styling
=> Interactives UX: Modals

ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue, ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion/index.vue, ozaria/site/components/interactive/PageInteractive/insertCode/index.vue
Pre fills answers on all three interactives when student has successfully completed the interactive
=> Interactives UX: Pre fill answers when user has successfully completed

ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue
Finalize UX of draggable ordering
=> Interactives UX: Finalize draggable ordering

app/templates/base-flat.jade, server_config.coffee
Change redirection from cn.codecombat.com to koudashijie.com
=> Update china redirection

app/assets/dexecure-c167a5675c.js
add coco-dex.koudashijie.com and dexecure-test.koudashijie.com to dexecure.js file
see slack link https://codecombat-core.slack.com/archives/CEK2G6FQB/p1564644125007200
=> setup dexecure testing domain for china server

app/views/play/CampaignView.coffee
server-side change refer to
https://github.com/codecombat/codecombat-server/pull/115
=> update free access level CS1, level 1~10

app/schemas/models/achievement.coffee, app/schemas/models/article.coffee, app/schemas/models/course.schema.coffee, app/schemas/models/level.coffee, app/schemas/models/level_component.coffee, app/schemas/models/level_system.coffee, app/schemas/models/poll.schema.coffee, app/schemas/models/thang_type.coffee, app/schemas/schemas.coffee
EDIT:
Ran both client and server tests locally.
=> Add algolia schema property

app/locale/ru.coffee
A few lines translated into Russian
=> A few lines translated into Russian

app/styles/contact-cn.sass, app/templates/base-flat.jade, app/templates/contact-cn-view.jade
add useful link 
CCID  ccidtraining.org.cn
AIYouth  aiyouth.ccidtraining.org.cn
add china team photo on contact-cn view
=> update china home page & contact cn

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/templates/base-flat.jade, app/templates/contact-cn-view.jade, app/views/core/AuthModal.coffee
=> Chenzhiran patch 3

app/templates/static/home.static.pug
Add schema to help CodeCombat get found on google under "Coding Games". Schema only added to home page.
=> Add Coding Game seo for google search

app/app.sass, app/core/utils.coffee, app/locale/en.coffee, app/locale/zh-HANS.coffee, app/models/User.coffee, app/templates/account/account-settings-view.jade, app/templates/core/create-account-modal/basic-info-view.jade, app/templates/core/create-account-modal/school-info-panel.jade, app/templates/core/create-account-modal/teacher-role-panel.jade, app/views/core/CreateAccountModal/BasicInfoView.coffee, app/views/core/CreateAccountModal/teacher/NcesSearchInput.coffee, app/views/core/CreateAccountModal/teacher/SchoolInfoPanel.coffee, app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee, server_setup.coffee
Stop autocomplete for region
Change Chinese label to "school name or training center name"
Only need city and province; switch to province first, then city
Don't need district or country
Phone number required in China
Add WeChat as optional
Default country: China
=> teacher register modify for china

app/templates/static/layout.static.pug
use baidu analytics instead of google analytics in China
=> add baidu analytics

bower.json
Reverts codecombat/codecombat#5553
=> Revert "Upgraded ace editor to 1.4.x for better mobile support"

app/locale/zh-HANS.coffee
miss approved https://github.com/codecombat/codecombat/pull/5560 
forgot to open parent comment in last pr
=> fix update zh-HANS.coffee

app/locale/th.coffee
Translate Calendar Section. Day/Month/Year and Month Names
=> Translate Calendar Section

app/models/User.coffee, app/templates/account/account-settings-view.jade
mask delete account panel in account setting view in china
=> prevent delete account in China

server_config.coffee
which redirect to koudashijie.com/china-bridge, will show the guide to netease/koudashijie
=> update china domain to bridge.koudashijie.com

app/collections/Levels.coffee, app/core/utils.coffee, app/models/User.coffee, app/schemas/models/classroom.schema.coffee, app/schemas/models/course_instance.schema.coffee, app/templates/courses/classroom-settings-modal.jade, app/templates/courses/courses-view.jade, app/templates/courses/teacher-class-view.jade, app/templates/courses/teacher-courses-view.jade, app/views/courses/ClassroomSettingsModal.coffee, app/views/courses/TeacherClassView.coffee, app/views/courses/TeacherCoursesView.coffee, app/views/play/level/tome/Spell.coffee, app/views/teachers/TeacherCourseSolutionView.coffee, test/app/core/utils.spec.coffee
Reverts codecombat/codecombat#5729
in order to clean commit
=> Revert "Enable C++ for CodeCombat classroom version"

app/templates/about.jade
Add two new job postings.
Screenshot of change:
I verified manually using proxy server.
=> Add marketing manager and events coordinator

app/vendor.js, package-lock.json, package.json
We are using a method on Arrays that some users may not have yet. Especially if the user is on a not completely updated Edge browser.
=> Add flat polyfill

app/styles/modal/create-account-modal/school-info-panel.sass, app/templates/core/create-account-modal/school-info-panel.jade, app/templates/teachers/convert-to-teacher-account-view.jade, app/templates/teachers/create-teacher-account-view.jade, app/templates/teachers/request-quote-view.jade, app/views/core/CreateAccountModal/teacher/SchoolInfoPanel.coffee, app/views/teachers/ConvertToTeacherAccountView.coffee, app/views/teachers/CreateTeacherAccountView.coffee, app/views/teachers/RequestQuoteView.coffee, package-lock.json, package.json, test/app/views/teachers/ConvertToTeacherAccountView.spec.coffee, test/app/views/teachers/CreateTeacherAccountView.spec.coffee, test/app/views/teachers/RequestQuoteView.spec.coffee
Details in ozaria PR: https://github.com/codecombat/ozaria/pull/344
=> Restrict country state

app/schemas/models/user_stats.schema.js
Duplicate of Ozaria PR: https://github.com/codecombat/ozaria/pull/349
=> Schema for user stats

app/views/courses/TeacherClassView.vue, app/views/school-administrator/dashboard/SchoolAdminDashboardTeacherView.vue, app/views/teachers/classes/TeacherStudentView.vue, app/views/user/CertificatesView.coffee
Fix places where lastName shows `undefined`
=> use broad name for certificate view, school admin dashboard, etc.

app/locale/zh-HANS.coffee, app/templates/base-flat.jade
Modify some website title and keywords
Add some china specific href such as aojiarui.com, blog.koudashijie.com
=> Add some href in koudashijie.com

app/templates/base-flat.jade
=> add blog link on nav bar

app/models/User.coffee, app/views/play/level/HintsState.coffee
=> Turn off general article in China

app/core/Tracker2/DriftTracker.js, app/core/application.coffee, package-lock.json, package.json
Reverts codecombat/codecombat#5815
Due to issue found on staging.
=> Revert "Disable drift targeting for students and on /play/ pages"

app/core/Tracker2/DriftTracker.js, app/core/application.coffee, package-lock.json, package.json
Commit was reverted due to an issue on staging.  This brings it back after fixing the root cause.
This reverts commit 76646db50ffb10ce141f0da6d4c665893988418f.
Testing on next.
=> Disable drift targeting for students and on /play/ pages #2

app/templates/core/create-account-modal/teacher-role-panel.jade, app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee, app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coffee
Details here: https://github.com/codecombat/ozaria/pull/381
=> Add phoneNumber in signup form

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/locale/zh-HANT.coffee, app/templates/core/create-account-modal/school-info-panel.jade, app/views/core/CreateAccountModal/teacher/SchoolInfoPanel.coffee
update country list with:
Hong Kong, China
Macao, China
Taiwan, China
Country -> Country / Region
=> update country list display

app/core/social-handlers/GoogleClassroomHandler.js, app/models/User.coffee, app/views/core/AuthModal.coffee, app/views/teachers/CreateTeacherAccountView.coffee, test/app/core/social-handlers/GoogleClassroomHandler.spec.js, test/app/views/teachers/CreateTeacherAccountView.spec.coffee
Details in Ozaria PR: https://github.com/codecombat/ozaria/pull/387
=> Google classroom fixes

app/locale/en.coffee, app/models/User.coffee, app/schemas/models/course_instance.schema.coffee, app/templates/courses/teacher-class-view.jade, app/views/courses/TeacherClassView.coffee, app/views/play/CampaignView.coffee
Expanding on China-only locking from https://github.com/codecombat/codecombat/commit/80c09e6e2fb6090171f199ea56adf1381cd33922
Tested in local dev env.
=> Global classroom level locking

app/locale/en.coffee, app/views/core/AuthModal.coffee
Similar to ozaria PR: https://github.com/codecombat/ozaria/pull/407
=> Google account merging changes for notification

app/core/Tracker2/ProofTracker.js, app/core/Tracker2/index.js
- Integrates proof tracker
- Only loads on `next.codecombat.com` right now, this will change after we evaluate proof, we'll either remove or release everywhere.
This is live on next.codecombat.com
=> Integrate Proof Tracker

app/templates/base-flat.jade, app/templates/base.jade, app/templates/core/components/page-errors.jade, app/templates/core/loading-error.jade, app/templates/editor/level/level-edit-view.jade, app/templates/editor/thang/thang-type-edit-view.jade, app/templates/i18n/i18n-edit-model-view.jade, app/templates/play/campaign-view.jade, app/templates/play/play-level-view.jade
Asana: https://app.asana.com/0/654820789891907/1175888975367490
=> Hide links to open contact form

app/core/store/modules/me.js, app/locale/en.coffee, app/views/PageParents.vue
- Adds `isPremium` and `isInGodMode` getters to Vuex `me` store based on User model
- Prevents user from subscribing to premium when `isTeacher`, `isStudent`, `isAdmin`, `isPremium`
- Style tweaks
=> Parent page v2 fixes / improvements

app/locale/en.coffee, app/templates/about.jade
Fixes https://github.com/codecombat/codecombat/compare/0b1ce82e9fb2...1a22b3e86ae0
=> Fix i18n translation change

app/lib/aether/problems.coffee
modity the transpile error position in c++.
=> Cpp error message position

app/locale/en.coffee, app/views/core/AuthModal.coffee
See https://github.com/codecombat/ozaria/pull/488 for context
=> feat(auth): add support for rate limit message in AuthModal.coffee

app/views/account/SubscriptionView.coffee
If the server has an error with the message from the contact form, it times out. 
Timing out means the callback doesn't trigger, and so the unsubscribe action never fires. 
The unsubscribe event now runs regardless of whether the contact form succeeds or not.
=> Fix broken unsubscribe event when form has a message

app/components/common/MetaManager.vue, app/templates/base-flat.jade, app/templates/static/layout.static.pug, app/views/HomeView.coffee, app/views/PageParents.vue
- Unifies the meta viewport tag across all pages so that we can switch between different viewport settings per page (allows better mobile experience on newer pages).
- Fixes bullet rendering on mobile on parents page
- Removes an unnecessary container-fluid from footer
- Fixes small horizontal scroll issue on mobile on parents page
=> Mobile responsiveness fixes for parents page

app/core/Router.coffee, app/core/vueRouter.js, app/locale/en.coffee, app/views/landing-pages/parents/PageParents.vue, app/views/landing-pages/parents/PageParentsJumbotron.vue, app/views/landing-pages/parents/PageParentsSectionPremium.vue
- Adds '/live-classes' landing page that is backed by current parents page
- Moves some of the sections of the parents page into their own components
- Small changes to parents page to adjust what is shown based on route (live classes page vs parents page)
- Moves parents page into it's own directory alongside sub modules
=> Live classes landing pages

app/core/Tracker2/FacebookPixelTracker.js, app/core/Tracker2/index.js, app/locale/en.coffee, app/views/landing-pages/parents/PageParents.vue
- Adds facebook pixel tracker
- Sends facebook pixel when live classes campaign converts
=> Facebook pixel tracker

app/views/landing-pages/parents/PageParents.vue
- Add tracking events on CTA click
- Update to new Drift interaction ID
=> Live classes landing page changes

app/views/courses/EnrollmentsView.coffee
once admin teacher has no administratedTeachers, the licenses page cannot initialized because of 'length of undefined' error
=> admin teacher cannot access licenses page

app/lib/simulator/Simulator.coffee
handle sessions with `no levelID key` or `team: 'no team'`
=> Fix ladder simulation exception

app/components/common/BaseModal.vue, app/locale/en.coffee, app/views/landing-pages/parents/ModalTimetapSchedule.vue, app/views/landing-pages/parents/PageParents.vue
- Minor tweaks to base modal styling
- Adds timetap to parents page in iframe instead of redirect
- Preloads iframe in background
=> feat: load timetap in iframe on parents page

app/locale/en.coffee, app/schemas/schemas.coffee, app/templates/core/create-account-modal/basic-info-view.jade, app/templates/teachers/edit-student-modal.jade, app/views/core/CreateAccountModal/BasicInfoView.coffee
Enforces NIST compliant password requirements
- Password length
- Repeated characters
=> NIST password enforcement

app/lib/aether/problems.coffee
a quick fix for name of 'options.error' undefined
=> fix options.error undefined error

app/models/User.coffee, app/templates/courses/classroom-settings-modal.jade, app/views/play/modal/PlayHeroesModal.coffee
Reverts codecombat/codecombat#5934
=> Revert "Enable C++"

app/templates/about.jade
Tested manually with local proxy.
=> Add Software Eng job to about page

app/core/forms.coffee
=> forms.coffee check radio input isChecked

app/locale/en.coffee
Small copy updates for Hour of Code activity.
=> Update HoC activity date to 2020

app/templates/about.jade
Adds "Lead Artist" and "Online Coding Instructor" job posting.
=> Updated Job Postings

app/templates/teachers/resource-hub-view.jade
A pdf isn't as useful for teachers who want to make a copy and change the content. Thus for english only provide a link to google docs with a document that can be copied.
Looks like so:
=> Add Progress journal and engineering cycle worksheet Google doc

app/core/Tracker2/DriftTracker.js, app/core/Tracker2/GoogleOptimizeTracker.js, app/core/Tracker2/index.js
need discuss i think
not sure if this pr is enough to disable such trackers
=> disable some trackers in china

server_setup.coffee
Updates the target for the local proxy so signing up/logging in works again :tada:
=> Fix local proxy target

app/views/core/AuthModal.coffee, ozaria/site/templates/core/auth-modal.jade
This fix lets failed logins see the error and not reload the page.
=> Fix login flicker

app/schemas/models/license_request.schema.coffee, app/templates/teachers/teachers-contact-modal.jade, app/views/teachers/TeachersContactModal.coffee
New license request model for routing of contact form.
=> License request (#634)

app/locale/en.coffee, app/templates/courses/teacher-classes-view.jade, app/templates/home-view.pug, app/views/courses/BannerWebinar.vue, app/views/courses/TeacherClassesView.coffee
We're running a free webinar! Set up links to get registrations.
Tested manually and very low risk changes. Highest risk is that `moment` date is not correctly EST time and banner hides itself too early.
=> Upcoming webinar headline and banner

app/views/landing-pages/parents/PageParents.vue, app/views/landing-pages/parents/PageParentsJumbotron.vue
Fix font specificity, don't use FAQ until it is live, clean up unused styles.
=> Parents page polish v4

app/views/landing-pages/parents/PageParents.vue
Fixed the font size on parents page.
Size changed for H2 from 30px to 40px.
=> Fixed font size for H2 on parents page

app/core/api/leaderboard.js, app/core/store/modules/seasonalLeague.js, app/models/Level.coffee, app/schemas/models/level.coffee, app/schemas/models/level_session.coffee, app/schemas/models/user.coffee, app/templates/play/ladder/ladder-tab-view.jade, app/views/core/CreateAccountModal/ConfirmationView.coffee, app/views/landing-pages/league/PageLeagueGlobal.vue, app/views/landing-pages/league/components/ClanCreationModal.vue, app/views/landing-pages/league/components/Leaderboard.vue
There are some Vue errors about a duplicate key on the clan-specific version of this, gotta look into that.
I don't think this was me?, but navigating between /league and /league/<id> is updating URL but not page? Have to reload to get the update.
To earn Code Points for testing, beat the level Kelvintaph Pillars for the first time.
=> CodePoints implementation, other /league tweaks

app/views/landing-pages/league/PageLeagueGlobal.vue
=> Update league button style

app/core/store/modules/me.js, app/locale/en.coffee, app/views/core/AuthModal.coffee, app/views/core/CreateAccountModal/CreateAccountModal.coffee, app/views/core/CreateAccountModal/teacher/SetupAccountPanel.coffee, app/views/landing-pages/league/components/LeagueSignupModal.vue
- Add more redirects
- Improve modal copy
- Improve structure of modal error message
=> Second round of League fixes and improvements

app/views/landing-pages/parents/PageParents.vue
Lines on both sides of FAQs and Student Outcomes Headers should be narrower.
=> Narrow section border in parent page

app/views/landing-pages/parents/PageParents.vue
Course Offerings subtext should be same style as Our Curriculum subtext.
=> Update course offerings subtext style

app/views/landing-pages/league/PageLeagueGlobal.vue
Padding between Subhead and CTA.
=> Decrease padding bottom for Subhead and CTA

app/views/landing-pages/league/PageLeagueGlobal.vue
Increase font for subheader1 and subheader2 in league page.
=> Increase font for subheader1 and subheader2

app/lib/LevelLoader.coffee
since classroom-ladder page's url don't contains `course-instanceid`, so we use `league` as session query url
=> fix wrong session language in classroom-ladder

app/templates/core/contact.jade
Originally a change by @Chaboi45 in https://github.com/codecombat/codecombat/pull/5523 but can't be merged there due to the source repo missing. Recreated the change here.
=> Update Contact page to a newer version of FAQ

app/views/landing-pages/league/PageLeagueGlobal.vue, app/views/landing-pages/league/components/ClanSelector.vue, app/views/landing-pages/league/components/Leaderboard.vue
If the server sends the clan displayName then it will be used in the ladder.
=> Add displayName preference for clans on league page

app/core/store/modules/seasonalLeague.js, app/templates/base-flat.jade, app/views/landing-pages/league/PageLeague.vue, app/views/landing-pages/league/PageLeagueGlobal.vue
This is currently on next.codecombat.com to add some additional robustness and potentially highlight errors.
CodePoints leaderboard bug naming not working fix:
=> Esports leaderboard bugs

app/templates/base-flat.jade
Fix red master by addressing static compilation.
=> Fix static navbar compile

app/views/landing-pages/parents/PageParents.vue
Removed extra space in small devices. and use H1 tag instead H2 to make uniform header.
=> Additional mobile optimization

app/views/landing-pages/league/PageLeague.vue, app/views/landing-pages/league/PageLeagueGlobal.vue, app/views/landing-pages/league/components/Leaderboard.vue, app/views/landing-pages/parents/PageParents.vue
Mobile optimization for overall League page.
Below image are better visible after download locally. 
Desktop Version:
Mobile Version:
=> League mobile optimization

app/locale/sv.coffee
Hi.
I want to play the game with my kid, so I thought I should chip in.
I'm a developer and thought that I could start to translate the game to Swedish. This fourth batch is mostly the new amazon competition language translations. This might not be something you require translating. If so, just close the PR.
I hope you find this to your liking. I will continue to translate more sections later.
Best regards
Daniel
=> Fourth batch of Swedish translations. (Amazon specific translations)

app/views/landing-pages/league/PageLeagueGlobal.vue
Adding image of whole page in mobile version. navbar is hidden only to take whole page 
snapshot.
=> Fixed spacing issue in leage page for small devices

app/templates/core/modal-base-flat.jade, app/templates/core/modal-base.jade
They are loading at some places which ideally shouldn't. Removing them for now.
=> remove manbites.com images

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/templates/account/account-settings-root-view.jade, app/templates/account/account-settings-view.jade, app/views/account/AccountSettingsRootView.coffee, app/views/account/AccountSettingsView.coffee
split one `save` button in the bottom into different panel
=> Modify account setting page

app/views/play/level/tome/SpellView.coffee
not sure how to tigger the @spellThang undefined error but sometimes i met it.
thinking adding a ? won't break anything
=> add a ? to avoid @spellThang undefined error

app/core/api/leaderboard.js, app/core/store/modules/seasonalLeague.js, app/views/landing-pages/league/PageLeagueGlobal.vue, app/views/landing-pages/league/components/Leaderboard.vue
=> show playerCount in code point leaderboard

app/schemas/models/district.schema.js, app/schemas/models/school.schema.js
Currently we store our school information in an old algolia index.
By taking ownership of our schools and districts we will be able to more easily integrate schools into esports.
This collection will often contain partial data - especially if a user has inputted their own school, so I've modeled it based on how we structure the data in algolia.
=> School and District schemas for new collection

app/schemas/models/level.coffee, app/views/editor/level/settings/SettingsTabView.coffee, app/views/play/level/PlayLevelView.coffee
add a `clans` to the level so that we can control the level access permission with clans
=> level clan permission

app/core/Router.coffee, app/lib/dynamicRequire.js, app/styles/artisans/arena-balancer-view.sass, app/templates/artisans/arena-balancer-view.pug, app/templates/artisans/artisans-view.jade, app/views/artisans/ArenaBalancerView.coffee, app/views/artisans/LevelConceptMap.coffee, app/views/artisans/SolutionProblemsView.coffee, app/views/artisans/StudentSolutionsView.coffee, app/views/editor/level/LevelEditView.coffee
Also fixed up a few /artisans tools while I was there.
Tested it all manually; it's all internal tooling, anyway.
=> Add an arena balancer tool

app/views/play/level/tome/SpellView.coffee
this pr is conflict with https://github.com/codecombat/codecombat/pull/6253, chose one to approve and merged into master
=> should fix the bug in game-dev wrong error message 

app/collections/Products.coffee, app/locale/en.coffee, app/schemas/models/user.coffee, app/styles/modal/subscribe-modal.sass, app/templates/core/subscribe-modal.jade, app/vendor.js, app/views/LegalView.coffee, app/views/core/SubscribeModal.coffee, app/views/landing-pages/parents/PageParents.vue, app/views/landing-pages/parents/PageParentsSectionPremium.vue, bower.json, test/app/views/core/SubscribeModal.spec.coffee
Allow displaying either annual or lifetime subscriptions (relying on the server to send the relevant products).
=> Front-end support for more flexible long-term subscription options

app/views/landing-pages/league/components/Leaderboard.vue
Fixes various issues with the name column for league and improves green display in non global league pages.
=> Fix league student names

app/lib/simulator/Simulator.coffee, app/schemas/models/tournament_match.schema.coffee, app/views/clans/ClanDetailsView.coffee, app/views/courses/CoursesView.coffee, app/views/ladder/LadderView.coffee
Ran some of this locally before. Still need to make a better front-end for configuring large tournaments.
Also includes a fix to loading clans by slug instead of id.
=> Starting to add front-end support for big tournaments

.github/worfklows/node.js.yml, package.json
=> GitHub Action for automatic CI tests

app/templates/courses/courses-not-assigned-modal.jade, app/views/courses/CoursesNotAssignedModal.coffee, app/views/courses/EnrollmentsView.coffee
Also fix a template interpolation issue in CoursesNotAssignedModal.
=> Don't show starter licenses in partner country or to admins.

app/schemas/models/earned_achievement.coffee, app/schemas/models/level_session.coffee, app/schemas/models/purchase.schema.coffee, app/schemas/models/user.coffee
Also fix an old copy/paste error on Purchase schema setup, likely cosmetic.
=> Add archived field to certain collections to support cloud archiving

app/views/payment/DayTimeInputComponent.vue, app/views/payment/PaymentOnlineClassesPurchaseView.vue, app/views/payment/PaymentOnlineClassesStudentDetailsComponent.vue
1.
-------------------
2.
We take user timezone and convert UTC times I have manually entered in the code to their timezones. In screenshot 1 u can see when nothing is selected, while the second one shows times available on that day. 
Since changing time based on timezone can take UTC sometime to the next or previous day, I have made changes to move times to the corresponding day.
=> changes to take preferred time for student class

app/core/api/clans.js, app/core/utils.coffee, app/locale/en.coffee, app/styles/courses/teacher-class-view.sass, app/styles/courses/teacher-classes-view.sass, app/templates/courses/clan-league-stats-mixin.jade, app/templates/courses/teacher-class-view.jade, app/templates/courses/teacher-classes-view.jade, app/views/courses/TeacherClassView.coffee, app/views/courses/TeacherClassesView.coffee
Working first version, but needs some more work (design, i18n, responsiveness, adding a similar section at the class level, and quickstart video).
=> Add AI League stats section to teacher dashboard

app/core/vueRouter.js, app/views/payment/PaymentOnlineClassesParentDetailsComponent.vue, app/views/payment/PaymentOnlineClassesPurchaseView.vue, app/views/payment/PaymentOnlineClassesSuccessView.vue
=> online classes success page

app/vendor.js, bower.json
Looks like the size reduced to 610kB from 690kB. Will confirm on staging. Tested on local and everything seems fine.
=> remove moment from bower

app/views/payment/PaymentComponentView.vue, app/views/payment/PaymentLicenseMinMaxTextComponent.vue, app/views/payment/PaymentSchoolDistrictBodyView.vue, app/views/payment/PaymentSmallClassroomBodyView.vue, app/views/payment/PaymentStudentLicenseClassroomDistrictBodyComponent.vue, app/views/payment/PaymentStudentLicenseClassroomDistrictView.vue, app/views/payment/PaymentStudentLicenseHeadComponent.vue, app/views/payment/PaymentStudentLicensePurchaseView.vue, app/views/payment/PaymentStudentLicenseView.vue, app/views/payment/PaymentStudentLicensesComponent.vue, app/views/payment/PaymentStudentLicensesView.vue, app/views/payment/paymentPriceHelper.js
=> payment UI changes for classroom and schools

app/collections/Levels.coffee, app/core/store/modules/game.coffee, app/core/utils.coffee, app/lib/aether/aether.coffee, app/lib/aether/interpreter.coffee, app/lib/aether/problems.coffee, app/lib/aether_utils.coffee, app/templates/courses/classroom-settings-modal.jade, app/templates/courses/teacher-class-view.jade, app/templates/editor/verifier/verifier-view.jade, app/templates/play/level/tome/spell_palette_entry_popover.jade, app/views/editor/level/tasks/TasksTabView.coffee, app/views/editor/verifier/VerifierView.coffee, app/views/ladder/LadderPlayModal.coffee, app/views/play/level/HintsView.coffee, app/views/play/level/LevelLoadingView.coffee, app/views/play/level/tome/DocFormatter.coffee, app/views/play/level/tome/Spell.coffee, app/views/play/level/tome/editor/autocomplete.coffee, app/views/play/modal/PlayHeroesModal.coffee, app/views/teachers/TeacherCourseSolutionView.coffee, test/app/core/utils.spec.coffee, test/app/lib/aether_utils.spec.coffee
If sample code, documentation, autocomplete snippets, etc. are not explicitly written for a level or API, then we will generate it through some hacky code generation from the base JavaScript, like we did for C++.
This won't always work, but it will work most of the time, reducing the burden to manually specify a lot of code.
Also fixed a bug causing Lua to yield too much, did some refactoring, and wrote a per-level per-language code generation test suite.
It's not fully ready yet, with a few more necessary bugs to fix, and lots more optional room for improvement.
Navigate to /test/app/lib/aether_utils.spec.coffee to test.
=> Add Lua/Java and automatic code generation for all languages

app/views/payment/PaymentSchoolDistrictBodyView.vue, app/views/payment/PaymentSmallClassroomBodyView.vue, app/views/payment/PaymentStudentLicenseHomeSchoolBodyComponent.vue, app/views/payment/PaymentStudentLicenseHomeSchoolView.vue, app/views/payment/PaymentStudentLicensePurchaseComponent.vue, app/views/payment/PaymentStudentLicensesComponent.vue, app/views/payment/PaymentStudentLicensesOnlineClassesComponent.vue
refactor small classroom to purchase component for re-use
=> add home school UI

app/core/treema-ext.coffee, app/schemas/models/user.coffee, app/styles/admin/administer-user-modal.sass, app/templates/admin/administer-user-modal.jade, app/views/admin/AdministerUserModal.coffee, app/views/admin/MainAdminView.coffee, app/views/modal/ModelModal.coffee
Improvements:
* Add editable Treemas to AdministerUserModal for User and TrialRequest
* Show the full TrialRequest property list
* Show only relevant sections for each user type, and tighten layout
* Show classrooms for students
* Add some classroom and other user quick links
* Add URLs for these user-specific modal links automatically
* Show subscription status for home users
=> Upgrade AdministerUserModal with some quality of life improvements

app/core/application.coffee, app/lib/surface/Lank.coffee, app/lib/surface/LayerAdapter.coffee, app/lib/surface/SegmentedSprite.coffee, app/lib/surface/SingularSprite.coffee, app/lib/surface/Surface.coffee, app/models/ThangType.coffee, app/views/clans/ClanDetailsView.coffee, app/views/clans/ClansView.coffee, app/views/core/CocoView.coffee, app/views/core/CreateAccountModal/CreateAccountModal.coffee, app/views/core/MineModal.coffee, app/views/core/ModalComponent.coffee, app/views/core/RootComponent.coffee, app/views/core/VueComponentView.js, app/views/play/CampaignView.coffee, app/views/play/level/LevelGoalsView.coffee, app/views/play/level/LevelLoadingView.coffee, app/views/play/level/PlayLevelView.coffee, app/views/play/level/tome/SpellView.coffee, app/views/play/level/tome/editor/autocomplete.coffee, app/views/user/MainUserView.coffee
We'll test this in Ozaria; if it works there, it'll likely work well here.
=> Port memory leak fixes first done in Ozaria

app/views/play/CampaignView.coffee
`->` override the `this`, so change to `=>`
=> fix wakka-maul missing from classrooms

app/components/common/Dropdown.vue, app/core/api/trial-requests.coffee, app/core/store/index.coffee, app/core/store/modules/trialRequest.js, app/lib/trialRequestUtils.js, app/views/core/CreateAccountModal/teacher/NcesSearchInput.coffee, app/views/core/TeacherDetailsModal.js, app/views/courses/TeacherClassesView.coffee, app/views/teachers/ModalTeacherDetails.vue
=> add modal to get teacher details

app/views/ladder/components/Leaderboard.coffee, app/views/ladder/components/Leaderboard.vue
=> display special bar in chart

app/views/teachers/TeacherStudentView.coffee
=> add linum to teacher-student-view

app/schemas/models/tournament_submission.schema.coffee
for admin view tournament leaderboard
=> fix(schema): make tournament submission schema work normal

app/views/payment/PaymentLicenseMinMaxTextComponent.vue, app/views/payment/PaymentStudentLicenseHeadComponent.vue, app/views/payment/PaymentStudentLicenseView.vue, app/views/payment/PaymentStudentLicensesComponent.vue, app/views/payment/PaymentStudentLicensesView.vue, app/views/payment/student-licenses/CocoHeadInfoComponent.vue, app/views/payment/student-licenses/OzariaHeadInfoComponent.vue, app/views/payment/student-licenses/head.scss
Related: https://github.com/codecombat/codecombat-server/pull/389
=> dsh integration changes

app/locale/en.coffee, app/styles/courses/teacher-class-view.sass, app/templates/courses/teacher-class-view.jade, app/views/courses/TeacherClassView.coffee
Regenerate button added next to Class Code input field
.
=> Give teachers ability to regenerate class codes

app/lib/aether_utils.coffee
using cpp markdown code block if exists.
keep leading space
=> better cpp documents

app/views/play/level/tome/SpellView.coffee
we now call kodekeeper server 4 times when code changes (same code). not necessary.
this commit to reduce the kodekepper server usage.
=> cache kodekeeper results for same source

app/models/User.coffee
coffee: a = not 0 <= b <= 1  converts to (!0 <= b && b <= 1) in js
fixing by adding braces
coffee: a = not (0 <= b <= 1) converts to a = !((0 <= b && b <= 1))
=> fix comparator check

app/views/courses/TeacherClassView.coffee
Save the last-viewed  `courseId` to `localStorage` and use it as default later.
=> DT: open to last-viewed chapter

app/lib/aether_utils.coffee, test/app/lib/aether_utils.spec.coffee
```cpp
function a() {}
int b = 2;
function c() {}
```
such code need to keep `int b=2;` line when translateJS
=> better translateJS

app/lib/aether_utils.coffee, test/app/lib/aether_utils.spec.coffee
2 levels in gd/cs need to be manually fix:
=> now cpp support all campaign-gd levels

app/core/utils.coffee
Vimeo urls replaced with cloudflare ones.
=> Move Vimeo CS1 videos to Cloudflare

app/lib/surface/Label.coffee
The same as here
https://github.com/codecombat/ozaria/pull/682
=> Text style for Label and refactoring from Ozaria

app/core/api/users.coffee, app/core/application.coffee, app/lib/common-utils.js, app/lib/user-utils.js, app/locale/en.coffee, app/templates/core/create-account-modal/basic-info-view.jade, app/templates/core/create-account-modal/confirmation-view.jade, app/views/core/CreateAccountModal/BasicInfoView.coffee, app/views/core/CreateAccountModal/ConfirmationView.coffee, app/views/core/RootView.coffee
=> changes for library users

app/schemas/models/campaign.schema.coffee, app/styles/editor/campaign/campaign-editor-view.sass, app/views/editor/campaign/CampaignEditorView.coffee
`&#9888;` (&#9888;) character added before unpublished levels. (Modifications copied from ozaria)
=> A way to see "published" in the level list

app/core/Tracker2/FacebookPixelTracker.js, app/core/Tracker2/GoogleAnalyticsTracker.js, app/core/vueRouter.js, app/lib/paymentUtils.js, app/views/HomeView.coffee, app/views/payment/HomeSubscriptionsSuccessView.vue, app/views/payment/online-class/PurchaseView.vue, app/views/payment/online-class/SuccessView.vue, app/views/payment/student-license/PurchaseView.vue
=> send price data along with event of purchase

app/core/utils.coffee, app/locale/en.coffee, app/locale/zh-HANS.coffee, app/styles/courses/manage-license-modal.sass, app/styles/courses/teacher-class-view.sass, app/styles/teachers/edit-student-modal.sass, app/templates/courses/manage-licenses-modal.pug, app/templates/courses/teacher-class-view.pug, app/templates/teachers/edit-student-modal.pug, app/views/courses/ManageLicenseModal.coffee
=> Yuqiang/new license UI

app/views/play/CampaignView.coffee
hide this button for anonymous taiwan users for now (until we have better parents role)
=> hide subscribe modal for anonymous taiwan users

app/schemas/subscriptions/play.coffee, app/views/play/level/tome/SpellTopBarView.coffee
We need a way to show/hide scripts when users click on Hints button in levels.
=> Added level:hints-button event for scripts

app/lib/surface/LayerAdapter.coffee
Moving ozaria PR https://github.com/codecombat/ozaria/pull/360
Without that, animated thangs aren't shown if they have negative layer priority.
=> Allow to show actions with negative layer priority

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/templates/teachers/teacher-student-view.pug, app/views/teachers/TeacherStudentView.coffee
=> show changed time in teacher student view

app/views/ladder/LadderTabView.coffee, app/views/ladder/components/Leaderboard.coffee
see https://app.asana.com/0/1193069161928913/1201992453714289 
i made it :joy: sorry.
this is a fix
=> don't set attribute to session model but just set properties

app/views/ladder/components/Leaderboard.vue
=> only allow v-html on battle column

app/assets/images/favicon/favicon-coco/manifest.json, app/assets/images/favicon/favicon-ozar/manifest.json
=> fix double coco/ozar in filepath

app/views/play/CampaignView.coco.coffee
=> hide announcement(subscribe) modal for tw anonymous users

app/core/initialize.coco.coffee, app/core/initialize.ozar.coffee, app/locale/en.coco.coffee, app/locale/en.ozar.coffee, app/locale/zh-HANS.coco.coffee, app/locale/zh-HANS.ozar.coffee, app/views/core/CreateAccountModal/BasicInfoView.coco.coffee, app/views/core/CreateAccountModal/BasicInfoView.ozar.coffee, app/views/teachers/CreateTeacherAccountView.coco.coffee, app/views/teachers/CreateTeacherAccountView.ozar.coffee
i think we can remove [these](https://github.com/codecombat/codecombat/blob/7b1787357423c8d7aafd28530e0a224b8946db32/app/views/core/CreateAccountModal/BasicInfoView.coco.coffee#L164-L171) too?
=> add email checking for tv4 globally so that our schema format could work

ozaria/site/components/teacher-dashboard/common/progress/progressLabels.vue
Alignment of code progress bubbles fixed:
=> DT: progress color code bubbles/text are unaligned 

ozaria/site/components/teacher-dashboard/BaseMyClasses/components/ClassSummaryRow.vue
New hover area defined for the border. Pls check difference on screen recording below:
BEFORE / AFTER
=> HOC & DT: Tweak class title bar hover state

app/core/initialize.ozar.coffee, ozaria/site/components/teacher-dashboard/common/SecondaryTeacherNavigation.vue
Asana issue: https://app.asana.com/0/0/1199179834445165/f
The DT top dropdowns now collapsing when any of their items are clicked.
=> DT: Secondary top-nav dropdown should close upon clicking

ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue
Asana: https://app.asana.com/0/1193069161928913/1185790669258736/f
Text on button centered vertically.
Description line height set to 14.
=> Edit Class Info Modal Polish

app/locale/en.coco.coffee, app/views/payment/v2/StudentLicensesBodyComponent.vue, app/views/payment/v2/student-license/BodyFooterComponent.vue
https://app.asana.com/0/0/1202372228861603/f
=> payment ui changes for smaller screens

app/styles/community.sass, app/templates/community-view.pug
=> add links to /editor for podcast and resources when admin

app/styles/home-view.scss, app/templates/home-view.ozar.pug
Asana link: https://app.asana.com/0/1191279859481924/1199529064573232/f
- increase the padding between value props to 100px under Engage section
All other parts of the asana task above seems to have already been done.
=> ozaria.com: Padding Issues

app/locale/en.coco.coffee, app/locale/en.ozar.coffee, app/styles/play/level/level-loading-view.coco.sass, app/styles/play/level/level-loading-view.ozar.sass, app/templates/play/level/level-loading-view.coco.pug, app/templates/play/level/level-loading-view.ozar.pug, app/views/play/level/LevelLoadingView.coco.coffee, app/views/play/level/LevelLoadingView.ozar.coffee
don't want to change my env back to coco so just screenshot the oz page. same content for coco
=> show 404 not found when level loading error

ozaria/site/components/teacher-dashboard/Panel/components/PracticeLevel.vue, ozaria/site/components/teacher-dashboard/common/CodeDiff.vue
=> introduce ace-diff to ozaria

app/locale/en.coco.coffee, app/locale/en.ozar.coffee, app/templates/base-flat.coco.pug, app/templates/home-view.coco.pug
=> change banner for non-teacher from parents to podcast page

app/assets/apcsp-local/curriculum.md, app/assets/apcsp-local/curriculum/assessment-activities-guide.md, app/assets/apcsp-local/curriculum/assessments/quiz-unit-1.md, app/assets/apcsp-local/curriculum/course-schedule.md, app/assets/apcsp-local/curriculum/explore.md, app/assets/apcsp-local/curriculum/overview.md, app/assets/apcsp-local/curriculum/performance-tasks.md, app/assets/apcsp-local/curriculum/syllabus.md, app/assets/apcsp-local/curriculum/unit-1.md, app/assets/apcsp-local/curriculum/unit-2.md, app/assets/apcsp-local/curriculum/unit-3.md, app/assets/apcsp-local/curriculum/unit-4.md, app/assets/apcsp-local/curriculum/unit-5.md, app/assets/apcsp-local/curriculum/unit-6.md, app/assets/apcsp-local/index.md, app/assets/apcsp-local/professional-development.md, app/assets/apcsp-local/professional-development/apcsp-101.md, app/assets/apcsp-local/professional-development/codecombat-101.md, app/assets/apcsp-local/professional-development/curricular-resource-requirements.md, app/assets/apcsp-local/professional-development/equity-access.md, app/assets/apcsp-local/professional-development/exam-components.md, app/assets/apcsp-local/professional-development/next-steps.md, app/assets/apcsp-local/professional-development/pd-unit-1.md, app/assets/apcsp-local/professional-development/pd-unit-2.md, app/assets/apcsp-local/professional-development/pd-unit-3.md, app/assets/apcsp-local/professional-development/pd-unit-4.md, app/assets/apcsp-local/professional-development/pd-unit-5.md, app/assets/apcsp-local/professional-development/pd-unit-6.md
All the files from `apcsp-local/` were moved from s3 to source control. 
Pls see screen recording below:
=> Put apcsp markdown files in source control

app/views/admin/MaintenanceModal.coffee, app/views/admin/components/MaintenanceModal.vue
=> better maintenance ui

app/styles/home-view.scss, app/templates/home-view.ozar.pug, app/views/HomeView.ozar.coffee
- set carousel buttons active if their slide gets active (regardless if because clicked, or automatically changed because of interval)
- do not change button colors on hover, just show mouse pointer
BEFORE/AFTER:
=> ozaria.com: Carousel buttons: wrong hover & click state

app/views/ladder/MainLadderViewV2.vue
part of https://app.asana.com/0/0/1202484318317086/f
=> styling changes on ladders page

.eslintrc.js, app/locale/en.coco.coffee, app/models/User.coco.coffee, app/views/ladder/MainLadderViewV2.vue, app/views/landing-pages/league/PageLeagueGlobal.vue
=> ladder list changes

.eslintrc.js, app/core/services/algolia.coffee, package-lock.json, package.json
Also,
- ignore coffee files from eslint
- add plugin of eslint for json files
=> change algolia api key to saurabh-s account

app/lib/aether_utils.coco.coffee
Can test on `/play/level/fire-dancing`
=> exclude io/clojure code hints from UI

app/core/forms.coffee
add exception for null emails otherwise the student without email cannot update their info
=> allow null email for validation

app/locale/en.coffee, ozaria/site/components/school-admin-dashboard/BaseMySchools/index.vue
Teachers and Students totals added for each campus. Pls check screenshot below:
=> School Admin: Show total teachers and students at campus

app/core/initialize.coffee
Swap isCodeCombat and isOzaria flags that was wrongly merged.
=> Fix merge problem for initialize.coffee

app/locale/en.coffee, app/schemas/models/podcast.schema.js, app/views/podcast/single-podcast/EpisodeComponent.vue, app/views/podcast/single-podcast/GuestInfoComponent.vue, app/views/podcast/single-podcast/HeadComponent.vue
=> add fields for additionalGuest in podcast

app/core/utils.ozar.coffee, app/views/play/CampaignView.coco.coffee
https://github.com/codecombat/codecombat-server/pull/478
=> limit free levels in china and japan

app/assets/markdown/cs1.md
Added a definition for the term "Statement", which is tested on the AP CSP exam.
=> New vocab term

ozaria/site/components/cutscene/common/CloudflareVideoPlayer.vue
Initialize the player with subtitles enabled.
=> auto trigger subtitles with Cloudflare

app/locale/en.coffee, app/templates/courses/courses-view.ozar.pug
Link to CH1 added for students without classrooms.
BEFORE / AFTER:
=> Ozaria students with no classrooms should get anon CH1 like we do in CoCo

app/templates/courses/courses-view.ozar.pug
playtest removed here: https://github.com/codecombat/codecombat/commit/a8d517b2a20586d0c794d78d462eaf7ea1489a11#diff-51d44f4171f51a2c4612073b9c7426f72235a9d638680c7daa6aebb97c799e0eL254
=> fix UI broken for students with playtest course added

app/core/Tracker2/FacebookPixelTracker.js, app/core/application.coffee, app/templates/static/layout.static.coco.pug, app/templates/static/layout.static.ozar.pug, app/views/core/CreateAccountModal/BasicInfoView.coco.coffee, app/views/core/CreateAccountModal/BasicInfoView.ozar.coffee, app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee, app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coco.coffee, app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.ozar.coffee, app/views/teachers/CreateTeacherAccountView.coffee
=> include fbq in initial html and remove it for student and home users

app/locale/en.coffee, app/views/podcast/BodyComponent.vue
=> show only top 3 podcasts initially

app/components/license/LicenseDataPerUser.vue, app/core/api/api-clients.coffee, app/core/store/modules/apiClient.js, app/core/store/modules/prepaids.js, app/views/api/components/ApiData.vue, app/views/school-administrator/dashboard/LicenseTableView.vue
reuse school-administrator view vue component to api dashbaord too
=> add license stats by student for api dashboard too

app/core/Tracker2/TwitterPixelTracker.js, app/core/Tracker2/index.js
Basically the same as FacebookPixelTracker, Twitter pixel will track all events that facebook tracked.
=> Twitter Tracker Added

app/locale/en.coffee, app/templates/courses/clan-league-stats-mixin.pug, app/templates/courses/teacher-classes-view.coco.pug, app/templates/courses/teacher-classes-view.ozar.pug
=> link ladder list page from teacher dashboard

app/styles/play/play-level-view.sass
=> make sure the real-time canvas show 100%

app/styles/courses/teacher-classes-view.sass, app/templates/home-view.coco.pug, app/templates/home-view.ozar.pug, app/views/HomeView.coco.coffee, app/views/HomeView.ozar.coffee, app/views/courses/BannerHoC.vue
The Hour of Code banner is added to homepages and teacher dashboards as well:
=> HoC banner added to both homepages

app/core/constants.coffee, app/templates/admin/administer-user-modal.coco.pug, app/views/admin/AdministerUserModal.coffee
now support edit esports product
=> support edit esports product

app/core/constants.coffee, app/views/ladder/components/Leaderboard.coffee, app/views/landing-pages/league/PageLeagueGlobal.vue, app/views/landing-pages/league/components/Leaderboard.vue
anonymizing member name in server side.
when having esports-product
for admin/teacher/classmates , show fullname.
=> set fullName and anonymizing name from server side

app/templates/play/ladder/ladder-tab-view.pug
slice nearbysessions is more reasonable than slice topsessions.
=> follow the nearby logic from leaderboard.vue:

app/core/utils.coco.coffee, app/lib/LevelLoader.coffee, app/views/ladder/LadderPlayModal.coffee, app/views/ladder/LadderView.coco.coffee, app/views/ladder/MyMatchesTabView.coco.coffee, app/views/ladder/components/Leaderboard.vue, app/views/play/SpectateView.coffee, app/views/play/level/DuelStatsView.coffee, app/views/play/level/PlayLevelView.coffee
we already use new name logic to leaderboards,
this pr make it also work in :
- MyMatchesTab.
- ladderPlayModal.
- playLevelView 
- spectateView
=> support name logic everywhere related to league

app/views/special_event/HoC2018Component.vue, ozaria/site/components/common/BaseCloudflareVideo.vue
=> HoC page: Replace youtube videos with cloudflare ones.

app/models/User.coffee, app/templates/courses/teacher-class-view.pug
display `expired` status in teacher class view
https://files.slack.com/files-pri/T3A7R00SU-F04EFK2DH4J/image.png
=> display expired status clearly

app/templates/teachers/share-licenses-joiner-row.pug
current buggy view
it should be:
=> use correct pug in merge

app/views/api/components/ApiData.vue, package-lock.json, package.json
This reverts commit 1415331966e0fb1aec7a99aaffe6d9f61eaf0f7a.
=> adding ageStats to api dashboard (#6870)

app/views/courses/TeacherClassView.coco.coffee, test/app/views/teachers/TeacherClassView.spec.coco.coffee
=> add detailed time in csv as Japan customer wanted

app/core/application.coffee, app/core/initialize.coffee, app/schemas/models/user.coffee, app/views/HomeView.coco.coffee
https://github.com/codecombat/codecombat-server/pull/548
=> use query variables instead of hash to open modal

app/templates/static/layout.static.coco.pug, app/templates/static/layout.static.ozar.pug
Testing https://www.pingdom.com/ trial
=> add pingdom script to check out their trial period

app/views/landing-pages/roblox/PageRoblox.vue
Show meaningful message if user already registered for roblox waitlist.:
pls also check backend: https://github.com/codecombat/codecombat-server/pull/555
| BEFORE      | AFTER |
| ----------- | ----------- |
| ![Screen Shot 2023-02-08 at 09 15 24](https://user-images.githubusercontent.com/11805970/217652555-0301708f-e811-4f24-b327-f85f8a37a83c.png) | <img width="1016" alt="Cursor_and_CodeCombat_-_Coding_games_to_learn_Python_and_JavaScript___CodeCombat" src="https://user-images.githubusercontent.com/11805970/217652492-254d096c-aaca-471f-a020-439bb51bc271.png"> |
=> Roblox Sign Up: Show meaningfulf message on duplicated entry

app/templates/account/subscription-view.pug
=> display correct end date when subscription is activate by code

app/components/common/Navigation.vue, app/models/User.coffee, app/views/core/RootView.coco.coffee, app/views/core/RootView.ozar.coffee
"Test as Student" functionality was not working while spying on teachers, it was working only if you logged in directly to a teacher account. 
The logic is fixed to show the "Test as Student" and "Stop Switching" options while spying the teacher account.
=> Spy mode: fix "Test as Student"

app/styles/home-view.sass, app/styles/home-view.scss, app/views/HomeView.coco.coffee, app/views/HomeView.ozar.coffee
see https://codecombat-core.slack.com/archives/C3BBBA01K/p1678297161906639
=> enable getBanner and style it

app/schemas/models/poll.schema.coffee, app/views/play/modal/PollModal.coffee
see https://github.com/codecombat/codecombat-server/pull/589 also
**and the nextURL logic is totally completed by github copilot.** i think it would work good. but maybe worth reviewing detailly 😂
=> allow hidden countries for poll

app/core/utils.coco.coffee, app/views/courses/TeacherCoursesView.coco.coffee
The available captions are added to list in the utils. 
In the future it won't be enough to add the captions in cloudlflare, they should also be added here as well.
=> Show localized captions for CS1 concept videos

app/styles/home-view.scss, app/templates/courses/teacher-class-view.pug, app/views/school-administrator/dashboard/SchoolAdminDashboardTeacherView.vue
- CoCo /school-administrator/teacher/<teacher>: add Outcomes Report link to top right
- CoCo /teachers/class/<class>: add Outcomes Report link to top right
- Oz homepage: fix white gap between footer and page gradient background
=> Update inter- and intra-site links (round 1)

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/views/teachers/TeacherStudentView.coffee
=> hide solutions for unpaid teacher

app/views/payment/v2/StudentLicensesComponent.vue
China team is developing a customer in combodia. they want to hide the price for license.
=> hide course prepaid price in cambodia

app/views/play/level/tome/editor/snippets.coffee
see https://codecombat-core.slack.com/archives/C49HU8WLA/p1680618586488659
=> fix autocompletion bug

app/views/play/level/tome/editor/autocomplete.coffee
=> fix bug that make snippets disappear

app/locale/en.coffee, app/schemas/models/user.coffee, app/views/core/AuthModal.coco.coffee, app/views/core/AuthModal.ozar.coffee, ozaria/site/components/play/PageUnitMap/hoc2019modal/ModalSignIn.vue
- Password reset token made longer
- +One week `expires` date added to password reset token
- `Your temporary password has been expired.` message shown if token was expired.
- backend: https://github.com/codecombat/codecombat-server/pull/604
=> COD- Q123-2 - Insecure Password Reset Mechanizm

vendor/esper-plugin-lang-cpp-modern.js, vendor/esper-plugin-lang-java-modern.js
fix cpp memory leak and this bug:
https://codecombat-core.slack.com/archives/C3BBBA01K/p1684123532290609
=> fix cpp memory leak and override ladder opponents js classes

app/core/treema-ext.coffee, app/views/editor/announcement/AnnouncementEditView.js
make sure the image uploaded to announcement using the absolute path so that ozaria & codecombat can both see the image.
=> force the image url to be absolute

app/locale/en.coffee, app/styles/courses/teacher-classes-view.sass, app/templates/courses/teacher-classes-view.coco.pug, app/views/courses/PodcastItemContainer.vue, app/views/podcast/trackPlayMixin.js, ozaria/site/components/teacher-dashboard/BaseMyClasses/index.vue
Latest podcast episode added to teacher dashboard. If the podcast was already played, the previous one is shown.
Pls also check [the server PR](https://github.com/codecombat/codecombat-server/pull/617)!!!
=> Embed podcast in teacher dashboard

app/templates/admin.pug, app/templates/admin/administer-user-modal.coco.pug, app/templates/admin/administer-user-modal.ozar.pug, app/templates/courses/prepaid-activation-codes-modal.pug, app/vendor.js, app/views/admin/AdministerUserModal.coffee, app/views/admin/MainAdminView.coffee, app/views/courses/PrepaidActivationCodesModal.coffee
=> remove moment-timezone from app.js bundle

app/views/HomeView.coco.coffee, app/views/core/CreateAccountModal/ChooseAccountTypeView.coffee
This reverts commit 814b6e156e7abddaf33bcaa0d13fddb0f6e54c60.
=> Revert "dont connect parents page signup from home"

app/views/core/RootView.coffee
=> Allow All Languages in Ozaria

app/schemas/models/ai_chat_message.schema.js
Necessary client changes for https://github.com/codecombat/ai/pull/130
=> add celebrate message type

app/templates/coco-home-view.pug, app/templates/home-cn-view.pug
**PR Summary**:
PR simply fixes the broken hyperlink to the Common Sense review.
=> fix: update common sense link

app/templates/ai/ai.pug, app/templates/base-ai.pug
Couldn't find a suitable template to base off of. Needed it to
1) not have a footer 
2) not be wrapped in `style-flat` due to some Tailwind CSS conflicts
Let me know if we don't want to create a 1-off template, happy to try another route!
=> Styling fixes for AI alpha

app/core/social-handlers/GoogleCalendarHandler.js
=> fix the array format in attendees

app/views/ladder/MyMatchesTabView.coffee, app/views/ladder/components/Leaderboard.coffee
in case the server side change didn't work
=> hide china prefix in ladder creator name

app/core/store/modules/game.coffee, app/core/store/modules/voiceOver.js, app/core/utils.coffee, app/lib/scripts/SpriteScriptModule.coffee, app/models/User.coffee, ozaria/engine/cinematic/SoundSystem.js, ozaria/engine/cinematic/cinematicController.js, ozaria/engine/cinematic/commands/CinematicParser.js, ozaria/engine/cinematic/dialogsystem/helper.js, ozaria/site/views/play/level/TutorialPlayView.js, test/app/lib/cinematic/cinematicParser.spec.js
CoCo TTS didn't have much of an effect on any metrics, but imagine it will be useful on the margin and for Ozaria, so turning it on generally.
=> Add TTS for Oz cinematics and level tutorials; turn TTS on generally

app/core/api/level-sessions.coffee, app/core/store/modules/levelSessions.js, app/locale/en.coffee, ozaria/site/components/teacher-dashboard/BaseSingleClass/ViewAndManage.vue, ozaria/site/store/BaseSingleClass.js
Currently, I'm enabling it only for the tecmilenio users. I will enable it for all the users after I get a new design.
https://github.com/codecombat/codecombat-server/pull/649
=> reset progress of user in course

app/core/store/modules/events.js, app/locale/en.coffee, app/schemas/models/event.schema.js, app/views/events/components/ClientCalendar.vue, app/views/events/components/EditEventComponent.vue
=> add meetinglink for events

app/locale/en.coffee, app/views/landing-pages/roblox/PageRoblox.vue
- duplicated _the_ removed from title
- success message shown for repeated signups (for same email address) - so users could see again how to join
| BEFORE | AFTER | 
| --- | --- |
|  ![codecombat com_roblox (2)](https://github.com/codecombat/codecombat/assets/11805970/ad64e85a-7ee0-47e8-b64b-1bd943fa5b45) ![image (33)](https://github.com/codecombat/codecombat/assets/11805970/fe967224-6719-4b62-ac1c-d281896ab674) | <p align="top"> ![beta-conflict](https://github.com/codecombat/codecombat/assets/11805970/43845d01-18d2-4a52-a53c-9c3cf68bf70e) </p> |
=> /roblox: small enhancements

app/core/constants.coffee, app/locale/en.coffee, app/views/events/components/EditEventComponent.vue, app/views/events/components/EditInstanceComponent.vue, app/views/events/components/TimeZonePicker.vue, package-lock.json, package.json
and use 12 hours display for time
=> add timezone selection

app/views/play/level/tome/SpellView.coffee
if we dont cast the problem, it won't add marker again and again.
=> fix the problem cast again and again

package-lock.json, package.json
this is a bug in ace-diff. so i update that and use the latest tag version
=> fix copyrightcontainer bug

app/views/play/level/LevelChatView.coffee, app/views/play/level/tome/Spell.coffee
cpp now works. but seems AI doesn't really understand our cpp structure (not find main is missing :joy:)
i think it also fix this issue: https://linear.app/codecombat/issue/AI-139/make-sure-we-arent-sending-any-personally-identifiable-information-to
=> don't send player name and send correct cpp src in level chat

app/lib/LevelBus.coffee
`tagger` function now requires the `concepts` collection to be passed as a parameter.
It was missing so this PR adds it.
=> Fix Ozaria SolutionConceptTagger Error

app/schemas/subscriptions/play.coffee, app/views/play/level/LevelChatView.coffee, app/views/play/level/tome/SpellView.coffee
seems chima in china stops work now, so i cannot test it manually.
=> make button show/hide content correct

app/locale/en.coffee, app/locale/zh-HANS.coffee, app/views/play/level/tome/ProblemAlertView.coffee
=> adding i18n first prompt

app/views/play/level/LevelChatView.coffee
Reverts codecombat/codecombat#7116
nick find a bug in it. let's revert first
=> Revert "run code first then save chat message"

app/core/api/events.js, app/core/social-handlers/GoogleCalendarHandler.js, app/core/store/modules/events.js, app/models/User.coffee, app/schemas/models/event.schema.js, app/views/events/components/EditEventComponent.vue, app/views/events/components/EditInstanceComponent.vue, app/views/events/components/SingleCalendar.vue
now edit events can sync to google calendar. tested manully
see server side  pr here: https://github.com/codecombat/codecombat-server/pull/673
=> sync events updates to google and fix some bugs

app/views/play/level/LevelChatView.coffee
if the buton doesn't refresh, it could work on first frame
=> don't refresh button

app/views/landing-pages/roblox/PageRoblox.vue
=> /roblox video updated

scripts/copy-i18n-tags.js, scripts/generateRot13Locale.js
manually test with rot13.js and ar.js seems work fine
=> fix copy-i18n for js instead of coffee

app/views/account/AccountSettingsView.js
=> Fix: Made email comparison case-insensitive for account deletion

app/locale/en.js, app/styles/play/level/tome/spell-top-bar-view.sass, app/templates/play/level/tome/spell-top-bar-view.pug, app/views/play/level/AskAIHelp.vue, app/views/play/level/AskAIHelpView.js, app/views/play/level/tome/SpellTopBarView.coffee
=> add option in spellbar to get hint from ai level chat

app/views/outcomes-report/OutcomesReportResultComponent.vue
also adding `?newReport=1` in normal outcome-report to test
=> add newreport for classrooms/teachers/school-admins

app/locale/en.js, app/templates/coco-home-view.pug
AI-141
https://linear.app/codecombat/issue/AI-141/link-ai-level-help-faq-from-various-places
=> add ai level chat in faq

app/core/urls.js, app/templates/courses/courses-view.pug, ozaria/site/components/play/PageUnitMap/index.vue
Instead of 4 sync calls, we do 2 + 2 parallel calls to get data to load map
=> parallelize calls to fetch data on ozaria map page

app/views/ladder/components/Leaderboard.js
(tournament owner doesn't want teams showing up here)
Test: /play/ladder/desert-duel/clan/65775bd45f6f1900185abf5b?tournament=65775da26dd00500194eaf3f
=> Hide team display in leaderboards for a particular tournament

app/locale/en.js, app/styles/modal/ai-league-promotion-modal.sass, app/templates/core/ai-league-promotion-modal.pug, app/views/HomeView.js, app/views/core/AILeaguePromotionModal.js, app/views/play/CampaignView.js
=> show ai league promotion modal fro home users on closing on subscribe-modal

app/locale/en.js, app/views/parents/LiveOnlineClassesPromotionModal.vue, app/views/payment/HomeSubscriptionsSuccessView.vue
=> show loc modal after successful payment

ozaria/site/views/play/level/tome/Spell.coffee, ozaria/site/views/play/level/tome/SpellView.coffee
fixes ENG-4
these levels require update (mainly on 2 `for` with same variable like `int i`, need to update to single declearation. or checking `&&` `||` these logical operator for goals). capstone levels may work. just verifier reports it has issue. but manually test works good
```
CH3.Capstone.b
CH3.M4.L3.L2.B
CH3.M4.L3.L1.B
CH3.M4.L2.CL1.B
CH3.M4.L1.L3.B
CH3.M3.L1.L1.B
CH3.M2.L2.L5.B
CH3.M2.L2.L4.B 
CH3.M2.L2.L3.B 
CH3.M1.L1.L4.B
1UP.M4.L2.L2.B
1UP.M4.L2.L3.B
1UP.M4.L2.L4.B
CH4.M1.L3.L2
CH4.M1.L3.L3
CH4.M1.L4.L2
CH4.M1.L4.L3
CH4.M1.L4.L4
CH4.M1.L4.L5
CH4.M2.L1.L1
CH4.M2.L1.L2
CH4.M2.L1.L3
CH4.M3.L2.CL1
CH4.Capstone.EX1
CH4.Capstone.EX2
CH4.Capstone.EX3
CH4.Capstone
```
=> allow ozaria to play cpp levels

ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue, ozaria/site/components/interactive/PageInteractive/index.vue, ozaria/site/components/interactive/PageInteractive/insertCode/index.vue, ozaria/site/components/play/PageIntroLevel/index.vue
tested in ch3 module 1 & 2. 
fix ENG-92
=> fallback to javascript interactive content for cpp

app/templates/play/level/chat.pug
=> enable chat icon to show and hide ai bot chat

app/styles/play/level/tome/spell-top-bar-view.sass, app/templates/play/level/tome/spell-top-bar-view.pug, app/views/play/level/tome/Spell.coffee, app/views/play/level/tome/SpellTopBarView.coffee
=> level chat classroom version fix

app/locale/en.js, app/views/apcsp/PageCurriculum.vue
=> ENG-90: Update AP CSP Portal webpage for those without active student licenses.

app/views/play/level/LevelChatView.coffee
=> track analytics for level bot usage

app/views/courses/JoinClassModal.js
Previously there was no error message if process failed after hitting the Join Class button.
=> Show Error Message if Joining Classroom Fails

app/components/common/Navigation.vue, app/locale/en.js, app/views/payment/ManageBillingView.vue
- show option in dropdown for unverified users and move position in dropdown upwards
- better messaging and i18n strings
fixes ENG-129
=> manage billing changes

app/styles/play/ace-editor.sass, ozaria/site/views/play/level/tome/SpellView.coffee
fix ENG-143
when copy config from coco, some extra code breaks oz ace editor. fix it
=> fix oz ace editor style

app/locale/en.js, app/views/apcsp/PageCurriculum.vue
/apcsportal redesign: 
| Mobile | Desktop | 
| --- | --- |
| ![localhost_3000_apcsportal (7)](https://github.com/codecombat/codecombat/assets/11805970/99c2a2e7-ac66-4657-935e-b0281a768fca) | ![localhost_3000_apcsportal (8)](https://github.com/codecombat/codecombat/assets/11805970/829de8af-f396-46d3-8396-da7e60f7450c) |
=> ENG-89 - Update AP CSP Portal webpage

app/views/codequest/Header.vue
=> /codequest: add date prominently

app/core/api/user-credits.js, app/views/play/level/LevelChatView.coffee
=> update the user credit uid to chat message id

app/templates/courses/classroom-settings-modal.pug
=> enable level chat by default for class

app/views/play/modal/LeaderboardTabView.js
=> anonymize leaderboard for library

app/locale/en.js, app/views/apcsp/PageCurriculum.vue, app/views/apcsp/PageMarketing.vue
| before | after | 
| --- | --- |
| ![codecombat com_apcsportal](https://github.com/codecombat/codecombat/assets/11805970/9d7b926a-4db1-4d2c-9710-53183453c193) | ![localhost_3000_apcsportal (9)](https://github.com/codecombat/codecombat/assets/11805970/823efdc3-9338-4e8b-819f-da8c945b5e16) |
=> ENG-174 - Adamk/apcsp portal update styles

app/lib/surface/Surface.coffee
=> fix capstone not running error: .get called on undefined

app/views/play/modal/PlayHeroesModal.js
a sad story is that seems many users already set their code-format to `python` , need a way to fix them
=> fix gpt bug

app/views/codequest/frame/core/Domestic.vue
=> /codequest update pricing

app/schemas/models/ai_chat_message.schema.js, app/schemas/models/ai_document.schema.js, app/schemas/models/ai_model.schema.js, app/schemas/models/ai_project.schema.js, app/schemas/models/ai_scenario.schema.js
https://github.com/codecombat/ai/pull/205
=> copy ai schema, add displayName in ai-model

app/components/common/elements/CarouselComponent.vue, app/core/Router.js, app/core/vueRouter.js, app/lib/dynamicRequire.js
=> start experiment on home-page

ozaria/site/styles/play/play-level-view.sass
=> also need fix ozaria solution background event

app/views/landing-pages/grants/PageGrants.vue
=> update grants.gov link

app/locale/en.js, app/views/ai/AIView.js, app/views/core/CocoView.coffee
=> get credits cta

app/views/outcomes-report/OutcomesReportResultComponent.vue, app/views/outcomes-report/PageOutcomesReport.vue
https://github.com/codecombat/codecombat-server/pull/807
clean code
=> use newReport by default

app/schemas/models/background_job.schema.js
=> background-job schema

app/schemas/models/ai_scenario.schema.js
backend PR: https://github.com/codecombat/codecombat-server/pull/821
hackstack PR: https://github.com/codecombat/ai/pull/220
=> ENG-310 - use editor/upload for scenario cover images

app/components/common/BaseCloudflareVideo.vue, app/components/common/backgrounds/BackgroundContainer.vue, app/components/common/buttons/CTAButton.vue, app/components/common/elements/BoxPanel.vue, app/components/common/elements/CarouselComponent.vue, app/components/common/image-containers/VideoBox.vue, app/locale/en.js, app/views/home/PageHome.vue
Now both SEO and Accessibility scores are 100%.
With merge we should wait for some response [here](https://codecombat-core.slack.com/archives/C9M56GXA9/p1709560434916689).
=> ENG-305 - Enhance Lighthouse SEO and Accessibility scores

app/views/outcomes-report/PageOutcomesReport.vue
=> use background job by default for outcome reports

app/locale/en.js, app/views/outcomes-report/OutcomesReportResultComponent.vue, app/views/outcomes-report/SummaryComponent.vue
=> add a summary component in outcome reports

app/views/outcomes-report/PageOutcomesReport.vue
fix ENG-359
my bad. when resolving merge confict, this param is missing
=> resolve a missing change when merge code

app/views/outcomes-report/PageOutcomesReport.vue
=> merge suborgs for reports

app/locale/en.js, app/views/outcomes-report/OutcomesReportResultComponent.vue, app/views/outcomes-report/PageOutcomesReport.vue
see server changes: https://github.com/codecombat/codecombat-server/pull/848
fix ENG-262
=> show teacher name info

app/views/play/menu/GameMenuModal.js, ozaria/site/views/play/level/PlayLevelView.js
=> fix level options and auto-complete in ozaria

ozaria/site/views/play/level/tome/SpellView.coffee
=> chapter one lineheight is different

app/locale/en.js, app/models/User.js, app/schemas/models/user.js, app/views/outcomes-report/OutcomesReportResultComponent.vue, app/views/outcomes-report/PageOutcomesReport.vue
=> add flag to identify district owner id

app/core/application.js, app/core/utils.js, app/lib/i18n/AIPostProcessor.js, app/locale/zh-HANS.js, app/views/play/level/tome/Spell.coffee
fix ENG-363
it should cover most of translations. maybe left 5% or less. (like the code comment we do not use utils.i18n before, but use other logic to grab i18n)
=> guard i18n functions to auto remove [AI_TRANSLATION]

app/views/payment/student-license/PurchaseView.vue
=> ENG-352 - Calculate email address based on student id

app/locale/en.js, app/models/Clan.js, app/views/outcomes-report/ClanLeagueStatsComponent.vue, app/views/outcomes-report/OutcomesReportResultComponent.vue, app/views/outcomes-report/PageOutcomesReport.vue
see also https://github.com/codecombat/codecombat-server/pull/856
fix ENG-270
=> adjust ai league stats to fit outcomes-report

app/styles/play/menu/change-language-view.sass, app/templates/play/menu/change-language-view.pug, app/views/play/menu/ChangeLanguageView.js
fix ENG-397
onhidden may triggered by mistake. let's use confirm button to change code/format
=> adding confirm button and disable onhidden

app/schemas/models/low-usage-user.schema.js
=> low-usage-user schema

app/core/Router.js, app/core/api/index.js, app/core/api/low-usage-users.js, app/core/store/index.js, app/core/store/modules/lowUsageUsers.js, app/core/vueRouter.js, app/views/admin/low-usage-users/DataComponent.vue, app/views/admin/low-usage-users/DataItemComponent.vue, app/views/admin/low-usage-users/FilterComponent.vue, app/views/admin/low-usage-users/MainDashboardView.vue, app/views/admin/low-usage-users/low-usage-users-helper.js
=> low usage front-end

app/views/play/level/PlayLevelView.coffee, app/views/play/menu/GameMenuModal.js
fix ENG-418
if classroom enable items:
if classroom do not enable items:
=> hide toggle hero options in classrooms which do not enable items

app/core/blocklyUtils.js, app/lib/code-to-blocks.js, app/lib/translate-utils.coffee, app/models/Level.js, app/views/play/level/tome/SpellView.coffee, app/views/play/level/tome/editor/autocomplete.coffee
Fixes various issues with loops and blocks, autocomplete snippets, toolbox snippet documentation, loading issues with no `aceConfig` set, and `ace-diff` cleanup. Adds icon-based and simple dropdown loop blocks.
=> CodeCombat Junior dropdown loop block implementation

ozaria/site/components/teacher-dashboard/BaseSingleClass/table/TableClassFrame.vue
fix ENG-328
i don't know why block isn't working. but i notice the header uses inline-block and works good. so I test inline-block and it works good too
=> inline-block has enough width for table row

app/core/api/clans.js, app/core/store/modules/courses.js, app/views/outcomes-report/OutcomesReportResultComponent.vue, app/views/outcomes-report/PageOutcomesReport.vue
=> add district ai league stats

app/views/core/CreateAccountModal/BasicInfoView.js, app/views/core/CreateAccountModal/CreateAccountModal.js
=> skip birthday in china individual path

app/locale/en.js, ozaria/site/store/BaseSingleClass.js
Show more detailed message to explain that user is probably trying to unlock a level that is not locked itself, but locked by a previous one.
=> ENG-313 - enhance user message for unlock attempt on unlocked level

ozaria/site/components/teacher-dashboard/common/progress/progressDot.vue
=> ENG-338 - Better color scheme for locked + completed level

app/views/courses/TeacherClassView.js
fix ENG-455
having correct course list for betaTester
=> junior is beta courses instead of released

ozaria/site/components/teacher-dashboard/BaseSingleClass/ViewAndManage.vue, ozaria/site/components/teacher-dashboard/BaseSingleClass/index.vue, ozaria/site/components/teacher-dashboard/common/Dropdown.vue
fix ENG-158
this part is now sticky after refresh (in same browser).
=> make sort method sticky in ozaria dashboard

app/core/store/modules/seasonalLeague.js, app/views/ai-league/PageLeagueTeachers.vue
=> ENG-155 / add pagination to ai-league on teacher dashboard

app/locale/en.js, app/views/ai-league/PageLeagueTeachers.vue, app/views/ladder/MainLadderViewV2.vue
fix ENG-454
let's introduce custom page first. can update Design later
=> add custom league toggle

app/views/admin/low-usage-users/MainDashboardView.vue
=> Added css to decrease title font size

app/views/courses/TeacherClassView.js
fix ENG-477
this.courses is not suit for everyone now. use latestReleasedCourses instead
=> default select correct course too

app/lib/LevelLoader.coffee, app/locale/en.js, app/styles/play/level/level-loading-view.sass, app/templates/play/level/level-loading-view.pug, app/views/play/level/LevelLoadingView.coffee
Reverting the revert commit.
Also missing condition added.
| non-locked | locked | 
| --- | --- | 
| ![nonlock](https://github.com/codecombat/codecombat/assets/11805970/318e8a36-aa1e-4251-bd65-0f5a396b6dc6) | ![lock](https://github.com/codecombat/codecombat/assets/11805970/6133f9bb-7090-44a9-8ec7-d71399702231) |
=> Fix locked level message issue

ozaria/site/components/teacher-dashboard/BaseMyClasses/components/ClassSummaryRow.vue, ozaria/site/components/teacher-dashboard/common/ClassInfoRow.vue, ozaria/site/components/teacher-dashboard/common/SecondaryTeacherNavigation.vue
=> ENG-464 - Truncate long class names in sidebar

ozaria/site/components/teacher-dashboard/BaseSingleClass/index.vue
fix sorting by moving sortMethod from computed to data
| BEFORE | AFTER | 
| --- | --- | 
| ![nonosort](https://github.com/codecombat/codecombat/assets/11805970/e08cf9a4-e6ff-49ae-801a-c1b4ff31b63a) | ![oksort](https://github.com/codecombat/codecombat/assets/11805970/0f62ae96-e744-4f14-a25c-2c4194f636b9) |
=> ENG-481 - Student sort feature in Ozaria teacher dashboard not working

app/views/admin/low-usage-users/FilterComponent.vue, app/views/admin/low-usage-users/MainDashboardView.vue
Added a sort by license toggle.
=> Added sort by license checkbox

app/views/ai-league/PageLeagueTeachers.vue, ozaria/site/components/teacher-dashboard/common/SecondaryTeacherNavigation.vue
- fix team select & activate ai-league in nav
=> ENG-527 - Enable AI-league in the sidebar

app/components/common/Navigation.vue
=> Removed manage bill option for teachers from the dropdown menu

app/components/common/Navigation.vue, app/core/api/payment.js, app/locale/en.js, app/views/payment/ManageBillingView.vue
=> merge manage billing view and billing history view

app/locale/en.js, app/views/account/robloxButton.vue
=> ENG-569 - Add age restriction warning to roblox connection

app/views/core/CreateAccountModal/CreateAccountModal.js
This modification is required for the script that counts how people are behaving on the birthday signup modal.
backend PR: https://github.com/codecombat/codecombat-server/pull/891
=> ENG-493 - CreateAccountModal: add tracking to every screen change

ozaria/site/components/teacher-dashboard/BaseSingleClass/table/CellStudent.vue
Use [logic from old dashboard](https://github.com/codecombat/codecombat/blob/af877c3abb9b9c3fccfd5f1e87f1046953d7ed3d/app/templates/courses/teacher-class-view.pug#L243-L244) to determine if course is finished.
=> ENG-589 - Certificates not showing up

app/locale/en.js, app/styles/modal/subscribe-modal.sass, app/styles/premium-features-view.sass, app/templates/core/subscribe-modal.pug, app/templates/premium-features-view.pug, app/views/PremiumFeaturesView.js, app/views/core/SubscribeModal.js
fixes ENG-599
/premium page
subscribe modal
=> show warning message to parent before subscribing to home

ozaria/site/components/teacher-dashboard/BaseSingleClass/ViewAndManage.vue
=> Moved 'Manage Class' and 'Assign Content' next to each other

ozaria/site/components/teacher-dashboard/modals/ModalEditStudent.vue
=> ENG-586 - Add Last Played Info to Student Modal

ozaria/site/store/BaseSingleClass.js
=> Update confirmation message for resetting student progress to include a warning

app/lib/LevelLoader.coffee
I was not able to reproduce the issue, but this check should fix the problem.
=> ENG-561 - do not call @classroomLoaded if destroyed

app/locale/en.js
=> need a space

bower.json
=> update esper version to fix python str bug

ozaria/site/components/teacher-dashboard/BaseSingleClass/ViewAndManage.vue
=> Update css for 'manage class' to align on the left side

app/templates/core/subscribe-modal.pug, app/views/core/SubscribeModal.js, app/views/parents/mixins/getPremiumForChildMixin.js
=> dont show warning message when buying for kid

app/locale/en.js, ozaria/site/components/teacher-dashboard/modals/ModalEditStudent.vue
=> bugfix when student has not played any level in lastPlayed

app/components/common/Navigation.vue
=> ENG-607 - Nav: Do not hide teacher dashboard for school admins

app/locale/en.js, ozaria/site/components/teacher-dashboard/common/progress/progressDot.vue
| before | after |
| --- | --- |
| <img width="1632" alt="CodeCombat_-_Coding_games_to_learn_Python_and_JavaScript___CodeCombat" src="https://github.com/codecombat/codecombat/assets/11805970/f5219f1c-2107-4dda-87ed-36c92b689078"> |  <img width="1586" alt="Cursor_and_CodeCombat_Teacher_Dashboard" src="https://github.com/codecombat/codecombat/assets/11805970/b7e74ed6-9d0a-4245-8dc8-4bd63239e324"> |
=> Fix progress dot layout and add missing i18n text

app/models/User.js
It should work pretty much as well as C++.
=> Take Java out of beta for teachers

app/components/common/Navigation.vue
New PR from: https://github.com/codecombat/codecombat/pull/7441
=> Fixed caret colour

app/views/ai-league/PageLeagueTeachers.vue
=> Show dropdown even when there are no classes

app/views/school-administrator/teachers/SchoolAdminTeacherListView.vue
=> Fixed incorrect html escaping for school administrators

app/locale/en.js, ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue
fix ENG-487
now creating:
and editing:
=> hide some options in creat class modal

app/locale/en.js, app/views/apcsp/PageMarketing.vue
=> Added button to AP CSP Marketing Page

ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue
Ozaria AI Hint issue:
Coco alignment issue from Items:
=> fix alignment issues after introduction of more options

app/views/editor/campaign/CampaignEditorView.js
We had two implementations for CampaignsNodes for setting adjacent campaigns, but neither worked because of merging typos. Fixed typos and condensed down to one.
Tried doing similar for LevelsNodes, but turned out we needed different approaches (assuming Ozaria approach works for Ozaria; it didn't for CodeCombat). Refactored a bit there.
=> Fix CampaignEditor Treema nodes for Campaigns

app/core/store/modules/gameContent.js
=> get campaign game-content cached on edge

app/core/Router.js, app/core/vueRouter.js, app/locale/en.js, app/views/apcsp/PageMarketing.vue, ozaria/site/components/teacher-dashboard/common/SecondaryTeacherNavigation.vue, ozaria/site/components/teacher-dashboard/common/constants.js
=> Add APCSP button on navigation panel of teacher dashboard

ozaria/site/components/teacher-dashboard/modals/ModalGetLicenses.vue
fixes ENG-690
Before touching
After touching
=> Only show "Field is required" after blurred past and changed css

app/views/home/PageHome.vue
=> Teachers are directed to /teachers/classes instead of opening the account creation modal

app/locale/en.js, ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ButtonCurriculum.vue, ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ChapterInfo.vue
=> Added curriculum button in teacher dashboard

app/core/api/online-classes.js, app/schemas/models/online_teacher.js, app/templates/admin/administer-user-modal.pug, app/views/admin/AdministerUserModal.js, app/views/online-class/SchedulerView.vue
fix ENG-666
for tuesday set 0-20 avaliable
but in google calendar having events. (here using brehan@codecombat.com for testing.)
so final:
=> sync google calendar free/busy

app/core/utils.js
fix ENG-750
maybe i shouldn't run the eslint-fix in this file 😂 the important change is at the line 323
without licenses:
with:
NOTE: the json is generated by gpt-4o. but I double checked the link is correct
=> add cs3 lessons

app/locale/en.js
client for https://github.com/codecombat/ai/pull/258
=> add i18n for HS student warning

app/views/user/CertificatesView.js
=> bugfix in certificates not loading in parent dashboard

app/locale/en.js
| before | after |
| --- | --- |
| ![Screen Shot 2024-07-03 at 2 40 38 PM](https://github.com/codecombat/codecombat/assets/11805970/8eb5ad12-d8c3-40e1-9aad-08304dc21326) | <img width="1098" alt="CodeCombat__the_most_effective_computer_science_solution_for_schools" src="https://github.com/codecombat/codecombat/assets/11805970/c1c6db90-8e0e-4450-a770-8c8036827fb1"> |
=> fix: schools page testimonial name

ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ModuleContent.vue
=> hide practice levels for junior

.eslintrc.js
backend PR: https://github.com/codecombat/codecombat-server/pull/1066
=> ENG-1071 - eslint: force to use trailing comma

app/views/landing-pages/league/components/YearlyArenaInfo.vue
now it has same size. 
fix ENG-1192
draft because waiting reply on how to deal with `previous season`
=> use same size for image and video

app/locale/en.js, app/views/exams/ProgressPage.vue, app/views/exams/StartPage.vue
=> feedback changes

ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/curriculum-guide-helper.js
=> change code format for junior modules

app/views/play/level/modal/CourseVictoryModal.js
bug come from https://github.com/codecombat/codecombat/pull/7846/files#diff-e47a5a805c24ac37e9c5a613e8bc83b3f5fee73fef972514a58c2ce6c0a84e03R132
fix ENG-1752
=> bring back missing !
