scripts/devSetup/factories.py
scripts/devSetup/repositoryInstaller.py

There's no good reason to leave mongo and node out in the cold in terms of distro-provided updates. This ensures that Arch and Ubuntu get those. I'll add more distros as requested, or anyone else can. They're pretty easy.

Distro-specific devSetup for Arch Linux and Ubuntu

---

app/views/account/AccountSettingsView.coffee

In the code before, onInputChanged function was called manually, but the parameter was not passed. I think it's better to trigger the event, than calling the callback function of the event.

Fix bug: cannot upload profile picture

---

app/templates/play/campaign-view.jade

I made it equal to the #volume-button, because they looked different.

Made #back-button a button

---

app/views/play/level/tome/SpellView.coffee

fixed auto-complete bug #2233 
Zatanna's tracking doesn't seems to work and is somehow loosing references of oldsnippets. 
Calling  @zatanna.addSnippets [], lang in SpellView.destroy  destroys old snippets from ace snippetmanager

Autocomplete bug fix #2233 - method 2

---

app/views/play/level/modal/HeroVictoryModal.coffee

A small fix to the PR #2313. 
This is just a small fix for making the victory dialog displays correctly when you are in the "god mode". Everything with the "god mode" should be ok now.

A small fix to the PR #2313

---

bower.json

If the user did not have access to SSH towards git, the installation would fail:  This was causing problems such as ![this](https://s3.amazonaws.com/uploads.hipchat.com/60497/1761100/RNGJU5a6mMMyI53/Error.png)

Replaced git for https in clone URL.

---

app/locale/en.coffee
app/styles/play/modal/play-heroes-modal.sass
app/templates/play/modal/play-heroes-modal.jade

(Issue #2307) 
Now you can also see the type of a hero in the hero selector modal

Add type (warrior/ranger/wizard)  to hero selector modal (Issue #2307)

---

app/styles/play/campaign-view.sass
app/templates/play/campaign-view.jade

There was a level indicator in campaign view, but it said XP and was confusing.
I changed it to say 'Level' for clarity.

Clarified level indicator for #2351

---

app/views/editor/campaign/CampaignEditorView.coffee

Override  RootView's onClickLoginButton method in CampaignEditorView with a blank method so that only CampaignView is listening to this method.

Issue #2082: Campaign editor login fixed

---

app/styles/play/level/modal/hero-victory-modal.sass

This fixes the issue #1917 for many languages such as Hungarian, Italian, Japanese, ...
The expression "Gems Gained" currently doesn't have translations in many languages so probably the issue #1917 will still be there for a while.

Update hero-victory-modal.sass (Issue 1917)

---

scripts/copy-i18n-tags.coffee

Fix Issue #2428
So, how it works.
Dev change some line in en.coffee. 
If he add {change} in comment of this line:
* this {change} will be added to all non-en files for this line
* {change} will be removed from en.coffee
If there is no comment in non-eu - " # {change}" will be added to line
If there is {change} in non-eu already - no doubles of {change}
Old mechanism of syncing comments from en also isn't broken - if there is a change in comment in eu and {change} in non-eu then new_comment + {change} will be added to non-eu
Totals: what is needed from dev? add {change} to en.coffee when dev change line. thats all.
If it will be merged to master, @popey456963 or @nwinter could you update devs guide for this? and some anounce would be great.
Also @Imperadeiro98 please participate in the …

Adding {change} to files when propagination.

---

app/templates/i18n/i18n-edit-model-view.jade
app/views/i18n/I18NEditModelView.coffee

Fix for Issue https://github.com/codecombat/codecombat/issues/2455
Change the layout to
Description 1
en
non-en
Description 2
en
non-en
etc...
It looks like this

More humane view of i18n-editor

---

.gitignore
.npmignore
Vagrantfile
scripts/vagrant/brunch.bat
scripts/vagrant/brunch.sh
scripts/vagrant/dev-server.bat
scripts/vagrant/dev-server.sh
scripts/vagrant/fillMongo.sh
scripts/vagrant/provision.sh

Automatic setup of a CodeCombat development environment using Vagrant, VirtualBox, and Ubuntu.
Once integrated, I can update the wiki to reflect the new instructions:
1. `vagrant up` from the root directory
2. `scripts/vagrant/brunch.sh` from the root directory
3. `scripts/vagrant/dev-server.sh` from the root directory
Once Brunch indicates that it's done compiling, visit http://localhost:3000.
The Vagrantfile and provisioning scripts were originally developed by dpen2000 and are hosted on GitHub under an MIT license. I am contributing based on the permissions under the MIT license to use, copy, modify, merge, publish, distribute, and sublicense without limitation.

Integrate Vagrant

---

scripts/vagrant/backup.bat
scripts/vagrant/backup.sh
scripts/vagrant/backupMongo.sh
scripts/vagrant/fillMongo.sh
scripts/vagrant/update.bat
scripts/vagrant/update.sh

Adds a script that can be used to backup the `users` and `earnedachievements` collections.
Designed to allow rebuilding the Vagrant VM (with `destroy` and `up`) without losing created users.

add user backup / restore for Vagrant

---

scripts/vagrant/brunch.sh
scripts/vagrant/dev-server.sh
scripts/vagrant/provision.sh

I think I've tracked down the issue that made Vagrant misbehave on Windows.
It appears that when there is a version mismatch between VirtualBox on the host and the VirtualBox Guest Additions inside the VM, symbolic links do not work for shared folders.
Guest additions is installed when the base box is built, so we can't easily control the version, and we don't want this cropping up every time someone upgrades VirtualBox. But npm needs symbolic links to work right. (Apart from this, npm likes long path names, which are also an issue within shared folders on Windows.)
I tossed around a few ideas and finally settled on making a directory within the VM and bind mounting it over top of `node_modules`. It works for me on Windows 7 with the latest VirtualBox.

Vagrant node modules

---

Vagrantfile

Forward the websocket port out of the virtual machine so the browser can connect to it

add websocket port forward for Vagrant

---

config.coffee
scripts/vagrant/brunch.sh

While testing with Vagrant, I noticed that changes made on the host weren't automatically getting picked up by brunch, but changes on the VM were.
I created a config section for brunch that switches brunch over to watching files by polling and updated the script so it gets used when running via Vagrant.
I do see a CPU hit from this while brunch is running, but it seems worth it since otherwise it breaks a pretty important part of the development workflow.

vagrant brunch detect file changes made on host

---

app/lib/world/vector.coffee

Vector.toString changed to accept precision parameter, defaulted to 2. Allows more natural display of small or normalized vectors. removed non-functional useZ parameter.

Vector.toString precision parameter

---

app/views/play/CampaignView.coffee

Prevent the campaign map yellow arrow from pointing to replayable levels, so people don't think they're required for the campaign progression.

Yellow arrow shouldn't point to replayable levels

---

app/styles/play/ladder/ladder-tab-view.sass
app/styles/play/ladder/ladder.sass

adjusted max-width to 100px, fixes #2373

Limit multiplayer leaderboard name width even more

---

app/views/play/menu/InventoryModal.coffee

This fixes the main issue of #2740, allowing the player to play the level if the required ring is equipped on either ring slot.
There's still a small problem: if the player already had a ring equipped in the `right-ring` slot, the Ring of flowers will not display as required due to this [line](https://github.com/codecombat/codecombat/blob/0df6da7efa3df9ff6cd0e65133ff31923a9a0ee8/app/views/play/menu/InventoryModal.coffee#L436). This seems to be a different issue though, probably related to the `unequipLevelRestrictedItems` logic.

Improved `updateLevelRequiredItems` logic regarding rings, fixes #2740

---

Vagrantfile
scripts/vagrant/provision.sh

* This updates the vagrant provisioning script to correctly set the ulimits in Ubuntu, since the `bin/coco-brunch` file can't set them properly when run as the vagrant user.
* Added some basic support into the Vagrantfile for VMware providers and uploaded a VMware compatible vagrant box based on trusty64 to https://github.com/spkane/vagrant-boxes/releases/download/v1.0.0/trusty64_vmware.box, that folks can use.

Add VMware support and fix ulimits

---

app/views/play/modal/PollModal.coffee

jQuery converts data strings into a possible JavaScript value, so keys like '0' and '1' get converted into numbers, which fails the validation (it expects a string for a key).
fixes #2924

Fix poll keys when key is a number

---

headless_client.coffee
headless_client/worker_world.coffee
package.json
server/queues/scoring.coffee

"Shims" `lscache`, support io.js < v3.0.0. Make simulating `one-game` possible.
Tested on Linux with Node.js v0.10.40 and v0.12.7; as well as io.js v2.5.0.
It still won't work with io.js v3.0.0 because `webworker-threads` doesn't compile properly, so that's another problem.
Hopefully nothing else changed (as in the actual simulation results).

Fix the headless simulator

---

app/views/editor/article/ArticleEditView.coffee

This commit is for issue #2729. Probably the bug occurred because it takes a moment for the preview page to get loaded in the new window. Now the button works as intended.

Fixed #2729 (bug in the article preview button)

---

app/locale/pt-BR.coffee

Changed "torneir" to "torneio" and  "Era dos Programadores" to "Ás dos Programadores"

Link to Ace of Coders

---

app/views/play/menu/GuideView.coffee

Original bug report: http://discourse.codecombat.com/t/embedded-video-in-hint-section/5309

Allow embedded help videos to go fullscreen

---

app/styles/common/common.sass
app/views/play/menu/GuideView.coffee

This patch makes iframe borders render identically in all supported browsers (i.e. no border).
Although Chrome does not displays borders around iframes by default, Firefox and Edge (IE) had visible iframe borders prior to this patch. This is because, as [previously mentioned](https://github.com/codecombat/codecombat/pull/3122#discussion_r42338590), the DOM property was mistyped as `frameborder` when it should be `frameBorder`.
As this is presentational issue, it feels more appropriate to fix it using CSS. Therefore, I've removed the buggy JS code and added a generic CSS solution to reset iframes' border styling.

Remove iframe borders using CSS instead of DOM

---

app/lib/world/vector.coffee
test/app/lib/world/vector.spec.coffee

Related to Issue #3110.
- Added hack to detect when it's in Aether-transpiled
- Made the instance methods available class methods
- Made the class methods available as instance methods that will not mutate in player code
I also added "...Self" methods to indicate that a method will mutate. Currently the regular methods will still mutate when called outside of Aether-transpiled code. My thinking is that it allows for refactoring engine code to the Self functions (.add -> .addSelf) to preserve performance (object re-use > object creation). If we go that route, we'll be able to remove the Aether check once everything is refactored, making Vector work the same in player code as it does in the engine.

Added non-mutating methods for Vectors in player code

---

config.coffee

Reference: #3219
Also trim some trailing whitespace.

Fix dev server (`npm run dev`) on Windows, fixes #3219

---

app/styles/achievements.sass
app/views/core/AchievementPopup.coffee

This fixes #3243. Achievement notification animation now slides in from
off-screen left and then hides back to off-screen left.

Fix achievements notifications animation

---

app/templates/user/main-user-view.jade
app/views/user/MainUserView.coffee

Add level to user profile page

---

app/views/play/level/modal/HeroVictoryModal.coffee

This fixes #3294. Now checking earnedAchievementMap to determine if the achievement was previously earned.

Fix Earned Achievements Check

---

app/models/ThangType.coffee

This fixes #3264. Checks were failing in cases where no gold amount was set and tier was 0. Checks are now using existential operator to ensure null/undefined.

Fix isSilhouettedItem

---

app/models/Level.coffee

This fixes #3299. There seemed to be two cases causing the errors that I could find: Thangs that had no kind attribute and Heroes that weren't the player selected character. I filtered those cases out.
Is there a reason I shouldn't be relying on session? Is session.get('heroConfig') the best way to grab the currently selected character?
Anyway, when this fix breaks something else, let me know :wink:

Fix thangTypes filtering in serialize

---

app/styles/kinds/search.sass
app/templates/editor/level/table.jade
app/views/editor/level/LevelSearchView.coffee

This fixes #2732. The Level Editor level list now highlights the rows in which you are the person who last saved the level. The level list now also displays glyphicons to indicate watched/unwatched levels.
Since the levels list was hitting the base Handler, I added "watchers" and "creators" to the default PROJECTions there. Let me know if you'd prefer it handled differently.

Fix level list highlighted levels

---

app/locale/zh-HANS.coffee

Fixed a grammar mistake in Chinese on [this page](http://codecombat.com/contribute/diplomat) (Simplified Chinese Version).
Simply deleted "对" in "那就是全世界的人都对很喜欢CodeCombat".
Minor change, but important as it's on the home page of Diplomat.

fix Chinese grammar

---

app/styles/core/loading-error.sass

Fixed the issue #3456 
The 'Log In' sentence is now correctly centered in its place.

fix misaligned login

---

app/templates/play/level/tome/spell_list_tab_entry.jade

Fix the fullscreen-code button of issue #3400. 
Also fix the beautiful-code button for language “Javascript”. Both of the buttons’ appearance are now based on player’s level and the buttons start to show up at level 15 of player level. ^^

Fix the fullscreen-code button and beautiful-code button

---

app/styles/new-home-view.sass
app/styles/style-flat.sass
app/templates/base-flat.jade
app/templates/new-home-view.jade

For users from Belgium and The Netherlands, a special button is included on the home page (new-home-view) to allow them to buy codes through iDeal, through a dedicated web site.
Also, the email address in the footer is changed to this dedicated domain.

include iDeal offer for Dutch (nl) users

---

app/views/RequestQuoteView.coffee

This is due to `#flying-focus` taking up space at the bottom of the page. This solution is a bandaid. Ideally we have view-swapping logic that contains this type of thing and we just swap out views using one function. But since it just shows/hides some divs, we have to fix `#flying-focus` manually.

Fix teacher quote page having lots of blank space at the bottom (after submitting the form)

---

app/views/play/level/tome/SpellView.coffee

Fixes #3510.
As JavaScript is the only language supported by the beautifier, and [CodeCombat is in the process of converting things to while (true)](https://github.com/codecombat/codecombat/issues/3510#issuecomment-201965310), I guess adding this quick hack to the view's code should suffice for now. Hopefully, the non-standard `loop` construct will be removed from other languages before they receive beautifier support.
If this doesn't seem good, I can move  this hack to `aether.beautify`, where it is possible to perform this substitution in a language-aware way (i.e. inside Aether's JavaScript implementation's [`beautify` method](https://github.com/codecombat/aether/blob/418ccf2414c87fa23bf1edcc838266097a2df559/src/languages/javascript.coffee#L137)). Seeing as the `loop` construct is …

JS beautifier: fix loop construct, fixes #3510

---

app/views/TestView.coffee

So that the currently logged in user doesn't affect tests.

Clear window.me before running tests

---

app/styles/modal/subscribe-modal.sass
app/templates/core/subscribe-modal.jade

Subscribe modal: make the "parent" and "sale" buttons take only as much space as necessary and the "subscribe" button takes all the remaining space, this fixes #3526.
Here's how the new style looks:

Update subscribe modal's style to support i18n, fixes #3526

---

app/views/play/menu/GuideView.coffee

Fixes #2159. Use the Vimeo postMessage API to pause the help video when the guide view is hidden.

Pause help videos when guide modal is not visible

---

app/collections/CodeLogs.coffee
app/core/Router.coffee
app/models/CodeLog.coffee
app/schemas/models/codelog.schema.coffee
app/schemas/models/level_session.coffee
app/schemas/subscriptions/play.coffee
app/styles/admin/codelogs-view.sass
app/templates/admin/codelogs-view.jade
app/views/admin/CodeLogsView.coffee
app/views/play/level/PlayLevelView.coffee
app/views/play/level/tome/SpellView.coffee
scripts/analytics/mongodb/queries/playtime-over-10.js
server/middleware/auth.coffee
server/middleware/codelogs.coffee
server/middleware/index.coffee
server/models/CodeLog.coffee
server/routes/index.coffee
spec/server/functional/codelog.spec.coffee
sublime-project.json
vendor/scripts/spade.js

Spade: Per-input recorder to playback a user's coding session.
Implementation: Hooks into the SpellView's ACE and records passively. Compresses and saves this information to a user's session if the user has been on a level for more than 10 minutes, or they press the contact button. There is currently no way to play this back, but UTF16 strings should be properly recorded in a user's session under codeLog.
Currently includes Spade as a vendor script, but will be converted to a Bower module eventually.

Implements Spade functionality, and adds the sublime project file.

---

app/views/core/CreateAccountModal.coffee
app/views/courses/CoursesView.coffee

This does two things:
- Fix a regression where signing up from /courses with a class code would not really join the class, because application.router.navigate doesn't work if the path is the same but the query parameter is different.
- Autofill the class code in the signup form if you get there from a classroom join link (`/courses?_cc=...`)

Fix/improve Class Code handling in signup form

---

app/templates/core/create-account-modal.jade

Ref: #3729
`<button>`s are `type="submit"` by default.

Create account modal: don't open Facebook popup when pressing Enter in an input field, fixes #3729

---

app/styles/play/campaign-view.sass

Campaign view: fix level titles getting cut off

---

app/views/TestView.coffee
app/views/core/CocoView.coffee
app/views/core/ModalView.coffee
app/views/courses/TeacherCoursesView.coffee
test/app/factories.coffee
test/app/views/courses/CoursesView.spec.coffee
test/app/views/courses/HeroSelectModal.spec.coffee
test/app/views/courses/TeacherCoursesView.spec.coffee

This is for the Demo flow, so that playing the first level of the first course shows the HeroSelectModal before jumping into the game.
Note that CocoView.openModalView now returns the modalView it opened (instead of nothing), to make setting up listeners nicer.

Code review: Demo hero select

---

app/core/application.coffee
app/models/User.coffee
app/schemas/models/user.coffee
server/handlers/earned_achievement_handler.coffee
server/middleware/earned-achievements.coffee
server/middleware/index.coffee
server/middleware/users.coffee
server/models/Achievement.coffee
server/models/EarnedAchievement.coffee
server/plugins/achievements.coffee
server/routes/index.coffee
spec/server/functional/achievement.spec.coffee
spec/server/functional/user.spec.coffee

Have the users periodically check for new achievements and check if they've been earned, so that they automatically get awarded new achievements retroactively.
Also refactored the POST /db/earned_achievement endpoint and some related logic.
For now, the client DOES NOT actually check for achievements to award retroactively. I'd like to deploy the endpoint and test it through a dev proxy to ensure it works correctly.

Achievement updates

---

app/core/application.coffee
app/lib/LocalMongo.coffee
app/schemas/models/achievement.coffee
app/schemas/models/user.coffee
scripts/mongodb/migrations/2016-08-31-add-achievements-updated.js
server/middleware/achievements.coffee
server/middleware/users.coffee
server/models/Achievement.coffee
server/models/EarnedAchievement.coffee
spec/server/functional/achievement.spec.coffee
spec/server/functional/user.spec.coffee
spec/server/utils.coffee
test/app/lib/local_mongo.spec.coffee

* Clients check updated achievements as well as new ones
* Clients do not wait to keep checking
* Update achievement points along with everything else in EarnedAchievement.upsertFor
* Fix various bugs

Fix, update and enable achievement updates

---

.travis.yml
app/core/Router.coffee
app/core/utils.coffee
app/schemas/models/user.coffee
app/templates/account/israel-signup-view.jade
app/views/account/IsraelSignupView.coffee
config.coffee
server/models/User.coffee
test/app/core/utils.spec.coffee
test/app/views/account/IsraelSignupView.spec.coffee

Add a dedicated signup page for Israel. In the future, student and individuals creating accounts will be redirected to a separate site to sign up. This site will then redirect to `/il-signup`, providing information about the user through GET parameters, including email and an ID which will be saved, and all the student needs to do on our end is provide a username and password.

Add Israel signup view

---

server/routes/db.coffee

Also, schemas in the `x.schema.coffee` don't work, but I guess those never worked for the most part.  Should we make them work? @sderickson

Be a little more picky about requiring a user supplied string.

---

app/assets/dexecure-c167a5675c.js
app/assets/main.html

It should replace images that are needlessly large with smaller images automatically. It does it with ServiceWorkers and has a Cloudflare integration. It seems to work (tried on staging), but the only thing to watch out for will be possibly more aggressive caching–not sure.
In their words why it's better than alternatives:
* Support for various browser specific formats (WebP for Blink browsers, JPEG XR for IE11 and Edge)
* Automatic removal of metadata in images which can make the image up to 14% smaller if present
* Different images served for desktop and mobile devices adjusting the quality of the image accordingly. 
* Automatically inter-convert between various formats - PNGs are good for certain images, JPEGs for other kinds!
* Support for progressive JPEGs which leads to a much …

Try out Dexecure

---

app/locale/uk.coffee

Proposed translation of the web_dev section. "картинки" has been chosen intentionally as less formal than "зображення" and thus more children-friendly.

Update web_dev section in uk.cofee

---

app/collections/Achievements.coffee
app/schemas/models/campaign.schema.coffee
app/views/editor/campaign/CampaignEditorView.coffee
server/middleware/campaigns.coffee
server/models/Level.coffee
spec/server/functional/level.spec.coffee

* Before saving the campaign, load all missing levels and achievements so rewards are properly set
* Have individually loaded levels save and report changes properly
* Do not propagate campaignIndex from non-course campaigns to levels
* Do not set level properties to 'undefined', making it seem like they have local changes
* Update campaign indexes before saving the campaign
* Have fetching achievements by campaign handle odd level original values
* When a level is edited, propagate those changes to campaigns immediately

Tighten Campaign level denormalization and saving

---

app/locale/en.coffee
app/views/core/CocoView.coffee
app/views/core/ModalView.coffee
app/views/core/RootView.coffee

What could go wrong with this?
Test here: http://e0z6mg-codecombat-staging-codecombat.runnableapp.com/
You should be able to cmd+alt+click (on Mac) an element and open up GitHub right to where the element's translation is, if it has one.
@Imperadeiro98 @Bryukh is this helpful?

Experiment: cmd+alt+click a translated element to open the translation file to that element

---

app/models/User.coffee
app/views/play/level/HintsState.coffee
app/views/play/level/PlayLevelView.coffee

@differentmatt see anything wrong with this? Before, we weren't showing non-Intro/Overview specific articles nor general articles in hints, and this makes us do that.
Any other A/B testing stuff you wanted to remove? I left the events in.

End hints A/B test in favor of manual style and enable hints to show general articles

---

app/styles/play/campaign-view.sass
app/templates/play/campaign-view.jade
app/views/play/CampaignView.coffee
app/views/play/modal/PlayHeroesModal.coffee

Make the campaign editor arrow tips bigger, and actually align the arrows from end to tip at the center of the level circles.
Also added shift-s shortcut in the level editor to display level completion on the campaign edit screen.

Campaign stats colorer

---

app/core/Tracker.coffee
app/core/ViewVisibleTimer.coffee
app/schemas/subscriptions/misc.coffee
app/views/core/CocoView.coffee
app/views/core/SubscribeModal.coffee
app/views/play/modal/BuyGemsModal.coffee
app/views/play/modal/PlayHeroesModal.coffee
app/views/play/modal/PlayItemsModal.coffee
server/models/User.coffee

This adds analytics events for when premium features are viewed.
Notes about the structure:
CocoView will trigger an update to the timer, if it exists, any time the view is hidden/reappears/is inserted
Any view inheriting from CocoView can call `@trackTimeVisible()`, which creates the `viewVisibleTimer` which CocoView will manage automatically
Calling `@trackTimeVisible({ trackViewLifecycle: true })` will treat the view being open as the only feature being tracked for that view
If `trackViewLifecycle` is not set, the view must implement `currentVisiblePremiumFeature` which should return an object describing the premium feature currently in view, or `null` if none are visible. CocoView's `updateViewVisibleTimer` will call this function and update the timer if necessary.
- The view should …

Premium time tracking

---

app/views/play/CampaignView.coffee

Copy the special cases that existed in singular campaigns to the world select.

Sync up campaign and world selector level counts

---

app/templates/courses/teacher-classes-view.jade
app/views/admin/MainAdminView.coffee
app/views/courses/TeacherClassesView.coffee

So admins don't have to do a full spy on a teacher to check their classes. This is immediately accessible via the search results on /admin, but the main use will be attaching this link to the notes in Close.io.
Current caveats with this implementation, that could be worked around with a bit extra code if we want:
When you've clicked into a single TeacherClassView, the "My Classes" link will bring you back to YOUR classes, not the teacher's you were looking at.
The TeacherClassesView also does not have a clear visual indicator (other than the URL) that you're looking at someone else's classes.

Add button to quickly spy a teacher dashboard

---

app/views/teachers/TeachersContactModal.coffee
server/lib/closeIO.coffee
server/routes/contact.coffee

If a close.io lead can't be found to use to send the license request, send it via sendwithus instead.

Send license request via sendwithus when necessary

---

app/views/artisans/StudentSolutionsView.coffee

Apparently, previously esper was in the global namespace. No longer, so parsing JS solutions in the StudentSolutionsView has stopped working. This moves esper loading and parser creation to `initialize`.

Fix JS parsing for StudentSolutionsView

---

app/views/play/menu/InventoryModal.coffee

I added an exception in restrictedGear mechanic to let Rangers and Wizards equip their specific weapon on levels where 'cleave' is in requiredProperties.

Cleave req warriors only

---

app/locale/en.coffee
app/views/play/modal/LeaderboardModal.coffee
server/handlers/level_handler.coffee
server/models/LevelSession.coffee

Switch queries and indexes to do latest/all leaderboard scores instead of day/week/all. (We couldn't performantly do top-scores-from-last-day/week and were actually firing off all sorts of queries that ran for hours in our Mongo, long after a two-minute webserver request timeout.)
I'll delete the old index and remove the old day/week once this is up.

Fix leaderboard top scores performance

---

bin/coverage.js

Per issue #4335, this PR shaves off about 30s from the coverage tasks's runtime on my
local machine by using `coffee` to compile the entire directory, rather than the manual fs traversal preent before.
@duk3luk3 do you think it'd work on Travis CI?

Refactored out manual fs traversal in coverage.js

---

app/styles/modal/subscribe-modal.sass
app/templates/core/subscribe-modal.jade
app/views/core/SubscribeModal.coffee
test/app/views/core/SubscribeModal.spec.coffee

Forces either Stripe or Paypal, depending on whether the user is in a country with regional pricing. Removes the extra UI for the choice between the two.

Remove payment processor choice

---

package.json
server.coffee
server/commons/errors.coffee
server/middleware/healthcheck.coffee
server/routes/index.coffee
server_config.coffee
server_setup.coffee

Node doesn't handle timeouts well; by default it returns nothing and reports
200 after two minutes.
Add a connect timeout middleware to limit responses to one minute and
return 503. Also have production node instances continuously run
healthchecks and kill themselves if they fail repeatedly. `multicore.coffee`
will then spin up a replacement worker.

Add timeout request and a self-health checker

---

app/templates/admin.jade
server/commons/parse.coffee
server/middleware/payments.coffee
server/models/Payment.coffee
spec/server/functional/payment.spec.coffee

Add a search form to the admin page for searching PayPal transactions, and add an index for those transactions.

Add paypal payment search to admin page

---

app/core/Router.coffee

This defers merging the non-static page until after the locale finishes loading. The locale load was already initialized in `application.coffee`, but this gets the promise from that and waits for it to finish before merging the view (and most importantly, before rendering the dynamic view)

Fix translations not being used on first load

---

app/core/Router.coffee
app/core/api/levels.coffee
app/views/play/level/PlayGameDevLevelView.coffee
app/views/play/level/PlayWebDevLevelView.coffee
app/views/play/level/modal/HeroVictoryModal.coffee

Fetches levels based on the `original` in the Session instead of by URL query parameter.
Has some jank from bridging the supermodel+backbone/fetch API bridge, but it works. Let me know if there's a better way to bridge it in PlayWebDevLevelView especially.

Fix shareable links being broken by level rename

---

app/core/Router.coffee

Static page merging was breaking the `/?hour_of_code=true` redirect to `/play?hour_of_code=true`. This fixes it the same way it was already fixed for `/` -> `/premium`

Fix /?hour_of_code=true redirect

---

server/queues/scoring/scoringUtils.coffee

Logs an error instead of raising an unhandled exception.

Log an error instead of crashing when setting header twice

---

app/lib/world/box2d.coffee
app/lib/world/box2d_content.coffee
app/lib/world/world.coffee
app/lib/worldLoader.coffee
webpack.base.config.js

This changes the bundling of Box2D to be more similar to the old Brunch setup, by including it and executing it in the World bundle, separately from `lib/box2d` which sets up the global BOX2D_ENABLED when DB code requires `lib/box2d`.
The problem that was occurring before this change was that BOX2D_ENABLED was being set to `true` in the level editor, when it wouldn't have been set before. This caused the Collision system to do work it wouldn't have before when adding a Thang to a level, but it would error out because it wasn't set up enough to do so (missing a `collisionCategory`).
To have the box2d vendor script run, we need it at a root level of an entry point (which we achieve by having it be in an array entry point), but we still need to use `exports-loader` to get it set to `window` …

Fix Level Editor interactions with Box2D

---

package.json
webpack.development.config.js

Doesn’t do hot swap for CSS like brunch did, but reloads on build now. Probably buggy and gross but needed it today.

Quick stab at webpack auto refresh with webpack-dev-server

---

app/locale/en.coffee
app/models/CourseInstance.coffee
app/templates/courses/teacher-class-view.jade
app/views/courses/TeacherClassView.coffee
server/middleware/course-instances.coffee
server/routes/index.coffee
spec/server/functional/course_instance.spec.coffee

Adds a "Remove Course" button alongside bulk-assign "Assign Course" button.
Most of the code here is shared/pared down from the analogous functionality for adding, with only minor changes (mostly removing logic that's only needed for adding, like creating course instances or auto-enrolling them).

Add Remove Course button

---

app/locale/en.coffee
app/models/Classroom.coffee
app/templates/courses/remove-student-modal.jade
app/views/courses/RemoveStudentModal.coffee
server/handlers/classroom_handler.coffee
server/middleware/classrooms.coffee
server/middleware/prepaids.coffee
server/models/Prepaid.coffee
server/routes/index.coffee
spec/server/functional/classrooms.spec.coffee
spec/server/utils.coffee

When removing a student from a classroom, if the student is in no other classrooms:
- Inform the teacher that the license will be restored IF they have rights to the license
- Revoke the license
If the student is still in other classrooms, the old behavior still takes place — the student stays enrolled, and the teacher is told they will not get the license back.

Unenroll students on removal from last classroom

---

server/routes/file.coffee

- Server running on a non-US locale OS crashes while sending HTTP Last-Modified header. Tested on Windows 10 Korean.

[Fixed] TypeError: The header content contains invalid characters

---

app/core/Tracker.coffee
app/templates/play/modal/amazon-hoc-modal.jade
app/views/play/CampaignView.coffee
app/views/play/level/modal/HeroVictoryModal.coffee
app/views/play/modal/AmazonHocModal.coffee

Adds analytics events for AWS HoC buttons/links.
Please sanity check if any snowplow or schema things may break with this in production.
Please check if the values given to trackEvent make sense.
A single user may trigger any of these multiple times, so for the ones where we want unique counts we'll need to do aggregation with that in mind.

Add AWS HoC tracking events

---

app/lib/LevelLoader.coffee
app/lib/simulator/Simulator.coffee
app/lib/world/world.coffee
app/views/ladder/LadderTabView.coffee
app/views/ladder/SimulateTabView.coffee
app/views/play/level/PlayLevelView.coffee
app/views/play/level/tome/CastButtonView.coffee
server/handlers/level_handler.coffee
server/lib/simpleCache.coffee
server/queues/scoring/getTwoGames.coffee

Random game simulation will now never play you against yourself.
It will often target an opponent near your skill level for better games.
It will often play one of your games so that you can get faster results for games you care about if you are simulating.
Improved simulation display of what's going on while simulating.
Added a simple cached fallback for calculating leaderboard ranks based on ladder score distributions we may already have cached, and reduced the max query timeout before falling back to that.

Improve simulation sampling

---

app/locale/cs.coffee

There should be only one letter "e" in czech translation of "more"

Minor typo fix in cs.coffee

---

app/styles/courses/teacher-class-view.sass
app/templates/courses/teacher-class-view.jade

They didn't work because those bubbles have no text, so the links had
zero width. Refactored the progress bubbles to be themselves links;
this has the added effect that the click area is larger.

Fix assessment tab student code links in TeacherClassView

---

app/core/application.coffee
app/lib/LevelBus.coffee
app/lib/SolutionConceptTagger.coffee
app/lib/coursesHelper.coffee
app/locale/en.coffee
app/locale/locale.coffee
app/models/Classroom.coffee
app/models/LevelSession.coffee
app/schemas/models/campaign.schema.coffee
app/schemas/models/classroom.schema.coffee
app/schemas/models/level.coffee
app/schemas/models/level_session.coffee
app/styles/courses/student-assessments-view.sass
app/styles/courses/teacher-class-view.sass
app/templates/courses/student-assessments-view.jade
app/templates/courses/teacher-class-view.jade
app/templates/play/campaign-view.jade
app/templates/teachers/hovers/progress-dot-single-student-level.jade
app/templates/teachers/teacher-course-solution-view.jade
app/views/courses/StudentAssessmentsView.coffee
app/views/courses/TeacherClassView.coffee
app/views/editor/level/settings/SettingsTabView.coffee
app/views/play/CampaignView.coffee
app/views/play/level/LevelGoalsView.coffee
app/views/play/level/tome/Spell.coffee
bower.json
server/models/Classroom.coffee
server/models/Level.coffee
server/models/LevelSession.coffee

Add `codeConcepts` to level sessions. This lists all concepts used in player code, including default code. Does not retroactively apply them to existing sessions, and only works with Python and JavaScript. For `'open-ended'` assessment levels, the teacher class assessment tab bubbles show which concepts were used in the student code, and for other levels they list the primary concept for that level.
Also fixed a couple bugs found along the way:
* Fix "Last Played" string in bubble
* Fix student assessment page if they are in another
classroom w/out assessments
Still TODO:
* Confirm wording, then translate
* Consider what to show in assessment tab when a course does not have assessments

Concept tagging

---

app/core/utils.coffee
app/templates/teachers/hovers/progress-dot-single-student-level.jade
app/views/courses/StudentAssessmentsComponent.vue
app/views/courses/StudentLevelProgressDot.vue
server/middleware/course-instances.coffee
test/app/core/utils.spec.coffee

Only return next assessment level if it’s incomplete and immediately
following current level.
Next practice level takes precedence over next assessment level.
Add automated tests for utils.findNextAssessmentForLevel
Fixing goalStates null check in student assessment progress UI.

Update find next assessment level logic

---

app/models/ThangType.coffee
server/commons/Handler.coffee

This commit makes it so when you go to [The Last Guardian](https://codecombat.com/editor/level/last-guardian),
the artillery sprite correctly displays. This may also fix other
prerendered sprite sheet issues. Two changes:
1. Have the names endpoint return spriteType so
`getPrerenderedSpriteSheet` can use it to figure out what sprite sheet
needs to be rendered.
2. Don't let a lack of `raw` property get in the way of searching for
the right spritesheet to use.

Fix artillery not rendering in Last Guardian

---

app/lib/Angel.coffee
app/lib/God.coffee
app/views/play/level/tome/ProblemAlertView.coffee
app/views/play/level/tome/SpellView.coffee

The changes in Angel.coffee should be fine; we just weren't handling the runtime errors from user code.
The change in SpellView... why did we not have the runtime version of the `aether` having the error before, or how do runtime errors still work in normal game modes? Not sure if that will change any behavior anywhere else, although in my tests it didn't. Might be worth a little more QA comparing various error behaviors.

Abort and show code errors while in game dev test level

---

app/core/Tracker.coffee
test/app/core/Tracker.spec.coffee

Also refactored event guard conditions while I was at it; the logic was getting too hairy. I think this is correct.
@sderickson question for you:
```coffeescript
shouldBlockAllTracking: ->
return me.isSmokeTestUser() or window.serverSession.amActually
```

Don't track events when using serverSession.amActually

---

app/locale/pt-BR.coffee

Improved some translations but the main change was on the mixing translations for the word `subscribe`.
I believe the best translation for `subscription` would be _assinatura_ instead of _inscrição_. The former is used in magazine and cable TV subscriptions contexts, for example. I found that both words were being used interchangeably and I decided to change everything to _assinatura_.

Update pt-BR.coffee [subscribe]

---

app/core/utils.coffee
test/app/core/utils.spec.coffee

Correctly skip over assessments when needing a practice level but one
isn’t available.

:bug:Fix utils.findNextLevel assessment bug

---

app/core/utils.coffee
app/models/ThangType.coffee
app/views/core/CocoView.coffee

IE11 does not support crossorigin img attribute within a canvas element.

:bug:Fix IE11 level background raster image loading

---

app/lib/LevelBus.coffee
app/lib/LevelLoader.coffee
app/lib/LevelSetupManager.coffee
app/models/Level.coffee
app/schemas/models/level.coffee
app/views/editor/level/settings/SettingsTabView.coffee
app/views/ladder/MyMatchesTabView.coffee
app/views/play/level/PlayLevelView.coffee
app/views/play/level/tome/CastButtonView.coffee
app/views/play/menu/GameMenuModal.coffee
server/middleware/levels.coffee
server/models/Level.coffee

1. Add ability to configure `type: "hero-ladder"` levels to use specified hero/equipment, instead of having to hard-code that.
2. Configure mirror match levels via level property instead of hard-coding.
3. Start to add level passwords for restricted level preview.
I need some help on the third part. I am not sure the best way to restrict the `password` property from ever leaving the server except when requested by an admin. See [work in progress here](https://github.com/codecombat/codecombat/commit/1179161b424024e5aa7cfde6e2ec161c66a853c1#diff-13182bfff6e125a033722e291146313cR70). This is needed to control access to arenas before tournaments begin to only our trusted playtesters to whom we've given a password.

Ladder configuration

---

app/lib/world/world.coffee
app/schemas/models/campaign.schema.coffee
app/schemas/models/level.coffee
app/views/editor/level/settings/SettingsTabView.coffee
server/models/Level.coffee

- Health is raised if below `recommendedHealth` 
- Added `maximumHealth` to schemas.

Implement Min Health Restriction

---

app/templates/courses/teacher-courses-view.jade
app/views/teachers/TeacherCourseSolutionView.coffee

Instead of a single `HTM`L guide for both JS and Python `web-dev-2` classes, now there are two pages.

Clarify numbering to web dev 2 solutions guide

---

app/views/play/level/modal/CourseVictoryModal.coffee

We were saving a level session and loading a collection of level sessions that included that session at the same time, causing changes to be reverted locally due to supermodal caching behavior.
Problematic session loading sequence:
Session loaded from supermodel via LevelLoader
levelSessions.fetchForCourseInstance async via supermodel
LevelBus saves session.state.complete = true immediately
LevelBus save completes
SuperModel.registerCollection updates the cached session model
CourseVictoryModal.onLoaded fires session.state.complete = false again
Fixing by moving level sessions fetch in course victory modal to onLoaded, and no longer saving level sessions in supermodel.

:bug:Fix unshown victory achievements

---

app/lib/LevelLoader.coffee
app/lib/surface/Lank.coffee
app/lib/world/world.coffee
app/models/User.coffee
app/views/play/level/PlayLevelView.coffee

- Had local health bar anomalies. Suspect caching.
- The cache seemed to be setting maxHealth lower.
- Tested using proxy and everything worked.
- Worked locally after clearing cache.
Bug: Only clamped health if level type was `course`. Most have type `hero`. The fix injects additional data into the `level` data object to inform when to clamp.

Fix recommendedHealth

---

app/views/play/SpectateView.coffee

This `console.error` highlights an important precondition that must be satisfied for Spectate Mode to work.
May help uncover and diagnose other Spectate bugs which are intermittent.

Spectate View precondition error log

---

app/views/play/level/tome/ProblemAlertView.coffee

Fixes issue #4651
- Let `marked` sanitize the input entirely.

Markdown escaping moved entirely into marked

---

app/views/play/level/GameDevTrackView.coffee

Without this check the transpiled coffeescript can check the length of undefined in the for statement.

Fix Tracked Properties Undefined

---

app/templates/courses/teacher-class-view.jade

Enforce readonly property of input fields.
Remove `form-control` class because it changes the cursor to a `not-allowed` cursor.

Teacher class code and class url made read only on Teacher Dashboard.

---

app/vendor.js

Polyfill for String.prototype.includes
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Polyfill

Add polyfill for 'includes' to support IE11

---

app/lib/coursesHelper.coffee
test/app/lib/CoursesHelper.spec.coffee

Fix required the number of levels in the user state to be compared with the number of required levels in the course.
Otherwise a user could have a single completed level incorrectly marking them as completing the course.
Also tested against a teacher with a large classroom. This seems to fix all of the wrong progress on the account.

Fix classroom course progress dots

---

test/app/core/locale.spec.coffee

Check uniformity across translation files.
Helps prevent the bug caused when the parent key is accidentally left commented in a translation file.
I.e.
```
heading: xyz
```
should be caught by these tests while the following passes the tests.
```
landing_page:
heading:xyz
````

Add locale tests

---

app/lib/surface/Lank.coffee

Sometimes "layer" component loads later and @layer?.name is undefined for the first frame and it's enough for tweening

Fixed tweening floors.

---

app/lib/coursesHelper.coffee
app/templates/courses/teacher-classes-view.jade
app/templates/teachers/hovers/progress-dot-whole-course.jade
test/app/lib/CoursesHelper.spec.coffee

Calculation was number of students that completed the course divided by total students.
Now completion percentage is the progress of the entire class by counting all the completed levels against summation of all required levels per student.
If the class has one student in a course with 10 required levels. Prior to this change the percent completion would change from 0% to 100% immediately when the student completes all required levels.
With the change the percentage will improve gradually as students complete required levels.
Once the student as completed 1 level, the new percentage will be 10%.
With two students there are now 20 required levels between them. If one student completes a single level, the total class progress is only 5% or `1/20`.

Make percentage level completion more granular on progress dots.

---

app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee

Triggers when the `CreateAccountModal Teacher TeacherRolePanel Continue Success` google analytics event is triggered.

Facebook Pixel teacher conversion tracking added

---

app/views/play/CampaignView.coffee
app/views/special_event/HoC2018InterstitialModal.coffee

Adds an `onDestroy` callback to the modal allowing it to start the music once it has been destroyed.

Refactor allowing modal to start music

---

app/core/Router.coffee
app/core/utils.coffee

Upgrading to Backbone 1.1.1 for https://github.com/codecombat/codecombat/commit/320150f56740f225e40b1392b202e31fb1ece6e8 introduced different routing param behavior.  Query strings are appended to the routing params, which messes up our use of optional wildcards.
To fix, we strip those back out in our routing `go` method which should get us back to the expected behavior in general and leave @shubhi1092's fix in place.

Fix verifier dev=true mode

---

app/views/play/level/PlayGameDevLevelView.coffee

Space bar can be used as a control in the game, so preventing its default behavior of scrolling down the page in PlayGameDevLevelView.

Prevent space bar from scrolling the page

---

app/views/play/CampaignView.coffee

In the class code entry text box in campaign view for anonymous players, allow 'enter' key to submit the class code.

Allow 'enter' to submit class code on CampaignView

---

app/core/Router.coffee
app/views/HomeView.coffee

Upgrading to Backbone 1.1.1 for https://github.com/codecombat/codecombat/commit/320150f56740f225e40b1392b202e31fb1ece6e8 introduced different routing param behavior.  Query strings are appended to the routing params, which messes up our use of optional wildcards.
This URL routing pattern is broken and we shouldn't use it anymore:
'/somepage': go('SomeView')
'/somepage/:param1': go('SomeView')
Because, query strings on the base route will be passed in as the optional param (param1) instead.
Instead, use a single route with optional param via parenthesis:
'/somepage(/:param1)': go('SomeView')
Did not update /play CampaignView routing because it was unclear what Facebook integration would break and it's not quite broken, just very fragile.  Can't use query strings on world map selector …

Fix verifier dev=true mode (2nd attempt)

---

app/locale/ja.coffee
test/app/core/locale.spec.coffee

A common error is when a diplomat forgets or accidentally doesn't remove the comment from the parent key of the translation.
I.e.
```
b: "translation"
```
When it should be:
```
a:
b: "translation"
```
When `a` is commented, `b` becomes attached to the wrong parent key. This test catches this issue.
A slight complication introduced by this test is that it will become harder to delete translations from the `en.coffee` file, requiring the translation to be deleted across all languages to make this test pass again. I think this is a fair trade off as more errors are introduced via the translation process than removing translations. 
There is also a translation fix in this pull request.

Reduce diplomat comment errors

---

app/styles/account/account-prepaid-view.sass
app/templates/account/prepaid-view.jade
app/views/account/PrepaidView.coffee

Requirements was to make this page behave better on phones.
There is a meta tag in our `layout.static.pug` that sets viewport to `width=1024`. This needs to be overwritten to allow the page to scale on smaller screens. This ended up being the cleanest way I could think of doing this without risking side effects.
If we want this page to be a better experience it requires a re-design & rewrite.

Responsive /account/prepaid page

---

app/styles/modal/subscribe-modal.sass

There wasn't whitespace at the bottom of the dialog, so this change adds the whitespace.
Before:
After:

Add margin to the bottom of the subscribe dialog

---

app/core/social-handlers/GPlusHandler.coffee
app/styles/modal/auth-modal.sass
app/templates/core/auth-modal.jade

Google+ APIs are being deprecated and will be shut down on march 7, 2019. Hence, replacing them.
Also, we have been using google+ platform sign-in(gapi.auth) instead of google sign-in(gapi.auth2), so replacing that as well.

Replace g+ API with google api

---

app/models/LevelSession.coffee

LevelSession.submitted property shouldn't be used for level completeness in classroom dashboards.  More applicable to arena ladder logic.

:bug:Fix student level complete on teacher dashboard

---

app/lib/surface/Lank.coffee

It's possible that a Lank has previousEffectNames and the thang doesn't have effectNames anymore (GD levels with dynamical components).

Fix for effects when objects are reused

---

app/lib/coursesHelper.coffee
app/models/Classroom.coffee

Checked the following test cases manually and cases in the comments on Asana.
The teacher calculation remains unchanged and still shows 100%.
The student 18/19 correctly displays as 18/18 as ladder is not a required level.
This is correctly displayed on the /students page as well as the world map for the student.

Exclude ladder level on both student and teacher completeness check

---

app/views/play/modal/PlayHeroesModal.coffee

This code isn't required anymore and we can remove it.
In the case that a hero pose isn't provided, the rendering code is using non updated libraries and throws a createjs error `spriteStage` isn't defined.
I believe this is an old implementation of Lanks and Layers that doesn't exist anymore.
This change therefore provides a clearer error message if a hero is added without a `poseImage`.

Remove unnecessary code in hero pose image

---

app/views/ladder/LadderPlayModal.coffee

Fix for #5157 
Removes Java from the arena drop down menu as it's not currently supported.

Remove Java from the arena language options

---

app/templates/home-view.jade

The text used in the statistics overview is duplicated. 
The reference to the first section was used twice. I just updated it to use the third section text instead.

Fix: Duplicated home page text

---

app/templates/admin/outcome-report-result-view.jade

The outcomes reports would only show the overview of the class, the classes section, if there was custom markdown manually added to the report. 
Always show the classes section regardless of whether the markdown was present or not. To keep the report consistent when generated with/without the custom markdown, the classes section was moved to the left.

Fix: Always show classes section on outcomes report

---

app/styles/style-flat.sass

Very long names cause the "My Account" dropdown menu to shift off the users screen making it hard it impossible to read buttons. 
Set a max width and set overflow-x.

Dropdown menu will truncate very long names

---

app/templates/base-flat.jade

Leave as is when not logged in.
Before:
After:

Fix language dropdown positioning when logged in

---

package.json

We want a standard to follow for writing JavaScript. There should be adequate tooling, low config and some benefit to the style we choose.
We've chosen [standardJS](https://standardjs.com/), or JavaScript Standard Style. This is a zero config tool that formats and lints our code. standard also has editor extensions, plugins and a CLI.
This PR introduces a new npm script: `npm run standard` that is detailed below.
This script will format your code and print linting errors to the console.
**It is recommended that you install an editor [plugin](https://standardjs.com/#are-there-text-editor-plugins) to get a much better experience** as this script runs slowly.
The commands were tested on files ending with `.js` and `.vue`.
The plugin `eslint-plugin-script-tags` is required to use standard on …

Add StandardJS tool

---

app/styles/user/certificates-view.sass

The certificates have top padding making room for the nav that isn't required.
This is causing certificates to not fit on a single landscape page.
Remove the padding-top from the `.style-flat` div on the Certificates View.
On manual testing the page was still leaking off the page. This is fixed with the `print` media query additions.
Manually tested on Chrome and Firefox. Firefox adds white space which can't be removed on my computer. I believe this fixes the issue on Chrome and improves printing on other browsers by reducing top white space.

Fix printing certificates on landscape pages

---

app/core/api/users.coffee
app/models/User.coffee
app/styles/admin/administer-user-modal.sass
app/templates/admin/administer-user-modal.jade
app/views/admin/AdministerUserModal.coffee

We want to give our admins the ability to grant School Administrator access through the admin modal dialog. This requires a new search, state management before and after storing user ID's in the db and interacting with the new API endpoints in https://github.com/codecombat/codecombat-server/pull/57/files.
- How would you manage state in this situation? It quickly grew complex, and the current structure is more a result of debugging and pulling together all the pieces - rather than by intentional design. 
- What is a good approach for testing this? My focus has been on understanding the systems, interactions and data models. Now that the pieces are interacting the expected way, could this be done in a more testable way?

School admin access granting for coco admins

---

app/core/social-handlers/FacebookHandler.coffee

Facebook API v2.8 is being deprecated.
Bump the version number.
See referenced server PR for additional details as this change depends on the server.

Upgrade Facebook API

---

app/templates/base-flat.jade

change 京ICP备16061132号 to 京ICP备19012263号 with href to MIIT of China

modify China ICP info

---

app/lib/surface/Surface.coffee

For some levels we need track mousemove event.
If world's parameter `trackMouseMove` is true then we send all mousemove events to realtTimeInputEvents which is processed in Systems.UI

Add mousemove event transferring in game systems

---

app/lib/surface/Surface.coffee
app/lib/world/world.coffee

We need to control the camera (bounds, target, zoom) from the game codebase.
Added world's method to trigger client code events from the world lib.
Unbound the camera from the hero thang on game-dev levels (we don't hero there).

Camera control from the game

---

app/templates/courses/teacher-class-view.jade
app/templates/teachers/teacher-student-view.jade
app/views/teachers/TeacherStudentView.coffee

There was still a link into student pages that both school admins and teachers were seeing. Going to this student page for a school admin would simply display an empty page. 
Remove the link, and give a more useful "Not available" message to the school admin that somehow gets to a student page.

Restrict student page links for school admins

---

app/views/admin/AdministerUserModal.coffee

The school admin checkbox was not responsive because the local `user` was not updated after the `put` call to the server. 
Modify the local permissions of the user model after receiving the `res`.

Fix school admin checkbox responsivity

---

app/templates/courses/teacher-class-view.jade
app/views/courses/TeacherClassAssessmentsTable.vue
app/views/courses/TeacherClassView.coffee

There are more links from teacher pages and sub components that should be disabled for school admins.
Introduce `readOnly` through props for the sub components and conditionally render remaining links.

Prevent additional student links for school admin

---

app/views/admin/AdministerUserModal.coffee
app/views/school-administrator/teachers/SchoolAdminTeacherListView.vue

We were not grouping teachers by `No school found` and the table headers were not `th` but rather `h6`, popping above the table.
Add default `No school found` and properly use `th`.

NCES grouping fixes

---

app/templates/courses/teacher-classes-view.jade

Pug/Jade does not consider spacing in the beginning of a text block like `| My text`.
Added `&nbsp;` to force spacing in the rendered HTML.

Tiny whitespace fix for school admin notification

---

app/core/initialize.coffee

Some third party vendors using CodeCombat are seeing errors. This is due to our code not recognizing that it's in production.
Add an additional condition to the problem area. Instead of checking for `codecombat.com` domain. Instead check for the lack of `localhost`.
We still want admins to see errors.

Don't throw errors in production under other domain names

---

app/styles/style-flat.sass
app/templates/base-flat.jade

When the CodeCombat logo is sharing the navigation with another logo the nav resizes and thus covers the teacher dashboard.
The nav must be 70px tall, and a third party logo causes the nav to have a height of ~90px.
Ensure that partner logos are set by height instead of width.
The issue was fixed for CodeNinja's logo but also fixed the Tarena logo.
Because we shrink the CodeCombat logo when it's with a partner logo, I shrunk it slightly more to compensate for the slightly smaller third party logos. It's also been centered vertically.

Fix navigation height with Partner logo

---

app/models/User.coffee
app/schemas/models/level.coffee
app/views/play/CampaignView.coffee

- Adding a new level type for "intro"
- Allowing only admins to view voyager dummy campaigns in edit mode.
- Dummy campaigns will be created by the script on the server side - https://github.com/codecombat/codecombat-server/pull/65

Voyager world map placeholder data support

---

app/styles/admin/admin-outcomes-report.sass
app/styles/teachers/teacher-course-solution-view.sass

Outcomes report and printing course guides had excessive top padding.
The cause was due to the redesigned homepage nav bar spacing appearing on the printable versions of these pages.
Thus as these pages hide the nav bar on printing we must also set the padding to 0.
We want the outcome report to always have a `padding-top` of `0` as the preview view is the printable view.
And we want the teacher course page to only have a `padding-top` of `0` when printing as there is a nav bar when not in print view.

Remove top padding from style-flat in printable pages

---

app/core/Tracker.coffee
app/core/auth.coffee
app/locale/en.coffee
app/models/User.coffee
app/schemas/events/identify.json
app/schemas/models/user.coffee
app/templates/base-flat.jade
app/templates/home-view.jade
app/views/HomeView.coffee
app/views/core/CreateAccountModal/BasicInfoView.coffee
app/views/core/CreateAccountModal/CreateAccountModal.coffee
app/views/core/CreateAccountModal/teacher/SchoolInfoPanel.coffee
app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee
app/views/core/RootView.coffee
app/views/courses/TeacherClassesView.coffee
static-mock.coffee

- Adding `testGroupNumberUS` to the users belonging to `united-states` since this test is only for US customers.
- Dividing users by `testGroupNumberUS` into 40%, 40%, 20% for UI variation A,B,C respectively.
- Added UI variation on the homepage for test group A,B,C.
- Added support to track certain events for a/b test results, i.e. their events will have a label pointing to the test group that triggered the event.
Also, includes a minor change to open the teacher signup modal instead of the generic signup modal when clicked on `Sign Up` button from `For Teachers` section on the homepage.

Homepage A/B testing

---

app/schemas/models/user.coffee

Fixes parsing error causing schema definition to be incorrect

Remove commas from stats definition in user schema

---

app/views/play/level/modal/CourseVictoryModal.coffee

@wjllance can you test this to see if it works?
The idea is that when we did #5227 to make it so that Tarena hackathon players play in the global leaderboard, we nullified the `leagueID`, which passed through all the way to the CourseVictoryModal, which assumes it has a `courseID` or `courseInstanceID` but doesn't. So, if we don't have those, in China, for now, we can fill in the values we would have had.

Additional Tarena ladder course ID workaround to go with #5227

---

app/views/teachers/MarkdownResourceView.coffee

Our markdown links that jump to the top of the page were pointing to an outdated `#logo-img` anchor, and were not jumping anywhere.
There was no natural place to link this to, because we already have `href` set for this image at the top of the page in our nav bar. Instead, replace with a simple `href="#"` so it always jumps to the top.

Make markdown links always jump to the top

---

app/locale/en.coffee
app/styles/courses/courses-view.sass
app/styles/courses/teacher-classes-view.sass
app/templates/courses/courses-view.jade
app/templates/courses/teacher-classes-view.jade
app/views/courses/TeacherClassesView.coffee

Change adds a temporary banner to run over teacher appreciation week at the route `/teachers/classes`.
I reuse logic that has been used before, and clean up some of the Hour of Code banners that we used to use.
The paidTeacher check is lifted from the TeacherCourseSolutionView (These two lines):
https://github.com/codecombat/codecombat/blob/85bec7768d1bef3f25c7968f15f2d75f8d8a458e/app/views/teachers/TeacherCourseSolutionView.coffee#L42
https://github.com/codecombat/codecombat/blob/85bec7768d1bef3f25c7968f15f2d75f8d8a458e/app/views/teachers/TeacherCourseSolutionView.coffee#L58
CSS changes are scoped to the `announcement` id, and thus safe to change.
I ran manual tests on my local teachers.
Paid teachers don't get the banner as per design.
Unpaid teachers do get the design.
User must be in …

Teacher appreciation banner

---

app/views/teachers/TeacherStudentView.coffee

tl;dr: `super` renders the page. Move logic after the super call to ensure page is rendered when we try to jump to the fragment heading.
For full repo of bug report see linked ticket.
I was able to reproduce the issue on Chrome but not Firefox.
The issue seems to be the page not being rendered when the fragment `if` condition is being run. 
~The change forces the `@updateSelectedCourseProgress`method to run after other synchronous and async methods earlier in the event queue. Ensuring we can jump to a fragment that has been  rendered.~ (retracted after second commit)
`CocoView.coffee`'s `onLoaded` method calls [`@render`](https://github.com/codecombat/codecombat/blob/dfe2860fcb4768462cc38fa4f947a558dc2af4c7/app/views/core/CocoView.coffee#L231) synchronously. This occurs when `super()` is …

Anchor links for View Student Code broken in Student Profile View

---

app/lib/surface/Surface.coffee

In some game dev levels when we use camera zoom, mouseClick control activates dragging and that's annoying for players.
UI system parameter to disable cameraDragging for certain levels.

Added the parameter to disable camera dragging in some levels

---

app/views/courses/EnrollmentsView.coffee
test/app/views/courses/EnrollmentsView.spec.coffee

Update logic to determine when a starter license is displayed.  Starter license will now display when:
- The teacher is low priority (selected 1 - 10 students in class)
- The teacher has never had a full license shared with them
- The teacher has never purchased a full license
- The teacher has never purchased a starter license or the teacher has purchased a starter license within the last two months

Starter license banner display change

---

app/core/Tracker.coffee
app/locale/en.coffee
app/models/User.coffee
app/templates/base-flat.jade
app/templates/home-view.jade
app/views/HomeView.coffee
app/views/core/CreateAccountModal/BasicInfoView.coffee
app/views/core/CreateAccountModal/CreateAccountModal.coffee
app/views/core/CreateAccountModal/teacher/SchoolInfoPanel.coffee
app/views/core/CreateAccountModal/teacher/TeacherRolePanel.coffee
app/views/core/RootView.coffee
app/views/courses/TeacherClassesView.coffee

Ending A/B test on the homepage and replacing with the test winner - https://app.asana.com/0/654820789891907/1120659490583466
Left the support to implement and track a/b test in the future. We can use the user property `testGroupNumberUS` to implement a/b test for US users, or `testGroupNumber` for worldwide users, and use `trackABResult` to track the results in google analytics.

End a/b test on homepage

---

app/views/courses/TeacherClassView.coffee
test/app/views/teachers/TeacherClassView.spec.coffee

Prior to this change, `calculateProgressAndLevels` method is called in response to all sorts of state changes. This is problematic as `calculateProgressAndLevels` is expensive.
The outcome is operations on large class sizes becoming unreasonably slow.
Adding or removing a course from a student can cause progress to be calculated > 20 times. This leads to a lot of repeated work.
An alternative way of fixing this issue is streamlining the various call sites. Identifying wasteful calls and refactoring them.
I chose not to pursue this as certain `calculateProgressAndLevels` calls had been committed due to historic UI bugs.
Hence I opted to keep the call sites the same, instead debouncing repeated calls.
This means that the functionality should be the same but with much less work.
I manually …

Speed up adding and removing courses from large classroom

---

app/core/api/users.coffee
app/core/auth.coffee

Setting country and geo for returning users so that any code paths that don't set the country/geo when the user is created can be covered.
Related server PR: https://github.com/codecombat/codecombat-server/pull/79

Set country and geo for returning users

---

app/core/api/cinematic.js
app/core/api/thang-types.js
app/views/CinematicCanvas.vue
app/views/CinematicViewComponent.vue
app/views/editor/cinematic/CinematicEditorComponent.vue
app/views/play/cinematic/CinematicLankBoss.js
app/views/play/cinematic/Loader.js
app/views/play/cinematic/cinematicController.js

Brings functionality back to Cinematics.
I feel there are some better abstractions and refactorings that can be done but unsure how to proceed for the moment.
I feel that the design is sufficiently decoupled that the improvements could be added later.
- Backgrounds can be set between shots
- Background objects can be placed.
- Background objects can be removed with a trigger delay.
- Player Hero can be shown as the left or right character.
- Add Cinematic View to the Cinematic Editor for easier testing.
Depends on the changes from #5282 
This was tested manually as I can't think of how to test the side effects without creating some kind of Cinematic Verifier environment. To assist with rapid feedback the cinematic editor environment improvement at least allows you to immediately view  the …

Cinematic Lank Boss Priority Functionality

---

app/schemas/models/cinematic.schema.js
app/schemas/selectors/cinematic.js
app/views/play/cinematic/CinematicLankBoss.js
app/views/play/cinematic/DialogSystem.js
test/app/models/Cinematic.spec.js

Adds text animation length property to the Cinematic schema and the ability for an action to be played over the dialog bubble animation.
This feature is relatively minimal as we're leveraging `Actions` built into Lanks.
Currently the character Lanks can't do any other animation that would be interrupted by talking.
Thus we assume  that after the talking animation concludes the Lanks go back to being idle.
1. Navigate to `/editor/cinematic`
2. Make a new cinematic.
3. Create a new shot by clicking  on `shots` and the `+`.
4. Create a setup shot and a left character.
5. Click on the dialog nodes.
6. Create  a dialog node.
7.  Set the text property.
8. Set the textAnimation property.  I  recommend `build` or `move`.
9. Click test Cinematic on the top right.
10. Click on the `Enter` button …

Cinematics Talking Animation

---

app/templates/courses/teacher-class-view.jade

School admins were still seeing some controls that had no use for them.
Conditionally render controls so school admins have a clearer view.
- Without the useless checkbox, it looks very sparse and the student name has no padding on the left side. Would it be useful to go deeper into conditional rendering here and add in some padding too?

Remove useless controls for school admins

---

app/schemas/selectors/cinematic.js
test/app/models/Cinematic.spec.js

The clearDialog attribute has the wrong default value. It is far more common to clear the dialog than leave it.
Update the selector to return `true` by default. Tests are also updated to reflect the change.

ClearDialog cinematic property default should be true

---

app/styles/editor/thang/colors_tab.sass
app/templates/editor/thang/colors_tab.jade
app/views/editor/thang/ThangTypeColorsTabView.coffee

This is a small step in the direction and design of Character Customization, via color tinting.
This small change introduces a way to define and test colors on predefined Thang groups within our Thang color editor.
This modification is entirely cosmetic, and kept minimal in order to create a stepping stone for more character customization features.
The panel presents some hard coded hair and skin colors that can be applied once hair and skin color groups have been defined on a given ThangType.
This panel is at the  bottom of the  Colors tab within `/editor/thang`. I've hard coded some colors which will eventually be fetched and saved from the database.
If you have defined a color group for `skin` or `hair`, clicking these colors will apply them to the thang. …

Add initial Color Tinting Panel to Thang editor

---

app/schemas/models/tint.schema.js
app/schemas/models/user.coffee

This is a stepping stone for the server work which will present end points for these schema additions.
We are adding a new collection that will store valid color tints for the ThangType color groupings that we define in the editor.
Then the player will be able to choose a valid tint. The server will use the `tints` collection to validate the user's decision.

Color customization schema

---

ozaria/engine/cinematic/CinematicLankBoss.js
ozaria/engine/cinematic/Loader.js
ozaria/engine/cinematic/cinematicController.js

We need to be able to scale Lanks. Like the background object, and characters.
We had 3 different ways of moving lanks.
- An animated movement, that was called `moveLankCommand`.
- An instant move, `moveLank`.
- Move background called `setBackground`, which could position the background between scenes. And supported scaling.
As the schema defines the same thang object between the 3 lanks, it is possible to consolidate this functionality into a single method.
Simplify the logic into a single method `moveLankCommand` that handles an instantaneous move as an edge case (when milliseconds is 0).
Also fixed the bug  where a user could have never selected a hero and thus crashed the cinematic. Instead a default hero is chosen.

Refactor CinematicLankBoss to consolidate move commands

---

app/schemas/models/tint.schema.js
app/schemas/models/user.coffee

When saving tints it's not precise enough to store a list of colors.
Improve the schema to force tint objects to contain a slug, referencing the origin of the tint color. And then store color configs related to that tint.
A valid customization schema on the user now looks like so (taken from server tests):
```
tints: [
{
slug: 'hair',
colorGroups: {
hairHighlight: { hue: 0.1, saturation: 0.2, lightness: 0.3 },
hairBase: { hue: 0.3, saturation: 0.1, lightness: 0.01 }
}
}]
```

Improve the player customization schema

---

app/core/Router.coffee
app/core/ozariaUtils.js
app/core/vueRouter.js
app/models/User.coffee
app/schemas/models/interactives/common/interactive_types.schema.js
app/schemas/models/interactives/interactive.schema.js
app/schemas/models/interactives/interactive_session.schema.js
app/schemas/schemas.coffee
ozaria/site/api/interactive.js
ozaria/site/components/cinematic/PageCinematicEditor/index.vue
ozaria/site/components/common/BaseListItem.vue
ozaria/site/components/interactive/PageInteractiveEditor/index.vue
ozaria/site/models/Interactive.js
test/app/models/Interactive.spec.js
test/app/models/InteractiveSession.spec.js

- Added a new route for interactive editor
- Split `interactiveData` property into 6 properties for each type of interactive in the schema.
- Changed the type of element ids to stringID
- Added i18n
- Added ajv support for format ace(for code editor field in the editor), and hidden(for hidden fields)
Related changes on server: https://github.com/codecombat/codecombat-server/pull/84

Changes for Interactive editor

---

ozaria/engine/cinematic/dialogsystem/DialogSystem.js

Change the origin points for the speech bubbles.
Prior to this change the text location was calculated from the top left of the text bubble.
The diagram shows where the origin point is set based on the text given. The text location point is the red circle.
This new origin allows cinematic designers to set the text location point near the characters mouth and have the dialogue bubble expand up and away from the character.

Set intuitive origin points for Cinematic dialog bubbles

---

app/schemas/models/cinematic.schema.js
app/schemas/models/selectors/cinematic.js
ozaria/site/components/cinematic/common/CinematicCanvas.vue

Increased resolution to 1280x850.
Did a time boxed investigation updating the resolution based on the `window.devicePixelRatio`. (This would make our game support retina displays).
This is a very hard problem as it requires modifying our Camera system in a major way in order to preserve the transformations. Without camera modifications the game will appear at different scales on different pixel densities. I.e. on a retina display the game will look zoomed out.
Thus this change just scales up the screen size as per requested.
The default camera zoom is also updated to prefer zoomed out shots, which will default a higher quality, and allow more screen space for our larger assets.

Update cinematic dimensions to 1280x850

---

app/lib/world/thang.coffee

This commit brings player color customization into production for single player levels.
In order for the ThangType to be customized we first check if the player has `tints` in their `customizations` data.
These tints are applied to the colorConfig options.
In order for the tint to be displayed the ThangType must also have a matching colorGroup.
(You can use proxy server for test)
1. Choose the Anya hero.
2. Run the following code to set customization. (We're going to set team colors.)
```
me.set('customization', {
tints: [
{
"slug": "teamExample",
"colorGroups": {
"team": { hue: 0.8, saturation: 0.9, lightness: 0.7 }
}
}
]
});
me.save()
```
3. Play a single player level with Anya and notice she is customized.
You will end up [with something like …

Player Customization ColorConfig Middleware

---

app/core/Router.coffee
app/lib/dynamicRequire.js
ozaria/site/components/cinematic/PageCinematic/index.vue
ozaria/site/components/cinematic/common/CinematicCanvas.vue

Create a wrapper and test page for the Cinematic Canvas.
This wrapper accepts a slug and emits a completion event at the end of the cinematic.
It has been temporarily attached using the interactives page as a guide. This route is admin gated.

Cinematic Canvas View Wrapper

---

app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/CinematicLankBoss.js
test/app/models/Cinematic.spec.js

In the cinematic editor is was found that this property wasn't correctly attached. There was no delay happening for background objects added to the cinematic shot.
Connect the data of the delay to a delay command when creating a background object.

:bug: Background object delay not connected

---

ozaria/site/components/cinematic/common/CinematicCanvas.vue

Improve the user experience of the cinematic allowing the user to achieve two behaviors from clicking on the cinematic.
Clicking the cinematic will skip the current playing shot if one is playing. Or start the next shot.

Remove Next button from Cinematic

---

app/templates/editor/level/save-level-modal.jade
app/templates/editor/modal/save-version-modal.jade

We don't know if this feature fully works and have been mostly relying on not using it, but that's fragile. Rather than find out or use it, a quick fix to disable.

Disable and hide save new major version checkbox

---

app/lib/surface/Lank.coffee
ozaria/engine/cinematic/CinematicLankBoss.js
ozaria/engine/cinematic/cinematicController.js
ozaria/site/components/cinematic/PageCinematicEditor/index.vue
ozaria/site/components/cinematic/common/CinematicCanvas.vue

This bug manifests in many ways. Currently you can see it best when you navigate to this [cinematic](https://www.codecombat.com/cinematic/1fhl1c2).
The mushroom should be the same scale throughout the entire cinematic. (Which you can manually test locally using the proxy).
To test with proxy. Have two terminals open and run `npm run dev` and `npm run proxy` simultaneously.
The issue seemed to be the way the engine handles scaling.
I first decoupled the treema editor data to make replaying the same cinematic deterministic.
The stage bounds were made into a dynamic getter to ensure the characters always have the latest camera bounds.
Finally we've added an `isCinematic` option to the Lank which prevents the implicit tweening and stretching of the scaling.
I also added an isLoaded callback …

:Bug: Cinematic Lank Scaling Issues

---

app/styles/editor/thang/colors_tab.sass
app/templates/editor/thang/colors_tab.jade
app/views/editor/thang/ThangTypeColorsTabView.coffee
ozaria/site/api/tint.js

Add tint editor to the thang editor color tab. Can be accessed via `/editor/thang` and then clicking on the Color tab.
This tab now has two modes. The default mode is the original purpose which is to define color groups. But there is now a button that switches the page to a tint playground tab and mode.
The tint assignment tab allows testing out various color tint combinations, and saving them to the database.
This tab includes a second treema for editing the tints.
It also replaces the grid of colors with dynamically created tints from the treema. This allows designers to combine the various tints together on the thang instead of one at a time as per prior behavior.
Once tints have been defined in the treema, they can now also be saved to the database if the user is an admin.
Features in …

Tint editor extension

---

app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/CameraSystem.js
ozaria/engine/cinematic/cinematicController.js
ozaria/engine/cinematic/commands/CinematicParser.js
ozaria/engine/cinematic/dialogsystem/DialogSystem.js
ozaria/engine/cinematic/dialogsystem/helper.js
test/app/lib/cinematic/cinematicParser.spec.js
test/app/models/Cinematic.spec.js

Currently, Cinematic defaults are nonsense, and it puts a lot of work on content production to type out the same numbers repeatedly.
By setting defaults based on [this doc](https://codecombat.slab.com/posts/cinematic-default-values-x0j7dmw8), we'll be able to increase content production velocity.
This change gives the Cinematic System some context around how it is used. We predominantly use zoom level 1 and zoom level 2 for the dual shot and close up shots.
For both of these shots there is a standard text position that can be used by default.
Similarly characters are always placed in the same position and also have specific values that can be set.
It is important that if a value is ever set in the cinematic editor it overrides the default.
We should also expect these defaults to change as …

Set reasonable Cinematic default values

---

README.md

The current README has top of Catherine's avatar cut-off, as shown below:
This PR will fix that issue by using a non-cut-off image. (I've resized it so it matches the sizes of others). After fix:

Fix Catherine's "cut-off" avatar image in README.md. 

---

ozaria/site/templates/play/game-dev-goals.pug
ozaria/site/templates/play/play-level-view.pug

When playing a game dev level via the `/ozaria` route, the goals mixin wasn't connected and would throw an error.
Fork the goals mixin as a pug file into the new ozaria templates folder structure.

:bug: Fork the game-dev-goals layout for Ozaria play view

---

app/lib/surface/SegmentedSprite.coffee

Adds shape rendering code path to the Segmented Sprite builder.
This allows shapes to be rendered in our segmented sprites.
Code is heavily inspired (copied) from [an existing code path that renders shapes](https://github.com/codecombat/codecombat/blob/983b6ac2f33c07b6619f8b1d3fc5a4aaa0386bce/app/lib/sprites/SpriteBuilder.coffee#L21) correctly.
**This unblocks us from importing art into Adobe Animate**. Which doesn't have containers, and thus fails to render in our segmented sprite. It does render in the editor using the SpriteBuilder.
This will improve all artwork in our game that has relied on shapes for some kind of effect.
For example, this is what is currently being rendered in the game:
This is the art that we were given, and what the animation looks like after this fix:
I've been …

Add shape rendering to segmented sprite

---

bower.json

Remove font links that are now broken preventing deploy.
These fonts appear to be stored locally within `assets/fonts`.
Manually tested and appears to work. Will want to test in staging. Test by changing homepage language to Russian and ensure it looks the same as the CodeCombat.com russian page in production now.

Remove broken font links

---

app/models/Classroom.coffee
app/schemas/models/campaign.schema.coffee
app/schemas/models/classroom.schema.coffee
app/views/editor/campaign/CampaignEditorView.coffee
app/views/play/level/modal/CourseVictoryModal.coffee
ozaria/site/common/ozariaUtils.js
ozaria/site/components/play/PageIntroLevel/index.vue
ozaria/site/components/play/PageUnitMap/index.vue
test/ozaria/site/common/ozariaUtils.spec.js

- Schema changed for campaign.levels.nextLevels and similarly for classroom - nextLevels is now an object
- Changes in the next level logic
- Changes in building the level status map
Design doc with description of the new next level logic:
https://docs.google.com/document/d/1XTVtPjG_9gGic3FBPC7PYClTrf82fhxyzMnXzCK529Q/edit#heading=h.z287uqh1z7hk (specially section "How to handle non-linear flow(1FH Capstone)")

Changes for 1fh capstone flow on unit map

---

app/core/Router.coffee
app/core/vueRouter.js
app/lib/LevelBus.coffee
app/lib/simulator/Simulator.coffee
app/lib/world/GoalManager.coffee
app/schemas/models/level.coffee
app/schemas/models/level_session.coffee
app/schemas/subscriptions/play.coffee
app/views/play/level/LevelGoalsView.coffee
ozaria/site/components/cinematic/CinematicPlaceholder/index.vue
ozaria/site/views/play/level/PlayLevelView.js
ozaria/site/views/play/level/modal/CapstoneProgressComponent.vue
ozaria/site/views/play/level/modal/CapstoneProgressModal.js
ozaria/site/views/play/level/modal/CapstoneVictoryComponent.vue
ozaria/site/views/play/level/modal/CapstoneVictoryModal.js
test/app/lib/world/GoalManager.spec.coffee

We need a type of capstone level that can have multiple completions. This means that as the student is playing, they are effectively on a stage of the capstone level. 
For each stage that is completed, a cinematic will be shown. Once the cinematic has been watched, the level can be continued - now at the next stage. 
Due to the questions around deploying this safely to Next for testing, this needs to be reviewed locally. That means creating a new level to serve as the capstone level, in order to test the functionality. This is fairly involved, so it is explained in [this Slab doc](https://codecombat.slab.com/posts/capstone-levels-guide-rcosczss) as a general guide for Capstone Levels.
- `Level` now has a new property called `additionalGoals`, deciding how many stages are possible to …

Capstone stages

---

ozaria/engine/cinematic/CinematicLankBoss.js

Before this fix the cinematic character is created at an arbitrary y axis and then slid into position. This y position was a silly programmer default that looks horrible.
We want characters to start and end at the same y position. Thus this fix assigns the end position y coordinate to the start position if it is provided.
Also made characters slide in and out further so that they completely leave the frame when entering and leaving.

Fix cinematic character swooping in bug

---

app/schemas/models/cinematic.schema.js
app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/cinematicController.js
ozaria/engine/cinematic/systems/autoplay.js
test/app/models/Cinematic.spec.js

- Add additional property to cinematic schema, which by default requires user input to start next cinematic shot.
- Designer can set this to false and have next shot autoplay. This is useful for better coordination of shots.
Likely still need to discuss how much of a shot needs to be skipped if it is autoplaying dialog nodes.

Designer can set cinematic shot to continue without user input

---

app/lib/surface/SegmentedSprite.coffee

After the shapes were introduced to segmented sprites in #5393, a bug has appeared on the level [Coinucopia](https://direct.codecombat.com/play/level/coinucopia).
This reverts the change temporarily until we've resolved this issue.

:Bug: Revert shapes in segmented sprites

---

app/schemas/models/cinematic.schema.js
app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/CinematicLankBoss.js
ozaria/engine/cinematic/constants.js
ozaria/engine/cinematic/dialogsystem/DialogSystem.js
test/app/models/Cinematic.spec.js

The text animation length did not change how long it took letters to animate on the screen.
This made it impossible to synchronize the talking animation with text appearing on the screen.
- Fix timing logic by considering time per letter.
- Extend default logic to be based on the length of the text. A 1000ms default isn't useful with long and short text. Instead use a constant for how long each letter takes to appear on screen.

Fix timing of text and speaking animation in Cinematics

---

app/schemas/models/cinematic.schema.js
app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/cinematicController.js
ozaria/engine/cinematic/commands/CinematicParser.js
ozaria/site/components/cinematic/PageCinematic/index.vue
ozaria/site/components/cinematic/PageCinematicEditor/index.vue
ozaria/site/components/cinematic/common/CinematicCanvas.vue
ozaria/site/components/play/PageIntroLevel/index.vue
test/app/lib/cinematic/cinematicParser.spec.js
test/app/models/Cinematic.spec.js

Some dialog in the cinematic is language specific. Currently there is no way to skip nodes that may not be relevant.
This provides a way to tag a dialog node with a specific programming language. If you tag a dialog node with python it will not display for javascript watchers.
Also includes a selector in the editor environment allowing a designer to toggle between the supported languages.
Defaults to python on the `/cinematic` view. This will need to be integrated when cinematics is integrated into the intro flow.

Add Cinematic support for filtering by programming language

---

app/locale/en.coffee
app/templates/core/create-account-modal/teacher-role-panel.jade

With teachers coming to us from different sources, we want to differentiate between conference referring and other referring. 
Simply adds another option to the list of referrers. 
TBD - need to verify that this flows through Intercom.

Feature: Add ISTE as teacher referrer option

---

app/schemas/models/campaign.schema.coffee
app/schemas/models/level.coffee
app/views/editor/level/settings/SettingsTabView.coffee

Adding a new property `ozariaType` in the levels to identify the type for ozaria levels as practice/challenge/capstone.
The existing properties `type`/`kind` could not be used since they have different meanings (Eg: type is for the type of campaigns like game-dev, hero, web-dev), and its unclear if using a different value in type could interfere with the existing functionality.
However, for ozaria level type `intro` we can continue to use the existing `type` since it is completely different than other types and will not interfere with the existing types and their functionality.

Add ozariaType in levels schema

---

app/schemas/models/level.coffee
ozaria/site/components/play/PageIntroLevel/index.vue
test/ozaria/site/components/play/PageIntroLevel.spec.js

Changed intro level's `introContent` to take content ids instead of content slugs so that it does not break when slugs are updated

Change contentSlug to contentId in intro levels

---

app/lib/sprites/SpriteBuilder.coffee
app/schemas/models/thang_type.coffee

New Adobe Animate art turns movieclips off instead of containers.
Extend support for off onto movieclips.
Manually checked with the Isometric walk down Hero A.
Should be merged with https://github.com/codecombat/adobe-animate-parser/pull/3.

Add _off support on movieclip

---

app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/CameraSystem.js
ozaria/engine/cinematic/CinematicLankBoss.js
ozaria/engine/cinematic/Loader.js
ozaria/engine/cinematic/constants.js
ozaria/engine/cinematic/dialogsystem/DialogSystem.js
ozaria/engine/cinematic/dialogsystem/helper.js
test/app/models/Cinematic.spec.js

Cinematic Hero A and B are both imported. As they have vastly different proportions from the isometric art, the defaults need to be updated.
An additional default was added. This is the camera position used when camera is set on zoom 2. If the camera is at position 0, 0 and zoom is set on 2.
This default introduces some brittleness as it means the position 0,0 is treated as an unset condition. However the trade off is that content creation becomes even easier.

Correct Cinematic Defaults for content creation

---

app/views/play/level/modal/CourseVictoryComponent.vue
app/views/play/level/modal/CourseVictoryModal.coffee
ozaria/site/common/ozariaUtils.js
ozaria/site/components/play/PageIntroLevel/index.vue
ozaria/site/views/play/level/PlayLevelView.js

For teachers playing through course guides, need to pass capstone stage in query params in order to determine the next levels in the 1fh capstone flow (i.e. back and forth with the intros)
- When an intro is completed and it unlocks a particular stage of capstone level, send the correct stage in capstone level's URL as param `capstoneStage`.
- When the capstone level is completed, its current stage can be determined from the query param `capstoneStage` and the next intro level can be determined based on that.

Use capstone stage in query params to get next level for teachers

---

app/core/Router.coffee
ozaria/site/api/interactive.js
ozaria/site/components/interactive/PageInteractive/draggableOrdering.vue
ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion.vue
ozaria/site/components/interactive/PageInteractive/index.vue
ozaria/site/components/interactive/PageInteractive/insertCode.vue
ozaria/site/components/play/PageIntroLevel/index.vue

Course instance is no longer required for interactive session's APIs since it was being used to determine code language in the APIs, but since we already know the intro level's session's code language on the frontend interactive page, sending that directly to the interactive session's APIs.
Related server PR: https://github.com/codecombat/codecombat-server/pull/102

Send codeLanguage from intros to interactives instead of course instance

---

app/collections/Levels.coffee
app/locale/en.coffee
app/templates/teachers/teacher-course-solution-view.jade
app/templates/teachers/teacher-student-view.jade
ozaria/site/views/play/level/PlayLevelView.js

Add a way for us as admins and for teachers and sessionless users in general to set the capstone stage for a level as it is being loaded. 
This is being implemented through a query parameter that will forcibly set the capstone stage directly, disregarding any goals. 
1) Try to play https://next.codecombat.com/ozaria/play/level/capstone-test-1 by adding more munchkins
2) After having progressed through the stages, add `?capstoneStage=1` (for example) to the URL so it looks like this: https://next.codecombat.com/ozaria/play/level/capstone-test-1?capstoneStage=1
3) Expect the capstoneStage to have been set to the query parameter
This is live on Next now.

Set capstoneStage from query parameter

---

app/core/Router.coffee
ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue
ozaria/site/components/interactive/PageInteractive/draggableStatementCompletion/index.vue
ozaria/site/components/interactive/PageInteractive/index.vue
ozaria/site/components/interactive/PageInteractive/insertCode/index.vue
ozaria/site/components/play/PageIntroLevel/index.vue

Intro level ID is not required for interactive session API, therefore removing it from the frontend pages.
Server PR: https://github.com/codecombat/codecombat-server/pull/103

Remove intro level id prop from interactives pages

---

app/schemas/models/level.coffee
app/schemas/models/level_component.coffee
app/views/editor/level/settings/SettingsTabView.coffee
ozaria/site/styles/play/level/tome/spell-palette-view.sass
ozaria/site/templates/play/tome/spell-palette-view.jade
ozaria/site/templates/play/tome/spell_palette_entry_popover.jade
ozaria/site/views/play/level/tome/DocFormatter.coffee
ozaria/site/views/play/level/tome/SpellPaletteThangEntryView.coffee
ozaria/site/views/play/level/tome/SpellPaletteView.coffee

- Added methodsBankList to level schema which can be added from settings tab in level editor. We need to add this property to store the list for methods bank along with their section and sub-section name.
- Added shortDescription to level component property documentation schema, in order to save and show a short description for each documentation.
- Removed a bunch of code from SpellPaletteView.coffee and simplified the logic to read methodsBankList from level's settings and group them based on sections and sub-sections.
This is the first iteration of the new methods bank and it involves only the functional changes.
The pages changed in this PR are forked versions of the legacy pages and these are gated behind admin flags, so its safe to ship and test in prod with test ozaria levels. I …

Functional implementation for methods bank

---

app/schemas/models/selectors/cinematic.js
test/app/models/Cinematic.spec.js

We've imported new and much more performant Adobe Animate Cinematic heroes.
Because they are also smaller, this tweaks their default scale so they remain a similar size.
Manually tested and internal only.

Tiny defaults update for Cinematics

---

app/schemas/models/cinematic.schema.js
app/schemas/models/selectors/cinematic.js
ozaria/engine/cinematic/CinematicLankBoss.js
ozaria/engine/cinematic/Loader.js
test/app/models/Cinematic.spec.js

Features:
- Can add hero dog thangType that attaches itself to the right character if and only if this character is a hero.
- Add heroDog schema, selector, and test.
- CinematicLankBoss handles heroDog as an edge case to stick the dog to the right hero character with an offset.
- If the right character isn't a hero the pet is removed.
- Refactor out constants to the top of the file.
Open a test cinematic, via `localhost:3000/editor/cinematics`.
In the cinematic editor click through Shots -> Shot Setup and click the Plus. Add a `Hero Pet` property and fill it in like so:
```
{
"type": {
"slug": "duck-pet"
},
"pos": {
"x": -8,
"y": 10
},
"scaleX": 4,
"scaleY": 4
}
```
You may be able to copy that JSON and paste it in by selecting the `Hero Pet` block and using `Ctrl + Shift + V`.
Then test …

Add Hero Dog to Cinematic 

---

ozaria/site/components/cutscene/PageCutscene/index.vue
ozaria/site/components/cutscene/common/BaseVideo.vue

Adds two small features to cutscenes:
- Will try to auto play the cutscene. (This functionality is blocked by the browser until user interacts with the page).
- Will emit completed event when video concludes. There should be a UI that appears instead, but this is a stop gap to include Cutscenes into the flow earlier.

Completed event from cutscene

---

app/core/Router.coffee
app/core/vueRouter.js
app/lib/dynamicRequire.js
app/schemas/models/level.coffee
ozaria/site/components/play/PageIntroLevel/index.vue
ozaria/site/components/play/PageUnitMap/common/UnitMapLevelDot.vue
test/ozaria/site/components/play/PageIntroLevel.spec.js

- Moved intro level route from vue router to backbone router since we dont have support for empty templates in vue router.
- Added cutscene vue component to the intro level page.
- Changed the schema for introContent - instead of being an array or an object, it will always be an array. The content id can now either be a string id or an object with string ids for each language if its different. This is useful because some content ids can be the same in all languages while a few can be different. In this case, we do not need to repeat the content ids which are the same in all languages.

Intro level integration with cutscenes + intro level schema change

---

app/lib/world/thang.coffee
app/schemas/models/thang_type.coffee
app/schemas/models/user.coffee
app/views/core/HeroSelectView.coffee
app/views/play/modal/PlayHeroesModal.coffee

This is a tiny PR but touches some important legacy code paths. Must be merged with https://github.com/codecombat/codecombat-server/pull/105
We want to start using new Ozaria heroes in levels. However we have behavior that adds these heroes to our legacy hero selectors.
This change adds a flag `ozaria` that can be used to mark a thangType as ozaria specific. The two hero selectors then filter against this flag to hide any ozaria heroes.
There is also a small refactor that renames `customization` to `ozariaHeroConfig`. This renaming is happening to better capture that `ozariaHeroConfig` will contain the ozaria hero id, player's ozaria name, and any future properties related to their ozaria hero. Not just color tints.
I recommend manually testing using your local developer environment or …

Add ozaria property and rename customization property

---

app/locale/en.coffee
ozaria/site/styles/play/level/control-bar-view.sass
ozaria/site/styles/play/level/game_dev_track_view.sass
ozaria/site/styles/play/level/gold.sass
ozaria/site/styles/play/level/hud.sass
ozaria/site/styles/play/level/level-dialogue-view.sass
ozaria/site/styles/play/level/level-playback-view.sass
ozaria/site/styles/play/level/tome/spell-palette-view.sass
ozaria/site/styles/play/level/tome/spell_palette_entry.sass
ozaria/site/styles/play/play-level-view.sass
ozaria/site/styles/play/variables.sass
ozaria/site/templates/play/tome/spell-palette-view.jade
ozaria/site/templates/play/tome/spell_palette_entry.jade
ozaria/site/templates/play/tome/spell_palette_entry_popover.jade
ozaria/site/views/play/level/ControlBarView.coffee
ozaria/site/views/play/level/GameDevTrackView.coffee
ozaria/site/views/play/level/LevelDialogueView.coffee
ozaria/site/views/play/level/LevelGoldView.coffee
ozaria/site/views/play/level/LevelHUDView.coffee
ozaria/site/views/play/level/LevelPlaybackView.coffee
ozaria/site/views/play/level/PlayLevelView.js
ozaria/site/views/play/level/tome/SpellPaletteEntryView.coffee
ozaria/site/views/play/level/tome/SpellPaletteView.coffee

This changes the look and feels of the spell palette view (methods bank) according to ozaria. It does not affect anything for the existing play level view and hence is safe to ship.
Also a lot of sass files have just been moved from legacy to ozaria folder and do not need a review (basically only second commit needs a review).
Screenshots of the new methods bank (this is the initial design implementation, I am sure there will be some polishing to it later):
TODO: Change the position of methods bank to the left of the screen with a clickable handle to open and close the methods bank - Will do this in a separate PR next week after Shasha uploads assets for them.

 Change UI for methods bank

---

app/core/application.coffee

This makes sure hitting a local host type of address, for example starting with `172.`, is treated as localhost. 
If WSL is used without transforming the linux subsystem, then the address would be on the `172` range.

Make development environment match '172.' as well as localhost

---

app/core/forms.coffee
app/locale/en.coffee
app/templates/teachers/request-quote-view.jade
app/views/teachers/RequestQuoteView.coffee
package-lock.json
package.json
test/app/views/teachers/RequestQuoteView.spec.coffee

This PR implements the following changes to the request a quote page:
- Convert first / last name to full name via a `parse-full-name` module
- Remove purchaser role and education level
- Changes the ordering of fields in the form to look good with reduced number of elements
- Replace text below "Request a Quote" with: Learn more about CodeCombat with an interactive walkthrough of the product
-  Change CTA at the bottom from "Request a Demo" -> "Submit"
- Make "School" and "Phone Number" fields required instead of optional
- Change "State" to "State/Region"
- Remove "What kind of class..." question

Request a quote form updates

---

app/schemas/models/user.coffee
ozaria/engine/cinematic/CinematicLankBoss.js

Adds a missing method to the cinematic thang that is used to customize singular and segmented sprites.
Also fixes a typo in the schema.
Change is isolated to Cinematics, and was tested manually.

Add cinematic hero tint customization support

---

app/core/Tracker.coffee
app/core/experiments.js
app/models/User.coffee
app/templates/base-flat.jade

- Adds an experiments module to capture grouping logic for future experiments.  Adds TODOs to existing experiment methods on User object to note that they should be migrated.
- Uses [GA custom dimensions](https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets) to track buckets.  This allows us to support up to 20 different configurations at any give time and allows us to continue using labels as intended.
- Add request a quote link to navbar when logged out

Add request a quote experiment

---

app/views/core/CreateAccountModal/CreateAccountModal.coffee

SegmentCheckView asks for age for individual users, and class code for students. The view is restricted for non-US/EU/Israel countries, or if no country is set for the users, due to which the students in those countries are not able to get this screen to enter the class code during signup.
Hence fixing this by removing the check for `SegmentCheckView` for student signup flow.
Related asana: https://app.asana.com/0/654820789891907/1127558195120065

Fix student signup flow for non-US/EU/Israel countries

---

app/lib/Angel.coffee

Without this, we'd often show incomplete goals in game dev even as the level was finished.
The problem was that the goal manager needs to mark "don't fail" type goals as successful once the world ends, but we weren't updating the goals view in game dev after that happened.

Fix game dev goal states

---

app/schemas/models/selectors/cinematic.js

The default position could be mutated and thus change the position of the characters later in the cinematic.
Use object assignment instead of lodash merge preventing mutation from occurring.
Manually tested the fix using proxy mode.

Fix Cinematic positioning with multiple characters

---

package-lock.json

Updates package lock with latest adobe animate parser.
Adds feature for importing containers without animations.

Update art parser package lock dependency

---

.storybook/webpack.config.js
ozaria/site/components/common/LayoutChrome.vue
ozaria/site/components/cutscene/PageCutscene/index.vue
ozaria/site/components/cutscene/common/BaseVideo.vue
ozaria/site/styles/common/variables.sass
stories/BaseVideo.stories.js

The cutscene controls were being obscured by the chrome.
Storybook wasn't working with `scss` styles in vue components, so I also updated that.
Use @jmif aspect ratio container and set the chrome padding size using css `calc`.
The refactor can be tested both in proxy with Cutscenes, but also by checking the BaseVideo stories in Storybook. Because this is a visual change I don't believe there is a better way to check this currently.
~In a future PR will move the chrome padding to variables shared across ozaria.~

Fix Cutscene Padding to not obscure controls

---

app/core/social-handlers/FacebookHandler.coffee

Required to ship together with PR https://github.com/codecombat/codecombat/pull/111
This changes the Facebook API from `v2.9` to `v3.2`, extending the time we have before the next update is required. 
There are no known breaking changes for this version bump. 
From now on, age restriction is also a factor for our Facebook usage. There are separate efforts for this here: https://github.com/codecombat/codecombat-server/pull/110

Updating Facebook API to 3.2

---

app/schemas/models/level_component.coffee
ozaria/site/views/play/level/LevelPlaybackView.coffee
ozaria/site/views/play/level/PlayLevelView.js
ozaria/site/views/play/level/modal/LevelIntroComponent.vue
ozaria/site/views/play/level/tome/DocFormatter.coffee

- Language-specific short description not working in command bank
- Change default type for description and short description to be generic for all languages for the ease of content creation
- Play level view loading error in case of editor mode (i.e. query param dev=true)(because of the changes in loading view for ozaria and the new intro screen)

LevelUX bugs

---

ozaria/site/components/common/SwappingVueDraggable.vue
ozaria/site/components/interactive/PageInteractive/draggableOrdering/index.vue

- Adds temporary SwappingVueDraggable component until swap functionality is released
- Sets draggable ordering to use it so elements swap instead of sort

Interactives UX: Make draggable ordering swappable

---

ozaria/site/components/interactive/PageInteractive/insertCode/index.vue

Interactives UX: Finalize insert code

---

ozaria/engine/cinematic/dialogsystem/DialogSystem.js
ozaria/site/components/cinematic/common/CinematicCanvas.vue
ozaria/site/styles/common/variables.sass

- Update Cinematic to work with the new chrome padding as per discussion.
- Manually checked that there is no border at 1366 by 768.
- Add "Click to Continue" to bottom of speech bubble. (Non final).
- Remove permanent Click to Continue from top right.
- Added debounce to resize to make it more performant.

Center Cinematic and add Click to Continue

---

ozaria/engine/cinematic/commands/commands.js
ozaria/engine/cinematic/dialogsystem/DialogSystem.js

Anime.js callbacks not firing consistently, resulting in dialog bubbles that would become frozen on the cinematic.
Pass the animation as a callback and separate the cleanup logic from the animation function.
If you'd like to manually test their are two UX interactions that are affected by this change.
1. Wait till a dialog bubble has been completely revealed and then clicking to continue.
2. Clicking during the reveal of a dialog bubble to skip it. And then clicking to continue.
These can be tested in proxy mode by running `npm run dev` and `npm run proxy` simultaneously.
Then log in as admin and navigate to: http://localhost:3000/cinematic/1fhl1c1
Prior to this fix you should occasionally see dialog get frozen.

Cinematic speech bubbles not clearing consistently

---

ozaria/site/components/common/LayoutAspectRatioContainer.vue

All ways of measuring the width and height of a container include padding.  This change accounts for the padding when calculating the width and height of the aspect ratio, ensuring that the aspect is ratio is calculated with respect to the content area of the parent container.

Ozaria UX: Account for padding in aspect ratio container

---

app/locale/en.coffee
ozaria/engine/cinematic/dialogsystem/DialogSystem.js
ozaria/site/components/cinematic/common/CinematicCanvas.vue
ozaria/site/components/common/LayoutCenterContent.vue

- Cinematic is constrained by the padding correctly. None of the cinematic is obscured.
- "Click to Continue" has been changed to "click anywhere to continue" and supports i18n.
Set up local proxy environment with `npm run dev` and `npm run proxy` running in parallel.
Navigate to localhost:3000 and log into your admin account.
Navigate to http://localhost:3000/cinematic/1fhl1c1 (or any cinematic) and observe that the bottom of the dialog bubble has `click anywhere to continue`.
While resizing the cinematic should stay within the bounds of the padding and not be obscured.

Center cinematic and add i18n

---

app/views/editor/thang/ThangTypeEditView.coffee
app/views/editor/thang/replaceRgbaWithCustomizableHex.js

This tool has no interface by design. It will only be used on a tiny subset of the art that we'll be importing, but is a useful command. One that I have been using in proxy mode to fix art.
Lets you run the command `currentView.normalizeColorsForCustomization()` in the console while in the thang editor on a thangtype. This will fix the Adobe Animate colors and make the character work with Character Customization.
Adobe Animate doesn't export the colors we have defined as hex values, but as either:
- The hex value.
- an `rgba` value where the `rgb` part is very close to or exactly the hex value.
Because the engine can't customize rgba values, this tool iterates through a thangTypes shapes and sees if the color is near one of the character customization colors.
If so, the colors …

Internal character cusomization color tool

---

app/core/Router.coffee
app/lib/dynamicRequire.js
ozaria/site/components/common/LayoutAspectRatioContainer.vue
ozaria/site/components/play/PagePlayLevel/index.vue
ozaria/site/styles/common/common.sass
ozaria/site/styles/common/variables.sass
ozaria/site/styles/play/level/goals.sass
ozaria/site/styles/play/level/level-dialogue-view.sass
ozaria/site/styles/play/level/level-playback-view.sass
ozaria/site/styles/play/level/tome/cast_button.sass
ozaria/site/styles/play/level/tome/spell-palette-view.sass
ozaria/site/styles/play/level/tome/spell.sass
ozaria/site/styles/play/level/tome/spell_palette_entry.sass
ozaria/site/styles/play/level/tome/spell_toolbar.sass
ozaria/site/styles/play/level/tome/tome.sass
ozaria/site/styles/play/play-level-view.sass
ozaria/site/styles/play/variables.sass
ozaria/site/templates/play/level/tome/spell.jade
ozaria/site/templates/play/level/tome/tome.jade
ozaria/site/templates/play/play-level-view.pug
ozaria/site/views/play/level/LevelGoal.vue
ozaria/site/views/play/level/LevelGoals.vue
ozaria/site/views/play/level/tome/ProblemAlertView.coffee

Did a lot of styling changes to polish the level UX and update dimensions of various level components: 
- Wrapped PlayLevelView in a Vue component
- Added chrome around the level view
- Set a fixed aspect ratio for the levels
- Used common font styles from common/variables.sass
- Updated dimensions of everything in the level UX as per updated specs
If you want to test manually, connect to the proxy server (`npm run proxy`) and go to `http://localhost:3000/ozaria/play/level/1fhm1l1l1` to see the updated level UX.

Level UX updates

---

ozaria/engine/cinematic/dialogsystem/DialogSystem.js
ozaria/site/components/cinematic/PageCinematicEditor/index.vue
ozaria/site/components/cinematic/common/CinematicCanvas.vue

- Cinematic dialog bubble should be wider when zoomed in.
- Fixed: Cinematic Editor should display the cinematic at the max dimensions.
- Cinematic speech bubbles display none when not visible. This should make the bubbles slightly more performant on low end devices.

Cinematic dialog text should be wider when zoomed in

---

app/schemas/models/cinematic.schema.js
app/schemas/models/user.coffee

Adds required avatar schema to ensure that schema stays consistent between the two products.
Renaming `ozariaHeroConfig` is being punted to next week. Tricky to make the change while some other PRs are open.

Avatar Schema Update

---

app/schemas/models/user.coffee

This allows us to update the schema on the Ozaria server and not have users break when they navigate between the two websites.
Use your local database and codecombat server. Run `npm run dev` from the client and `npm run nodemon` from the server. Then try to save a new property like so:
`me.set('ozariaUserOptions', {playerHeroName: 'rawr', test: 123})`
`me.save()`
^ This saves a property on the schema and a property that is not on the schema.
After refreshing use `me.get('ozariaUserOptions')` and you should see both properties.

Make ozariaUserOptions more permissive

---

app/assets/pwa/manifest.json
app/templates/static/layout.static.pug

ISSUE
----
Currently there's no icon when you add CodeCombat to the home screen
on iOS (just a screenshot of the page). Also, the name of the icon on
the home screen is just the title of the page ("Play CodeCombat
Levels...").
SOLUTION
------
I've added a high-res favicon for iOS, and I've also added a [PWA](https://developers.google.com/web/fundamentals/web-app-manifest/)
manifest file so that the icon title defaults to "CodeCombat". This
should also work on Android (although I haven't been able to test it
myself). On iOS I've also configured the app to hire the address bar,
when you start it from a home-screen icon, which gives a bit more
vertical space on the page and should make it feel more like a real
app.
There are other css issues with CodeCombat on iOS (which I or someone
else …

Added a PWA manifest file and ios touch icon

---

app/templates/play/level/control-bar-view.jade
app/views/play/level/tome/CastButtonView.coffee

This level is not in a campaign and has no victory rewards, so when you press the green Done button after succeeding during initial game testing, it shows a nearly empty HeroVictoryModal with a Continue button linking to last year's Hour of Code campaign.
This change makes it so that the Done button doesn't show up for that level. You can still get to its shareable link via the Game button at the top.

Don't show 'Done' button when playing Resource Tycoon

---

app/views/play/level/PlayLevelView.coffee

Right-clicking the Surface shows either a copy coordinate context menu or the default browser context menu, depending on whether coordinates are shown in the level and the browser supports letting us copy to the clipboard.
Now, if in real-time playback mode (playing a game-dev level, for example), right-clicking won't do anything. This fixes development-mode interface elements from getting in the way during play mode.

Don't allow right clicking during real-time playback

---

app/schemas/models/user.coffee
app/views/core/CreateAccountModal/BasicInfoView.coffee

Seeing a lot of spam teacher users with firstName and lastName set to 玩游戏宋128圆菜金加Q204384420领取优惠专属网址604774. Seeing if this would thwart them.

Add validation against spam user account names

---

app/core/social-handlers/GoogleClassroomHandler.js
app/schemas/models/user.coffee
app/views/courses/ClassroomSettingsModal.coffee
test/app/core/social-handlers/GoogleClassroomHandler.spec.js

Issue: Classrooms imported to Codecombat should be available to import on Ozaria as well, i.e. Codecombat GC import and Ozaria GC import should work independent of each other.
- Added `importedToOzaria` and `deletedFromGC` flag to user schema `googleClassrooms` property
- Updated `importClassrooms` method to merge imported classrooms and set `deletedFromGC` flag.
- Updated test cases
Related changes also done on ozaria client repo.
Tested some cases locally, but difficult to test everything since it involves schema updates in both coco and ozaria. Will test on staging before deploying to prod.

Changes to support GC in Ozaria

---

app/views/courses/TeacherClassesView.coffee
app/views/teachers/OzariaEncouragementModal.vue

Category was incorrectly applied for GA events.

Fix category in tracking events for encouragement modal

---

server_config.coffee

This duplicates the Ozaria server config process have, allowing us to initialize config from a JSON bundle in an environment variable.  This allows us to pull secrets from a secret store (AWS Secret Manager) and not store them in our repos.  This is required to run CodeCombat on Fargate.

Add support for JSON bundle server config

---

bower.json

ISSUE
-----
Right now it's not possible to use the editor on iOS. Although no javascript errors are thrown, the editor does not appear, making code combat unusable.
Here's what it looks like (note that the editor isn't visible and can't be used):
SOLUTION
------
Code combat is using ace editor version 1.2.9, which is rather old and doesn't have good mobile support. There have been a lot of improvements for mobile in version 1.4, and upgrading to ace editor 1.4.5 makes it work perfectly on iOS with no code changes.
Here's what it looks like with the latest ace editor (see that the editor is working as it does on desktop):
These are the [changes](https://github.com/ajaxorg/ace/blob/d893a99a8bb317440080bd766288da4e8a7e9524/ChangeLog.txt) in ace editor between versions 1.2.9 and 1.4.5:
``` …
```

Upgraded ace editor to 1.4.x for better mobile support

---

app/views/editor/campaign/CampaignEditorView.coffee

Issue -> Once levels are added to a campaign and it is saved, then try to add more levels to the campaign. While saving the campaign again, the campaign index gets incorrectly updated for existing levels too, whereas it should only update for the new levels with an incremented value.
Mirroring the fix from Ozaria repo.

Fix campaign index update from campaign editor

---

app/locale/en.coffee
app/locale/zh-HANS.coffee
app/models/User.coffee
app/schemas/models/course_instance.schema.coffee
app/templates/courses/teacher-class-view.jade
app/views/courses/TeacherClassView.coffee
app/views/play/CampaignView.coffee
server_setup.coffee

Allow teacher to assign certain level within a course under China.
Say we set `Enemy Mine` as `startLockedLevel`, then levels start from `Enemy Mine` will be locked, all other levels before including practice and assessment levels are available
For simplicity, currently can only support choosing main level, without practice and assessment level.

Course progress controll

---

app/locale/en.coffee

Landing page has 2018 welcome.
Update copy to 2019.
Change seen below:

Update hoc banner to 2019

---

app/templates/static/layout.static.pug
compile-static-templates.coffee

localize page title when compiling static template
search engines in China get fallback title in `layout.static.pug`, but google catch the another one which located in `i18n/en.coffee#new_home.title`, this pr unify these two titles and will help Chinese search engine get Chinese title.

localize page title

---

vendor/scripts/createjs.js

This would ease impact of Chrome EaselJS hit test performance regression.
Lance and China partners noticed that in Lernaean Hydra and other game dev levels, performance was very slow. I noticed this in any game dev levels where multiple Thangs were close together, in Chrome only, and profiled it to the hit testing method in EaselJS. Not sure if it was always this slow, but it was really slow, so that the game stuttered on every click if clicking near multiple Thangs.
We had a monkey patch to EaselJS to optimize how many Thangs would need hit testing (anything within 10m of the world position of the click), and this heuristic tightens it based on the physical world dimensions of the Thangs (usually significantly less than 10m, and narrower in the x vs. the y dimension). Note that physical …

Tighten heuristic on which Thangs might need hit testing

---

app/lib/aether/interpreter.coffee

Infinite `while (true)` loops didn't yield when using C++ and would crash everything.
C++ uses some different tokens. Instead of a `Literal` token, it's a `BooleanLiteral` token that represents the concrete value `true`. By updating the aether yielding function, it's possible to add yielding to infinite C++ loops. 
Although this touches a lot of code, it's additive. I believe the only risk is that this somehow causes more yielding to happen in the context of `while (<Literal | BooleanLiteral>)`.
I cannot think of a situation where this happens.
If china needs this asap, merge this change behind a feature flag.
1. Check out this change locally.
2. Run against proxy
3. On the home page log into your admin/internal account.
4. Navigate to …

Fix infinite loop in C++

---

app/views/play/level/tome/SpellView.coffee

When language was set to C++ it wasn't adding semicolons.
The snippet system checks the language based on the ace editor language mode which uses `c_cpp` instead of `cpp`.

Fix cpp ace editor language mode

---

app/views/play/CampaignView.coffee

A prompt comes up which lets the student enter in their parents email address to show progress. There isn't supposed to be a prompt in the classroom version for parents emails.
Check to make sure the user is not a student before showing modal. This preserves behavior for home users.
Tested fix manually on Firefox.

Remove share prompt from classroom

---

app/lib/aether/aether.coffee
package-lock.json
package.json

The browser `atob` function doesn't work with UTF-8 [[reference](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem)].
This leads to utf-8 strings in the users code to become destroyed.
For example, the following `hero.say("abӁcd");` becomes `hero.say("abÓ cd");` if using the native `atob` function.
The easiest fix is to use a library.
1. As an admin start a local environment and use `npm run proxy` to connect to production server.
2. Choose C++ language
3. Add the code `hero.say("abӁcd");` into a level and check that the hero actually says that.

Add UTF-8 support for cpp

---

app/views/play/level/PlayLevelView.coffee

When playing with C++ the lines of code goal doesn't take into account the function wrapper.
Programmatically increase the lines of code by 2 to compensate.
This was manually tested with production proxy on the following levels:
- descending-further
- the-second-kithmaze
- haunted-kithmaze
If testing with an admin account you should have access to the experimental language.

Add linesOfCode goal C++ middleware

---

app/models/User.coffee
app/views/play/CampaignView.coffee

Need to make changes for the following:
- Do not show classroom signup prompt on campaign editor view.
- Do not show for code ninjas/brainpop.
Asana: https://app.asana.com/0/654820789891907/1153432423150975
We already have the check for hiding signup prompt for codeninja and brainpop however it was not working due to operator precedence.
The check was: `not (features?.chinaUx ? false or window.serverConfig?.codeNinjas ? false or features?.brainPop ? false)`. And the precedence for `or` operator is higher than the conditional `?` operator due to which it gives unexpected results.
See here for an example: https://coffeescript.org/#try:a%20%3D%2011%0Ab%20%3D%202%0Aalert((a%20%3D%3D%201%20%3F%20false)%20%7C%7C%20(b%20%3D%3D%202%20%3F%20false))%0Aalert(a%20%3D%3D%201%20%3F%20false%20%7C%7C%20b% …

Fix condition for signup prompt on campaign view

---

app/lib/aether/aether.coffee
app/lib/aether_utils.coffee
app/views/editor/verifier/VerifierTest.coffee
app/views/editor/verifier/VerifierView.coffee

This is in the same class of bugs that #5748 was in. We want to run C++ code in the level verifier to ensure that solutions work for students. However we cannot parse the C++ code on the client and need to add middleware to fetch the token from the server.
The first issue is that we don't have C++ tests. Therefore if there are no C++ tests, we transpile the JS solutions into C++ and use them instead. This is reasonable as we currently use this transpiler to generate starter code as well as solutions for the teacher.
Now that we have a C++ solution we need to add a step to the VerifierTest to fetch a token from the server, but only if the code is C++ or Java.
Then this token can be passed into aether and transpile is able to handle both the obfuscated and regular case.
There was also a …

Add C++ level verifier tests

---

app/lib/aether/aether.coffee
app/views/play/level/tome/SpellView.coffee

The c++ error is only displayed every second time, and doesn't clear if there is a correct solution.
Basically when writing C++ the error messages don't appear correctly.
It is because we only show errors if the source code is the same as what is transpiled. However this is not ideal in this case because the C++ code is an obfuscated token string.
The code was correctly working every second time because there is another code path that sets the `aether.raw` property to the source, in the case that they don't initially match...
This happens here: https://github.com/codecombat/codecombat/blob/9d3ea135088b618f9db07c3e98959faa05faf432/app/views/play/level/tome/SpellView.coffee#L836
The effect of this is the error appearing every second run, but this is really not good because `aether.raw` …

Fix C++ error displaying every second time

---

app/core/Tracker.coffee
app/core/experiments.js
app/templates/courses/teacher-classes-view.jade
app/views/courses/TeacherClassesView.coffee

- Removes custom dimension from GA
- Removes experiment from experiments file
- Updates views to always display the modal

Remove Ozaria encouragement modal AB test, always show Ozaria encouragement modal

---

app/core/store/modules/schoolAdministrator.js

When a teacher is administrating a large number of teachers the fetch users by ID call 502s.  This is due to the number of user IDs being passed in.  This PR splits the fetch users by ID call into batches so that we do not get the 502s.

Split user queries into batches with max length 100 to fix 502 school admin dashboard

---

app/templates/courses/teacher-class-view.jade
app/views/courses/TeacherClassView.coffee

The tooltips on the teacher dashboard are rendered every single time state is changed on the page. On a large classroom with 80 students this can lead to 1 second of jquery rendering after any state change.
Make the tooltips appear lazily. Only render the tooltip on demand.
On the classroom with 80 students, each render initially took 1500ms. This was the time taken to render after pressing a checkbox.
After this change it takes 500ms. It's still not great, but overall it's much faster.
Notice that the initial render is still the same, but the long tail of tooltips no longer exists from the screenshot above.
I manually tested on chrome, as well as drawing inspiration from our Ozaria teacher dashboard.
To test spin up a proxy environment.
Navigate to a classroom with many users.
Press the …

Make tooltips lazily improving dashboard render time by 1/3

---

app/templates/courses/teacher-class-view.jade
app/views/courses/TeacherClassView.coffee

Reverts codecombat/codecombat#5770
Tooltips position broken on slow internet. Can repro 100% via safari.
Caught it on staging using Safari. Although Chrome appears to work, a slower network may cause the issue to appear.

Revert "Make tooltips lazily improving dashboard render time by 1/3"

---

app/templates/courses/teacher-class-view.jade
app/templates/teachers/hovers/progress-dot-single-student-course.jade
app/views/courses/TeacherClassView.coffee

Fixed variation of PR: #5770 
Added a width and height to the image to help jquery position the tooltip across all browsers.
Below contains a repost of the PR.
The tooltips on the teacher dashboard are rendered every single time state is changed on the page. On a large classroom with 80 students this can lead to 1 second of jquery rendering after any state change.
Make the tooltips appear lazily. Only render the tooltip on demand.
On the classroom with 80 students, each render initially took 1500ms. This was the time taken to render after pressing a checkbox.
After this change it takes 500ms. It's still not great, but overall it's much faster.
Notice that the initial render is still the same, but the long tail of tooltips no longer exists from the screenshot above.
I manually tested on …

Improve Classroom render time

---

app/models/User.coffee
app/styles/style-flat.sass
app/templates/base-flat.jade
app/templates/contact-cn-view.jade
static-mock.coffee

China contact us page& base-flat footer update

---

app/core/Router.coffee
app/core/Tracker.coffee
app/core/Tracker2/BaseTracker.js
app/core/Tracker2/CookieConsentTracker.js
app/core/Tracker2/GoogleAnalyticsTracker.js
app/core/Tracker2/LegacyTracker.js
app/core/Tracker2/SegmentTracker.js
app/core/Tracker2/index.js
app/core/application.coffee
app/core/store/index.coffee
app/core/store/modules/me.js
app/locale/en.coffee
app/locale/locale.coffee
app/models/User.coffee
app/vendor.js
app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coffee
app/views/core/RootView.coffee
app/views/teachers/CreateTeacherAccountView.coffee
bower.json
package-lock.json
package.json
test/app/views/core/CreateAccountModal.spec.coffee
webpack.base.config.js

Base refactor of our client side tracking implementation.  This PR sets up the basic structure of the new tracker and integrates the legacy tracker with it but does not complete the refactor.  This PR should effectively be a noop in terms of functionality.  The legacy tracker is integrated with the new tracker such that it is still driving the core of the tracking calls.
**Summary of changes in this PR:**
- Create Tracker2 tracker and implement example tracker (SegmentTracker)
- Extract cookie consent out of legacy tracker and move into it's own tracker
- Import cookieconsent module with webpack instead of bower
**High level tasks still todo (in future PRs):**
- Automated tests
- Extract segment tracking from legacy tracker and move any remaining functionality into SegmentTracker
- Enable …

Tracker refactor

---

app/core/Tracker.coffee
app/core/Tracker2/DriftTracker.js
app/core/Tracker2/index.js
app/views/core/CocoView.coffee
app/views/teachers/CreateTeacherAccountView.coffee
package-lock.json
package.json

Removes client side Intercom integration and replaces it with Drift.  Intercom identify calls and event calls will still be sent via segment integration.
- Wires contact us link to open drift chat for teachers
- Removes intercom-client dependency
- Disables intercom chat in segment calls within legacy tracker
**Testing**
I've been manually testing throughout the past week and the latest version of this is live at next.codecombat.com (including changes in #5782)

Swap intercom for drift

---

app/core/Tracker2/BaseTracker.js
app/core/Tracker2/DriftTracker.js
app/core/Tracker2/index.js
app/core/Tracker2/pageUnload.js
app/core/api/users.coffee
app/core/store/modules/me.js
app/models/User.coffee
app/views/core/AuthModal.coffee
app/views/core/CreateAccountModal/BasicInfoView.coffee
app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coffee
app/views/teachers/CreateTeacherAccountView.coffee

This PR integrates identify calls with our signup, login and logout flows to ensure that the user is always properly identified.
- Refactors location of track event calls in response to signup / login / logout events
- Ensures identify calls are properly sent prior to page redirecting
- Adds a workaround for a Drift SDK shortcoming that does not expose when API calls are sent
Identify should now be called at:
- First session visit
- Login
- Logout
- Teacher signup
- Student signup
Testing
I've been manually testing throughout the past week and the latest version of this is live at next.codecombat.com

Add / update identify calls for signup and auth flows

---

app/core/Tracker2/BaseTracker.js
app/core/Tracker2/CookieConsentTracker.js
app/core/Tracker2/DriftTracker.js
app/core/Tracker2/LegacyTracker.js
app/core/application.coffee
app/core/store/index.coffee
app/core/store/modules/tracker.js

- Updates the cookie consent tracker to save state in Vuex store.  
- Adds a getter to pull consent declined status which is what drives tracker disabling.
- Integrates drift tracker with this new cookie consent status store
- Integrates legacy tracker with new cookie consent store
- Uses Vuex store watches to ensure that trackers are updated with latest cookie consent status.

Integrate cookie consent with Vuex store and disable Drift tracking when cookie consent declined

---

app/core/store/modules/me.js

This PR reverts a change that was incorrectly setting user state on anonymous users.  The change set the default values of the me store to the default values specified in the user schema.  When the me module is initialized with the user sent from the server, the updates are merged instead of updating the full user object.  This was causing the default values to persist on the client and eventually be written to the server.
This change was initially added to reset the client side user to an anonymous user after logout however we opted to use the logout redirect to do this.
Original code is here https://github.com/codecombat/codecombat/blob/9eb37d8df6b8bc4c938c37703b147b68b4274992/app/core/store/modules/me.js#L5 
This has been tested manually.

Revert to using null values for defaults in me module in vuex store

---

app/core/Tracker2/BaseTracker.js
app/core/Tracker2/CookieConsentTracker.js
app/core/Tracker2/DriftTracker.js
app/core/Tracker2/pageUnload.js
app/core/store/modules/me.js
app/core/store/modules/tracker.js

- Fixes a bug retrying identify calls on page unload
- Respects browser do not track settings in new tracker
Tested manually

Fix page unload bug and integrate do not track settings with new tracker

---

app/views/teachers/OzariaEncouragementModal.vue

Youtube is blocked in China, so a fallback video is required.

Add video in Ozaria encouragement for China

---

app/core/store/modules/me.js
app/core/store/modules/tracker.js

- Adds an `isSmokeTestUser` getter to the me module of the Vuex store
- Disables tracking for smoke test users and for spying users

Disable tracking for smoke test users and spying users

---

app/core/Tracker.coffee
app/core/Tracker2/BaseTracker.js
app/core/Tracker2/DriftTracker.js
app/core/Tracker2/LegacyTracker.js
app/core/Tracker2/SegmentTracker.js
app/core/Tracker2/index.js
app/models/User.coffee
app/views/TestView.coffee
app/views/core/AuthModal.coffee
app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coffee
app/views/teachers/CreateTeacherAccountView.coffee
test/app/views/core/CreateAccountModal.spec.coffee

- Finishes implementation of Segment tracker
- Removes segment integration from legacy tracker
- Triggers identify after page load during redirects related to auth changes
- Added firstName and lastName to drift identify traits
Tested manually

Extract Segment from legacy tracker and improve identify calls after page reloads during auth lifecycle

---

app/core/Tracker2/SegmentTracker.js

The SegmentTracker currently tries to call `window.analytics.reset()` regardless of if segment has been loaded onto the page.  This PR delays and / or prevents the call based on load state.

Fix bug in segment tracker preventing identity reset when segment not loaded

---

app/schemas/models/poll.schema.coffee
app/styles/editor/poll/poll-edit-view.sass
app/templates/editor/poll/poll-edit-view.jade
app/views/editor/poll/PollEditView.coffee
app/views/play/CampaignView.coffee
app/views/play/modal/PollModal.coffee

We want to support polls that are more than one view. This allows the content team to chain together polls from the answer given, allowing further info to be gained.
Poll answers have been given an additional `nextPoll` property that contains the id of the next poll. If an answer is selected with this `nextPoll` property we trigger an event that forces the next poll to be loaded and shown immediately.
Therefore each poll is still independent and treated in isolation, but a poll can trigger another poll to load. The benefit of this is we can do minimal work to change how votes are collected and minimal UI work.
In order to support this feature some minor schema changes have been made.
- Add `nextPoll` property to the answer that accepts a stringID.
- Add `hidden` property that allows …

Support for multi stage polls

---

app/core/Tracker2/DriftTracker.js
app/core/application.coffee
package-lock.json
package.json

Prevents Drift chat from showing in scenarios that we don't want it to.
- Adds a vuex module to sync vue router state to store so we can react to changes to it
- Disables drift targeting on /play/ pages
- Disables drift targeting for all students
Tested locally

Disable drift targeting for students and on /play/ pages

---

app/core/Tracker2/DriftTracker.js
app/core/application.coffee
app/core/vueRouter.js
package-lock.json
package.json

- Integrates lazy chunk loading with Vue router to ensure all views are loaded after application initialization
- Uses the same chunk names from `lib/dynamicRequire`
- Prevents an early load of vue router from loading views that have dependencies on application be initialized
Tested locally and going to deploy to next

Integrate lazy chunk loading with Vue router

---

app/core/social-handlers/GoogleClassroomHandler.js
test/app/core/social-handlers/GoogleClassroomHandler.spec.js

Calling the students API multiple times until nextPageToken is returned from the previous API call to make sure all students are imported.
Details in ozaria PR: https://github.com/codecombat/ozaria/pull/390

Fix google classroom student import issue

---

app/locale/en.coffee
app/styles/play/modal/live-classroom-modal.sass
app/templates/play/modal/live-classroom-modal.jade
app/views/play/CampaignView.coffee
app/views/play/modal/LiveClassroomModal.coffee
app/views/play/modal/PollModal.coffee

Currently we are running a poll to ask if users would like live classroom sessions.
We have set up a page at https://live.codecombat.com that provides much more information.
This change flashes a message to users who opt into wanting to learn more about these live classrooms.
The behavior we want intercepts either poll answer of a specific poll. This change adds a check for the poll being answered, and in the case of the "What kind of Course are you interested in?" poll triggers the live classes modal.
There are minimal risks as this is specific to the poll being answered. It shouldn't affect other polls or the campaign view in any way I am aware of. I tested it manually using incognito mode and anonymous users. We've also opted to go with speed > design, so the implementation attempts to …

Redirect certain poll responses to Live Classes page

---

app/core/utils.coffee
test/app/core/utils.spec.coffee

Did not account for practice levels or the locked level being set earlier than a student's next level to play.

:bug:Fix classroom level locking

---

app/core/Tracker2/BaseTracker.js
app/core/Tracker2/FullStoryTracker.js
app/core/Tracker2/ProofTracker.js
app/core/Tracker2/SegmentTracker.js
app/core/Tracker2/index.js
app/core/store/modules/me.js
app/core/store/modules/tracker.js

- Integrates FullStory session tracking
- Enables for entire session of a user at the beginning of a session by looking at the user type and randomly selecting a percentage of users based on that user type
TODO:

Integrate Full Story

---

app/collections/Products.coffee
app/core/Router.coffee
app/core/store/index.coffee
app/core/store/modules/products.js
app/core/vueRouter.js
app/views/PageParents.vue
app/views/common/BackboneModalHarness.vue
app/views/common/BackboneViewHarness.vue
app/views/core/ModalView.coffee
app/views/core/SingletonAppVueComponentView.js

- Removes some old Vue routes that are for ozaria only
- Adds new parents-v2 route for new parent page design
- Adds a basic parents page with CTA hooks in place
- Adds a BackboneModalHarness Vue component to allow us to use Backbone modals in Vue

Parents page v2

---

app/lib/world/world.coffee
app/views/ladder/utils.coffee

Arena levels keep getting the ordering of their Alliance System teams flipped, so that ogres comes first in the `playableTeams` list. This flips the human/ogre sides of the ladder page, and also breaks spectate mode, where it tries to load the human session in the ogre session's place and vice versa, causing the heroes to just have default logic. I recall it causing other issues in the past. One thing that we've been doing is re-saving arenas with minor changes to the Alliance System to get them into the right order, but as the ordering of the object is indefinite, sometimes they get disordered again.
Since we never actually do different arena teams (it's always just `"humans"` and `"ogres"`), this adds a check to normalize the order to `["humans", "ogres"]` if we notice that it was …

Normalize arena team order to ['humans', 'ogres'] to fix spectate and other bugs

---

app/core/Tracker2/DriftTracker.js

Remove trailing `/` so that it detects simple `/play` route

fix(drift): prevent drift from appearing on play pages

---

app/core/Tracker2/BaseTracker.js
app/core/Tracker2/index.js
app/models/User.coffee
app/views/TestView.coffee
app/views/core/AuthModal.coffee
app/views/core/CreateAccountModal/BasicInfoView.coffee
app/views/core/CreateAccountModal/teacher/TeacherSignupStoreModule.coffee
app/views/teachers/CreateTeacherAccountView.coffee

- Adds init timeout to all trackers to account for cases where trackers do not communicate error during init and result in waiting forever for init
- Catches all tracker errors and logs them instead of surfacing to user
- Use Promise.allSettled where possible to ensure every tracking call that is functional has time to complete

Tracker error handling improvements

---

app/schemas/models/user.coffee

Adds a new field to the `user.emails` object that captures the validation response from sendgrid so that we can save this data for future use (each API call to sendgrid costs us $$).

Add sendgrid validation data to user schema

---

app/styles/style-flat-variables.sass
app/styles/style-flat.sass

The navbar collapses twice instead of once, which makes the navbar overlap downwards and cover any banner we may have showing underneath. 
The navbar could have a wider logo and it could have additional navbar items. These are now covered by additional media queries that reduce their padding or margin so the total width can shrink further without wrapping downwards.

Fix media query for navbar collapsing

---

app/views/landing-pages/parents/PageParents.vue

- Deep link into relevant timetap page from choose plan buttons on live classes landing page

fix: update live classes self serve links to skip first selection screen

---

app/locale/en.coffee
app/styles/play/modal/codequest-2020-modal.sass
app/templates/play/modal/codequest-2020-modal.jade
app/views/play/CampaignView.coffee
app/views/play/modal/Codequest2020Modal.coffee
app/views/play/modal/PollModal.coffee

TODO:
Adds the simple modal that will appear after a user answers the poll.
The poll needs to be added via the poll editor. This is something I will do manually, and release once this is deployed.
This builds upon work done in this PR: https://github.com/codecombat/codecombat/pull/5812
Link to the poll that will trigger this modal: https://codecombat.com/editor/poll/want-a-challenge
There are some risks of regressions as this was done quite quickly. I tested manually and existing polls continue to work. The main touch point is the event that triggers the new modal. Thus I believe the regression risk is low.
I tested this manually with local database and patching the id with the local version. Was able to answer the poll and get the codequest modal.
Then continued to refresh and load polls …

Codequest poll trigger and modal

---

app/schemas/models/level_session.coffee

- Adds an optional source field to level sessions so we can identify level sessions that were added from external sources

feat: add source to level sessions schema

---

app/locale/it.coffee

Fixed a typo in the artisan page 'campanie -> campagne'.

fixed typo it translation Artisan page

---

app/lib/LevelLoader.coffee
app/views/play/level/tome/Spell.coffee

Several players [on the forum](https://discourse.codecombat.com/t/battle-of-red-cliffs-questions/23374/10) and via email support have noticed that opponents often load sample code (all archers) on the Battle of Red Cliffs. I dug in and it seems to be a race condition that involves `course-ladder` type levels, made much more likely because there are no dependent ThangTypes to load for hero equipment in this particular course ladder level, whereby the opponent session loads after everything else is loaded, too late to get its code inserted into the other team's Spell, which reverts to default code.
Race condition only appears in production. If I'm right, then the LevelLoader fix to check for a non-loaded `opponentSession` will take care of this. I also added a paranoid check in …

Fix a course-ladder race condition bug

---

app/views/core/HeroSelectView.coffee

in hero-select-view, we need i18n keys to translate hero short name in https://github.com/codecombat/codecombat/blob/4e2d519df51f25c12180a4c2b06bc309f70fa89e/app/templates/core/hero-select-view.jade#L14
and 
https://github.com/codecombat/codecombat/blob/4e2d519df51f25c12180a4c2b06bc309f70fa89e/app/lib/ThangTypeLib.coffee#L12-L15
while we do not get the i18n key in views
https://github.com/codecombat/codecombat/blob/4e2d519df51f25c12180a4c2b06bc309f70fa89e/app/views/core/HeroSelectView.coffee#L31-L33
so i add it

use i18n to show hero name in hero-select-view

---

app/templates/courses/enrollments-view.jade

Some duplicate UI was introduced into the license panel.
This is a visual only change.
Minimal risk. I don't believe I have removed any information from the teacher, as directly below the `pending` and `empty` prepaid UI is handled. This is only reducing some duplicate markup.
There is on pending and one available license.
The available license is sandwiched between two pending licenses.

Remove duplicate license UI for pending and empty licenses

---

app/styles/home-view.sass
app/templates/home-view.jade

Reverts this commit: https://github.com/codecombat/codecombat/commit/802a09959d2d45bf955b21d7e02c2e30bf589c13
Tested manually. Will remove the banner.
Screenshot of homepage after change:

Cleanup the CodeQuest banner

---

app/core/utils.coffee
app/views/play/level/PlayLevelView.coffee
test/app/core/utils.spec.coffee

standard cpp not allow void main
```
error: ‘::main’ must return ‘int’
```
for those cpp learners it is better to teach them to use `int main()`

fix standard cpp not allowe void main()

---

app/templates/about.jade

Small change to update team on about page.
Can be checked on /about route.

About page team updates

---

app/core/Router.coffee
app/views/special_event/HoC2018Component.vue
ozaria/site/views/special_event/HoC2018Component.vue

This PR adds:
- Link to a new 2020 HoC PDF.
- Adds a more specific route to match PDF expectation.
Tested manually:
- Teacher through course guide.
- Home user navigating through campaign views.
- Clicking PDF link.
- Navigating from PDF to campaign.

Update HOC pdf to 2020 and add url redirect

---

app/views/landing-pages/parents/PageParents.vue

A row was malformed in Firefox on the parent page.
This explicit styling ensures page lays out correctly.
I tested on Firefox as well as Chrome to ensure no regressions occurred.
**The issue:**
Can be seen on codecombat.com/parents when using firefox browser.
With this fix:

Parent page styling fix for Firefox

---

app/core/Tracker.coffee
app/core/experiments.js
app/models/User.coffee
app/styles/play/campaign-view.sass
app/styles/play/play-level-view.sass
app/templates/base-flat.jade
app/templates/core/subscribe-modal.jade
app/templates/play/campaign-view.pug
app/templates/play/play-level-view.jade
app/views/core/SubscribeModal.coffee
app/views/courses/TeacherClassesView.coffee
app/views/play/CampaignView.coffee
app/views/play/level/PlayLevelView.coffee
static-mock.coffee

We do want to include the "Request a Quote" action in the header, based on data; but we had only finished the test and picked the winning variant for Ozaria, forgot to do it for CodeCombat. Did that, and while I was at it, removed a bunch of old A/B testing code. Manually ran through SubscribeModal, CampaignView, PlayLevelView, and HomeView for a minute to make sure they didn't obviously break.

Remove old A/B test code, including picking winning variant for request a quote

---

app/views/HomeView.coffee

Small fix that ensures the iframe has been rendered before we try to attach the vimeo player.
Removes error noise.
Tested manually on localhost.

🐛 Vimeo error message on homepage

---

app/core/vueRouter.js

Changing default behavior of the parents from Drift to self-signup.
Route has been made the same as /live-classes route and has type overrides based on query params.
i.e.
`?type=parents` will revert original behavior
`?type=call` will show direct sales number.
Tested manually.

/parents route changed to use self-signup by default

---

app/templates/core/subscribe-modal.jade
app/views/core/SubscribeModal.coffee
app/views/landing-pages/parents/PageParentsSectionPremium.vue

This is a small step to our new individual pricing model and online classes payment structure.
Here is the subscription modal by default.
Gif below shows the modal through parent page flow. This should reduce confusion by only showing what the user clicked.
Removed monthly option from the parent page.

Remove monthly subscription option from parents page

---

app/locale/en.coffee

Right now the text for Regeneration covers the number stats, as seen below:
However, replacing that with just "Regen" fixes the problem of overlapping text, as seen here:
This PR will fix the issue of overlapping text 👍

Replace "Regeneration" with "Regen" to fix overlapping text

---

app/components/timetap/TimeTapDebugPage.vue
app/core/Router.coffee
app/core/vueRouter.js

Following instructions to help TimeTap debug the iframe in private browsing.
Looks like this:

TimeTap page to debug iframe in private browsing

---

app/schemas/models/user.coffee

Unblocks the client from requesting different subscription plans.
These plans are then verified on the server where the verification is done.
We are unable to make these subscription plans nicer as they match the stripe id which is immutable.

Add additional subscription plan requests

---

app/views/core/SubscribeModal.coffee

We have country specific pricing for our monthly subscription and our annual subscription.
Unfortunately the country specific pricing wasn't being applied to the annual subscription automatically leading to confusing pricing suggestions as shown beneath.
Currently what modal looks like if in a discounted region:
This fix ensures that the country coupon is applied. I added an edge case for brazil due to issue with the prior brazil coupon not correctly discounting.
Gif shows fixed behavior when doing a manual test. Because this is additive and still allows manual coupon adding this is a very low risk change.

Fix automatic application of coupons

---

app/core/application.coffee
app/core/initialize.coffee

Context is written up in the private Ozaria PR: https://github.com/codecombat/ozaria/pull/653
In short event validation can add another 200% of time to every frame.
Currently we hard coded whether event validation was turned on so that codecombat.com has a great experience but any other production domains have a slower experience (although playable).
This general fix should provide smoother framerates on low end hardware such as chromebooks in environments such as our domain in china.
cc/ @smallst

Fix capstone performance by removing backbone mediator event validation

---

app/views/landing-pages/parents/PageParents.vue
app/views/landing-pages/parents/PageParentsJumbotron.vue

Tweaks the griffin image to move out of the way of the heading.
Also added overflow-x to prevent the bit of space creating a horizontal scroll to appear in the page.
Note that localhost doesn't have the font in production (in screenshot).
I also tried to quickly animate the clouds but found that animating separate background-positions doesn't work. Next time will overlay some divs behind the jumbotron with a cloud in each div, and translate those divs instead of one background-position.
Tested in chrome and Firefox. The gif was from firefox:
Example of image:
Example of tiny space to the right.

Griffin responsiveness to Parent Page and jumbotron overflow-x

---

app/locale/en.coffee
app/styles/courses/teacher-class-view.sass
app/templates/courses/teacher-class-view.jade
app/templates/teachers/hovers/progress-dot-all-students-single-level.jade
app/templates/teachers/hovers/progress-dot-single-student-level.jade
app/views/courses/TeacherClassView.coffee

This was so confusing for teachers, so I:
- Renamed from "Assign up to level" to "Lock levels start at"
- Put lock images and faded the level dots for locked levels
- Added "(Locked)" to hover labels
(In the .gif I didn't have "(Locked)" on not-started levels, but I fixed that.)
I tested it as shown in the .gif but didn't test otherwise.

Make content locking more obvious

---

app/lib/surface/Surface.coffee

I looked for a while to figure out what might have been causing the bugs where sometimes the fade screen or the 1-framerate paused state would persist when they shouldn't have, but couldn't get to the bottom of it. But, I made some changes to improve the situation:
* Only dim screen at end of ladder levels.
* Don't pause/reduce framerate when ended/AFK in game dev or level editor.
* Fix the paths continuing to animate when paused by not calling `updatePaths()` after pausing the paths.
It's possible that changing the order of operations here could have solved the problem in other level types, but I'm not sure.

Improve end-of-level fade/pause behavior

---

app/views/play/level/tome/SpellView.coffee
bower.json
ozaria/site/views/play/level/tome/SpellView.coffee

This upgrades the ace editor to version 1.4, which has proper support for touchscreen devices. It builds on #5553 with a bugfix for how we highlight indentation in python code, but otherwise it should behave the same as #5553.

Update ace editor version

---

app/locale/en.coffee
app/views/landing-pages/parents/PageParents.vue

This is a very small fix that addresses two tasks.
1. Updating the top marketing banner on the CodeCombat homepage
2. Fixing an image overflow problem on /parents page when viewed on mobiles or small width screens.
To test run local proxy and manually check the home page and /parents page.
I manually tested on Chrome and Firefox.
Very low. Small and simple changes.
After overflow fix:
before

Remove top banner and fix parent page overflowing

---

app/views/landing-pages/league/PageLeagueGlobal.vue

Padding between "How it Works" and "Season Arenas" sections.

Added padding between 'How it Works' and 'Season Arenas' sections

---

app/views/landing-pages/league/PageLeagueGlobal.vue

Changed font to 60px instead of 70px since that was taking letters out of frame. Copied design changes from Figma.

increase font size of esports-header

---

app/views/landing-pages/league/PageLeague.vue
app/views/landing-pages/league/PageLeagueGlobal.vue

The routing to the page was passing through a parent component. When the route changed the exact same components were being used and Vue was more than happy to keep them the same.
To force vue to change the page on a url change (even if it is the same component), we can use a key. Here I've opted to use a full URL key which will re-render page when any url changes happen.
Tested manually by navigating to the /league page and testing clicking on the clan dropdown as well as the clans in the leaderboard.
Tested clan from perspective of anonymous, logged in, in clan, and owner of clan.

Fix esports routing and clan CTA

---

app/styles/style-flat.sass
app/views/landing-pages/parents/PageParentsJumbotron.vue

- Decrease the text-size so that it fits on 3 rows
- The CTA can be moved up so that it doesn't cover the boy's face
- Boy's image can be moved up so that we see more of it above the fold
Desktop/Laptop
iPhone5/SE
iPhoneX
Galaxy S5

Hero Section: decrease size of header text

---

app/core/store/modules/seasonalLeague.js

Currently if you navigate to /league page and select a clan there are duplicate AI sessions shown.
See screenshot below after navigating to https://codecombat.com/league/stem-spartans
A more robust fix tackles this on the server side. However temporarily for agility this can be solved on the client.

🐛 Remove duplication of AI session from league clan page

---

app/core/vueRouter.js
app/views/landing-pages/parents/PageParents.vue

When navigating between different vue router pages the scroll isn't reset. This can lead to users looking at the bottom of a page when navigating.
1. Navigate to codecombat.com/league
2. Scroll down, and then click "Parents" in the navigation
3. Notice that the page doesn't scroll back to top.
Gif recorded in Chrome.
These are the same steps to test locally.
I also manually tested back and forward navigation.
I initially explored using the [`scrollBehaviour`](https://router.vuejs.org/api/#scrollbehavior) method on the vueRouter constructor. However it doesn't work in `abstract` mode. We have set this mode because the vueRouter is controlled by the backbone router.
Thus I added the scroll behavior in a global `afterEach` hook. This ensures that if the user navigates to a different path the …

🐛 Scroll position shouldn't be saved between vue router pages

---

app/views/landing-pages/parents/PageParents.vue

Small fix removing the background graphic from the parents page video.
Tested manually in local development environment.

Remove background graphic from parent video

---

app/core/store/modules/seasonalLeague.js

Ladder doesn't show 4 above and 4 below if logged in user isn't in the top 20 of the ladder. There is also the following error in the console: `app.js:82 TypeError: Cannot read property 'top' of undefined`
The error is due to accidentally referencing vuex `state` rather than the in scope variable.
Fixed for both ladders by using the correct variable 🤦 .
Check out local proxy. Navigate to /league page.
Test on internal user with issue: andrew+student912@codecombat.com
Can also check leaderboard still works anonymously.

Fix four above/below logic in league ladder

---

app/core/vueRouter.js
app/locale/en.coffee
app/templates/base-flat.jade
app/views/core/SingletonAppVueComponentView.js

Updates the global navigation bar to remove "Request a Quote" and "About". Instead adds "Esports" with link to /league.
There was also a bug where switching between vue router pages didn't re-render the backing Backbone.js view. This can be fixed by triggering a render after any vue navigation.
1. Spin up local proxy (`npm run proxy` with `npm run dev`) and navigate to localhost:3000
2. Note nav bar changes
Clicking between the two correctly highlights them.
Vue component instance gets inserted into new backbone view after render. Risk of vue router bug can break website. However I think in this case manual checking confirms it as working without the surface area being very high.

Esports navigation header

---

app/core/store/modules/seasonalLeague.js

Currently it's possible for your codepoints rank to be unknown, leading you to not appear in the codepoints leaderboard.
There are also variables referencing the league ladder causing league values to appear in the codepoints ladder.
Because the only usable information from the ranking endpoint is the codePoints totalScore, I am using a guess to see if the user is in the top 20. If the user is tied for 20th the heuristic may fail to guess correctly. However it works in most cases which currently aren't working.
Future work is to return some kind of identifier from the rankings endpoint or fix the ranking.
In production it looks like this (hasn't detected my user correctly):

Fix CodePoints ladder if not in top 20

---

app/styles/style-flat.sass
app/views/landing-pages/parents/PageParents.vue

Fixed extra space in parent page for mobile device and add padding for course offering table.
1. Remove extra space from `Remove Learning` Section
2. Display `Pet following yellow dotted path` image which was not displaying before and causes extra space for "Course Offering" Section, Also rotate (-15 degree) this image to point `Course Offering` for mobile devices.
3. Added padding for `Course Offering` table.

Fixed extra space in parent page for mobile devices

---

app/core/store/modules/seasonalLeague.js
app/views/landing-pages/league/PageLeague.vue
app/views/landing-pages/league/PageLeagueGlobal.vue

This PR fixes some esports page bugs.
1. Fixes race condition where two sessions appear next to one another
2. Clear vuex ranking sessions between pages in case the user isn't in that clan or leaderboard.
3. Also stops accidental global session load even when you aren't looking at global version of page.
4. Fixes navigation of clans when clicking on leaderboard or dropdown. As well as browser back and forward arrows.
5. Handle direct navigation to incorrect or malformed clan slug
6. Handle creation of clan without accidental chinese clan name.
- Start a dev server connected to the proxy (or production) with `npm run dev` and `npm run proxy`.
- Spy on my account: andrew@codecombat.com
- Navigate to codecombat.com/league . It may take a couple refreshes but you may be able to repro the …

🐛 Esports league page ladder and clan loading

---

app/schemas/models/clan.schema.coffee

This is required to create a bucket property to store information letting us locate required autoclans efficiently.
Haven't specified the properties explicitly as they are subject to change and I don't want to break any clans that have any of these properties.
In the future will use these properties to more efficiently query for autoclans. I.e. clan.metadata.ncesId will have link to the school ncesId.
Also cleaned up terminology of the various kinds that we want to have.
Will be merging and deploying this today for Academica work.
Risk is low for changed enum properties as they aren't in use yet (only classroom and teacher are used).
The metadata property allows for any properties while we iterate on the data required.

Add autoclan metadata and clean up kind

---

app/locale/en.coffee
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/ClanCreationModal.vue
app/views/landing-pages/league/components/Leaderboard.vue

We're using a legacy & internal name on the esports page leading to confusion for customers.
This change replaces the usage of the word `clan` to the word `team` on the /league page.
Translation effort is out of scope of this PR. This PR is more of an initial quick fix. I've added some small i18n improvements where it makes sense but the page remains mostly hard coded in English for now.
- Change static text from `clan` to `team` across page and Clan/Team update modal.
- Replace `Clan` with `Team` in autoclan descriptions that are automatically generated. Quick hack as we want to better handle this server side.
Minimal risk as text changes.
Navigate to localhost:3000/league and note the lack of clan verbiage on the page.
Clicking on an autoclan will no longer have `Clan for` description …

Clan to Team esports page renaming

---

app/templates/base-flat.jade

There is a bug on the home page preventing a button from working correctly.
Reproduce the bug by navigating to the home page, codecombat.com, and then click on Profile.
Also checked some other links that use the nav bar.
This fixes a broken nav link and is a relatively low risk. I tested across the following pages:
- Home page
- Parent page
- Esports page
- Teacher dashboard

Fix incorrect link interpolation in nav bar

---

app/core/Router.coffee
app/core/store/modules/clans.js
app/views/landing-pages/league/PageLeague.vue
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/ClanSelector.vue

Fixes some small issues with the esports league page making the experience more enjoyable.
- Changes eSports text to esports.
- Ensures we don't accidentally set a clan in the vuex store with fewer fields than previously loaded.
- Fixes an additional Clan -> Team terminology change.
- A third party redirect for academica. Adds redirect for the url `/league/academica`.
Tested manually via local development with both a user in teams and looking at the global page.
These changes can be manually by spinning up local development via `npm run dev` and `npm run proxy`.
Navigating to `localhost:3000/league/academica` leads you to the school network team page.
The page should look like so:
Prior to this PR the page looks like this:
Note the incorrect team name.
Risk is low as these changes are …

Academica third party esports bug fixes

---

app/models/User.coffee
app/templates/courses/courses-view.jade

Currently our Academica partners need their student user's to be able to engage without a teacher or classroom.
This is a low risk and informative PR to add specific information for these students to access free content without a teacher or school intervening.
Next week we will be handling this more systemically for all students, thus keeping this low cost and easy to remove later.
The user flow for a Clever student is as follows:
- They log in through Clever.
- Get dropped in the student dashboard.
- See this announcement if they are Academica student and engage.
There is no easy way to test the Clever sign up flow, but you can emulate being a student in the Academica team.
For all other students they will not see the announcement.
You can test by spying on various students and …

Academica team - student call to actions

---

app/templates/play/ladder/ladder.jade
app/views/ladder/LadderView.coffee

The default experience of [this page](https://codecombat.com/play/ladder/blazing-battle) looks really rough.
This is the page currently live in production (screenshot taken in Chrome):
Note that the background container doesn't respond to the length of the ladder and leaks into the footer!
In addition to this if the user extends the ladder it doesn't bring the background with it.
This change is extremely small, but fixes up the responsiveness of the ladder pages. See screenshot section for the fixed screenshot and gif.
Original page isn't using original bootstrap semantics properly.
Adding the `row` class correctly propagates the page height across the various ladder pages without changing the bootstrap tab semantics.
This was tested across our various ladder pages.
Spin up a local …

Responsiveness fix for esports ladder level page

---

app/lib/loadAetherLanguage.coffee
app/vendor.js

We noticed that esper.js was loading on the homepage, when it's not needed until you are playing/editing a level, simulating, verifying, etc. in game. I moved it from a vendor.js include to the same way we load its plugins, so that any time we needed to load an esper plugin, we first load esper itself.
I also load esper.js and its language plugins consistently from the non-hashed JS path, because the web workers don't currently know how to use the hashed version, and so they would be doing a separate load anyway. Probably fine because it changes so infrequently, but if we wanted, we could move web worker JS loads to use the hashed JS path as well by passing that to the web workers as future work.

Load esper.js later for better performance

---

app/core/Tracker2/DriftTracker.js
app/core/Tracker2/index.js
app/core/store/modules/me.js
app/views/landing-pages/parents/PageParents.vue

Also, update logic to not show Drift for logged-in home players.
Also, remove extraneous `this.enabled = false` guards against Drift loading in China, since the Drift tracker is already not initialized when in China.
There are also a couple services that I don't think we use in China that I moved to the global-server-only list.
I'm not very familiar with this code, especially the async loading parts, so could use eyes on it. Wanted to get something out soon to help sales team not get buried in irrelevant chat messages. I tested locally being logged into nothing, home account, teacher account, and on/not on /play pages, and moving between those.

Don't load Drift unless/until it's needed.

---

app/core/api/leaderboard.js
app/core/store/modules/seasonalLeague.js
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/Leaderboard.vue

Global:
Clan-specific:
Was just practicing Vue a little more. I wonder if I'm not missing something, though, since this is a pretty hefty amount of boilerplate to load a value from the server and display it in the template?

Add player count to AI League arena leaderboard

---

app/locale/en.coffee
app/styles/play/campaign-view.sass
app/templates/play/campaign-view.pug
app/views/play/CampaignView.coffee

We want home users and students with a certain amount of codepoints to be able to find the seasonal esports arena.
In order to do that we are adding a button that links directly to the esports arena from CS1 and Dungeon campaigns.
This button is initially brown and not very visible. When the user gets over some (not decided) threshold of codepoints, we make the button more visible and potentially even trigger an animation. In this PR the button changes to red for initial implementation.
First implementation has codepoints threshold set to 30 points. This is enough to ensure the user has played a couple practice levels.
This can be tested by spinning up a local proxy: `npm run dev` and `npm run proxy` running at the same time.
First test:
Login as a home user.
Navigate to …

Esports link from home and student first campaign view

---

app/lib/surface/LayerAdapter.coffee
app/lib/surface/SegmentedSprite.coffee
app/lib/surface/SingularSprite.coffee

Our game view or renderer dynamically builds spritesheets of all the entities or thangs that are in a level.
This is an optimization to pass the graphics card a single large image with all the required sprites to animate and play the level.
However if a new sprite is drawn midway through play it must be added to the spritesheet. The new spritesheet has the new art, and the old own persists in memory until either a browser refresh or page crash.
This means that over a period of play, if there is dynamic rendering, we get a memory leak.
For the last two years we've solved this memory leak by refreshing the page between every level. This has blocked many other optimizations of resources we don't want to be constantly fetching.
This PR was done specifically for the Blazing Battle arena but …

🐛Fix spritesheet builder memory leak

---

app/core/application.coffee

We are improving Drift widget handling, but there are still edge cases where both Zendesk and Drift can be active at the same time. This change lets them "co-exist" side by side happily 😀 
- Check out `matias/zendesk-widget-offset`
- Start up local dev environment and go to the homepage
- Open the browser console and write `zE('webWidget', 'open') ; zE('webWidget', 'show')`
- Notice the Zendesk widget appearing side-by-side instead of overlapping

Zendesk widget offset improvements

---

app/locale/en.coffee
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/Leaderboard.vue

Currently we have two leaderboards on /league , but only link to the arena leaderboard.
This change provides a button to easily get users to levels that can give codepoints.
This can be tested manually by spinning up a local dev environment.
Use `npm run dev` and `npm run proxy` out of the client repo.
Expected behavior for clicking the codepoints button is:
- For student account, navigate student to dashboard.
- Home user or anonymous, navigate to campaign map.
- Teacher will get redirected to their teacher dashboard.
Pull request also addresses and improves responsiveness of the page and leaderboards.

Add CodePoints button from league page

---

app/templates/courses/courses-view.jade

Very small change and very low risk.
Swaps order of codePoints link and arena link so that users are more likely to interact with the codepoints link.
Otherwise users are interacting with arena before getting our more gentle ramp up levels.

Update Academica cta to route to codePoints first

---

app/core/Tracker2/DriftTracker.js

We don't want to try and identify users when drift isn't loaded.
In the past we have had drift constantly loaded, but now load drift for only certain conditions.
This issue comes up in production but not in local development environment. This occurs because we turn tracking off in local development so we don't add our own internal data to analytics.
Thus we need to do a bit of setup to locally reproduce the bug.
First to find the source of the bug I noticed it was during the `identify` call.
This lead me to Tracker.coffee that is the controller for all tracking.
Here there is a method `shouldTrackExternalEvents` that will block tracking when on local development.
https://github.com/codecombat/codecombat/blob/107748d/app/core/Tracker.coffee#L120
I set an early `return true`.
I also needed …

Handle unloaded Drift when identifying

---

app/core/Tracker2/DriftTracker.js

This pull request fixes some more subtle issues in Drift. Specifically it resolves the issue that turns up when you navigate to the following page: https://codecombat.com/students?_cc=SafeGateStone
Navigating to this page creates the following errors:
Although this error appears the Drift widget still works.
Why this error occurs because of a race condition.
Because we call `updateDriftConfiguration` on route updating as well as when initializing drift. It is possible for `updateDriftConfiguration` to trigger a second load before the first one has completed.
Make `updateDriftConfigration` async and check to see if the `initializationComplete` promise is complete. Then check for Drift and potentially trigger an initialization.
Spin this up locally. No other changes are needed.
Use `npm run …

Prevent drift from loading more than once

---

app/lib/surface/SegmentedSprite.coffee

#6195 describes an issue where game play freezes when playing a Game Development level game.
This is a simple, safe change that does not fix the root cause, but that enables the game to continue when the problem occurs.

Handle missing mcPool gracefully in spriteSheet buildMovieClip (#6195)

---

app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/SectionFirstCTA.vue

When we are looking at esports teams it's frustrating scrolling down as there is a large block of marketing before the team details.
This is a first step in moving a marketing section beneath the team.
Because we will be shortly adding customization so that teams can feel unique, we want them to also sit more prominently on the page.
Moved this marketing section to sit beneath team when on a custom team page:
Required CSS modifications so that the scoped CSS can modify the nested children.
This can be tested on local proxy. Use `npm run dev` and `npm run proxy` to spin up a local environment.
As any user type the global league page should appear unchanged. localhost:3000/league should have the marketing section as the second section on the page.
I.e. (awkward screenshot showing the bottom …

Move marketing section when looking at an esports team page

---

app/core/api/clans.js
app/core/store/modules/clans.js
app/core/utils.coffee
app/lib/surface/SegmentedSprite.coffee
app/locale/en.coffee
app/templates/courses/teacher-class-view.jade
app/templates/courses/teacher-courses-view.jade
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/ChildClanDetailDropdown.vue
app/views/landing-pages/league/components/SectionFirstCTA.vue
package-lock.json
package.json

We want it to be easier for parent umbrella clans to filter and search for any of their children.
This PR includes an initial component that can be fed a list of teams, and creates a fuzzy search input for exploring these teams. The teams can also display other data such as member counts.
The use case is that `school-network` and `school-subnetwork` type teams will be able to see the teams that make them up. It's also sorted by size.
Server portion has been merged but not deployed.
The server returns a list of teams with membership counts.
On the frontend we use a fuzzy search library to search, filter and sort the results to display to the user.
This is all encapsulated in a single search component.
Clicking any of the clans will link to their page.
Awaiting server portion to ship before …

Initial school clan UI search system

---

app/core/Router.coffee
app/core/vueRouter.js
app/schemas/models/clan.schema.coffee
app/views/admin/PageClanEdit.vue
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/ClanSelector.vue

For certain esports teams we want to be able to add custom images. This PR adds an internal admin Clan edit page for editing clans and uploading custom images.
New internal admin tool at route: `/admin/clan/:clanID`
The new `esportsImage` property uploads into our static file system and replaces the static image on the teams league page.
These gifs provide more context.
Uploading a new image:
Saving the uploaded image:
The final result: 
Vs the default static image:
As this PR includes mostly UI additions, it was manually tested against a local mongo instance.
To successfully reproduce the gif animations above, the server portion needs to be running locally - this allows admin users to edit the esportsImage and clan in the put request.
Low risk as most of the logic is internal tooling …

Custom esports images for teams

---

app/views/landing-pages/league/PageLeagueGlobal.vue

Classroom and Teacher teams are populated automatically and don't need a manual button.
This also stops users accidentally or intentionally joining other classes.
- Hide the "Join Team" button based on the 'kind' on the team.
Checkout these changes with `npm run dev` and `npm run proxy`.
Navigate to http://localhost:3000/league and navigate different teams.
This gif navigates using Academica team, and drills down into a teacher and classroom. Note the lack of "Join Team" button.
Updated text when button is not showing:
Risk is low, and this is intentionally a quick UI focussed fix.
Next steps may be to modify behavior of the joinClan api endpoint.

Hide teacher and classroom esport team join button

---

app/core/Router.coffee

Redirect students away from the clan page routes.
This limits student interaction to teams to /league routes.
Minimal risk. Tested manually and can be checked on our staging environment.

Redirect classroom user away from clan pages

---

app/assets/javascripts/web-dev-listener.js
app/assets/web-dev-iframe.html
app/templates/play/level/web-surface-view.jade

I think going from child to parent directly used to work, but no longer does, but it's pretty easy to pass that one piece of info we need to the iframe on creation via a URL parameter.
Also not calling `postMessage` to log an error if we haven't received a message yet (since it wouldn't know where to send it). Guessing that only happens on startup and those aren't the kind of errors we are trying to communicate.

Update web dev iframes to not use blocked methods of cross-domain communication

---

app/views/landing-pages/league/PageLeagueGlobal.vue

This is not a very good design, and I just hide the guy when it's too small, but likely better than nothing, as I want to show off the hero and Eugenio's bio.
I also move AI League logo up a bit on mobile, as it was overlaying right on top of Eugenio's head.

Add custom hero details for Team DerBezt

---

app/views/landing-pages/league/components/ClanCreationModal.vue

As we have been "protecting" the name / slug field in the esports team system, we've added a `displayName` property.
We also have UI that makes it look like users can update their clan from private/public once it is made.
This PR addresses both those UI issues with some light changes.
The private/public toggle is removed when editing:
And the team name updates the displayName.
There is also no reload or UI update after the modal is closed.
Reloading the page updates the team.
Low risks. May be a bit confusing when mixing with the old clan page as those pages don't look at `name` at all.
In the future we can migrate some of the displayName uses over and fix the edit over there.

Update Team edit modal to use displayName

---

app/locale/en.coffee
app/locale/es-419.coffee
app/locale/es-ES.coffee
app/models/User.coffee
app/styles/home-view.sass
app/templates/core/subscribe-modal.jade
app/templates/home-view.pug

Finally getting around to it. (Mentioned [on forum 2.5 years ago](https://discourse.codecombat.com/t/gem-purchases-will-be-turned-off-in-the-near-future/15697/2) and then forgot to actually turn them off.) Individually buying gems as an "in-app purchase" isn't really in line with our mission, plus kids would sometimes buy them without parental consent–no bueno!
Players can still get gems by playing the game, and extra gems still come with the premium subscriptions.

Disable buying gems

---

app/core/Router.coffee
app/core/api/clans.js
app/core/vueRouter.js
app/views/admin/PageClanEdit.vue
app/views/admin/PageClanSearch.vue

This is paired with a server change -- thus doesn't work on proxy yet.
Adds a new admin only route (checked client & server side) that allows for searching of clans by school and district.
New route: /admin/clan
When the user clicks on a school or district in the algolia dropdown, we try and fetch any related clans and append them on a list beneath. (Really simple and naive working behavior).
Here is a demo of it working with a mock clan. Hence the errors as my local db is missing schools and districts.
Clan that is appended is always "Doral Academy" -- hard coded.
The risk is low because this is internal facing only.
Also why it looks so bad on the first pass.

Admin school and district team search

---

app/core/store/modules/products.js
app/views/landing-pages/parents/PageParents.vue

Our pricing grid on the parents page doesn't adjust to local prices.
This is jarring when the stripe payment adjusts to a different price.
This PR moves the coupon logic into the vuex store making is possible to fetch the dynamic price on the parents page.
Navigate to: https://codecombat.com/parents?coupon=brazil
Notice on the pricing grid the student pricing per year is $99, which is the American pricing.
It should instead be $39.60
Spin up local dev and proxy: `npm run dev & npm run proxy`.
Navigate to localhost:3000/parents?coupon=brazil
The local pricing has been applied correctly:
Other cases that can be checked are:
- no coupon: falls back to $99
- invalid coupon: falls back to $99
This is a small change only improving the UI experience. The payment system isn't touched and thus I …

Apply coupons to local price on /parents pricing grid

---

app/locale/locale.coffee
app/views/contribute/DiplomatView.coffee

The `język` means `language`
It is redundant to display the `język polski` in the list of languages.
It is correct yet clear to display just `Polski`
It is also easier to search for the language as it respects the lexicographical order of languages names.
-----
By the way, in English all the [language names in the list should be capitalised](https://www.grammarly.com/blog/capitalization-countries-nationalities-languages/). I think it is safe bet to capitalise them in i10n forms too. It would make the UI/UX friendlier - clean display, nicely sorted list.

Remove redundant noun 'język' for Polish language

---

app/views/admin/InputClanSearch.vue
app/views/admin/PageClanSearch.vue
app/views/landing-pages/league/PageLeagueGlobal.vue
app/views/landing-pages/league/components/InputClanSearch.vue

This is the user facing component of the fuzzy clan search.
Intention is for anyone to be able to find the team they are looking for.
Whether it is a school, district, custom team or anything in between.
This team search component has been placed on the global league page (codecombat.com/league) between the global stats and the rankings. This is consistent with where the subclan search appears when you are viewing a network or subnetwork team.
The server endpoint is done. This is a very similar Vue component to the `ChildClanDetailDropdown`, but simplified as any clan can be retrieved.
In the context of the global league page:
The manual component can be tested by using a local database with your local clans collection filled.
Run the server on master branch and this branch as the client. …

Input team/clan search UI and UX

---

app/core/application.coffee
app/core/services/zendesk.coffee
app/views/core/CocoView.coffee

The Zendesk email widget would be very rarely needed, but it was being loaded at all times. I moved it to load when you start to use it.
Not sure if this is the best pattern for lazy loading a service like this; modeled it after some code I saw in `app/core/services/paypal.coffee`.

Only load Zendesk when we are about to open it, not on page load

---

app/templates/courses/enrollments-view.jade

Issue found while checking teacher dashboard for context on purchasing licenses.
Very small risk. Escaping interpolation like this does open up the possibility of a vulnerability, however we aren't inserting user generated content.
Before fix:
After fix:

Fix confusing student enrollment characters in teacher dashboard

---

app/views/play/CampaignView.coffee

Fixes an error currently in production when accessing esports arenas through codecombat.com/play route.
The error occurs as the tooltips are not initiated on this page.
Thus clicking the button fails to open a tooltip.
It's currently fine to fix by turning off the esports arena links from the campaign overworld.
They are still accessible from within the various campaigns.
There will also be future work to add a global button to the bottom right that links to esports arenas.
Simple change and can be easily verified with `npm run dev` and `npm run proxy`.
Navigate to localhost:3000/play and note the buttons are missing. (See screenshot).
On a campaign the buttons are visible. I.e. game-dev

🐛 Hide broken campaign view esports link

---

webpack.production.config.js

Reference to duplicate PR in Ozaria: https://github.com/codecombat/ozaria/pull/515
Details on deployment and testing behind that link.
We'll be able to clean this up once we upgrade Node and Webpack.

Deploy Vue in production mode

---

app/lib/world/rectangle.coffee
test/app/lib/world/rectangle.spec.coffee

This PR rewrites parts of the Rectangle class for correctness and speed. It also adds 5 utility static methods to `Rectangle`, of which only some are used during testing. The relevant cases that the old methods failed have been added to the test suite.
Some brief benchmarking suggests significant performance improvement: ~10x in `intersectsRectangles`, ~5x in `distanceSquaredRect` and `boundingBox`, and optimizations in other methods. `intersectsLineSegment` is ~4x faster and no longer always returns false.
Performance comes from using new algorithms and reducing the creation of temporary Vectors, especially in smaller methods like `distanceToPoint`.
Note: `add` and `subtract` reference an undefined attribute `@pos`, are they used anywhere?

fix and optimize rectangle calculations

---

app/models/User.coffee
app/schemas/models/user.coffee
app/templates/base-flat.jade
app/templates/courses/teacher-classes-view.jade
app/views/courses/TeacherClassesView.coffee

Also, add schema update for extra APIClient permissions (for example, to be able to grant licenses to users).
Not the prettiest when hiding some of these elements, but perhaps an ok start.
Before, for teacher who would have dashboard iframed into another site:
After:

Don't show irrelevant UI elements to partners on teacher dashboard.

---

development/docker/Dockerfile

Current project on github doesn't have a "master" branch.  It appears this is now called main.
https://raw.githubusercontent.com/rbenv/rbenv-installer/main/bin/rbenv-installer

Updated rben-installer path to match actual

---

app/styles/play/menu/inventory-modal.sass

Shifts pet positions so the pet does not appear to be right in front of the hero

Shift pet position

---

app/templates/vue-base/base-empty.pug
app/templates/vue-base/base-flat.jade
app/views/core/VueComponentView.js
compile-static-templates.coffee

- separate vue-base templates to a folder so that all templates are not included in app.js
reduces the size from 1MB to 700kB

reduce app.js bundle size

---

app/locale/en.coffee
app/templates/courses/enrollments-view.jade
app/templates/teachers/teachers-contact-modal.jade
app/views/courses/EnrollmentsView.coffee
app/views/teachers/TeachersContactModal.coffee

replace starter licenses with student and homeschool licenses

---

app/views/ladder/MyMatchesTabView.coffee
app/views/ladder/components/Leaderboard.coffee
app/views/ladder/components/Leaderboard.vue

make a better leaderboard to see where player himself is,  here are 3 different situation example:
just in the current leaderboard, do nothing except highlight himself
while at the edge case we expand the leaderboard to contains himself and below 4 players
while out of leaderboard adding a `...` line and display 4 above and 4 below

display myranks in leaderboard

---

app/core/Router.coffee
app/core/api/payment-group.js
app/lib/paymentUtils.js
app/locale/en.coffee
app/schemas/models/user.coffee
app/views/HomeView.coffee
app/views/core/SubscribeModal.coffee
app/views/payment/PaymentStudentLicensePurchaseComponent.vue
app/views/payment/PaymentStudentLicensePurchaseView.vue
app/views/payment/paymentPriceHelper.js

there is a fallback to the old payment way if new stripe checkout fails
On click of Buy Now is Subscribe Modal, we redirect users to stripe checkout

move coco premium purchase to stripe checkout

---

app/views/editor/ForkModal.coffee

When you fork a level all task statuses are copied.
Set the `complete` property of each task to `false` before creating the forked level.
1) Create a new level and mark some of its task completed.
2) Fork a new level from it.
3) None of the new level's tasks should be completed.

Level Forking should reset all tasks

---

app/lib/surface/Surface.coffee

For some levels we need better control on the camera and using Scripts for interactive stories. This way we won't break existing levels as the added property is `preventZoomToHero` is opposite to Surface.zoomToHero.

Allow to prevent camera tracking of the Hero

---

app/styles/bootstrap/_variables.scss
app/styles/common/common.sass

I don't understand why, but the `z-index` was removed from autocomplete by this commit:
https://github.com/codecombat/codecombat/commit/cd33376#diff-06bfc89545a034a8ee956a922c5aedfc071c159cf0978fdfafd505150fe27eadL217-R231
Now it is back, and the autocomplete is visible:

Treema autocomplete z-indexed behind ModelModal

---

app/styles/common/ace-diff.sass
app/templates/teachers/teacher-student-view.jade
app/views/teachers/TeacherStudentView.coffee
package-lock.json
package.json

Currently supported:
1. add ace-diff with basic usage in teacher-student-view.
Better to support:
1. localize the solution so don't have the comment be diff [ -x ]
2. ignore the stat.completed=true playerCode. [ ]
3. set the ace-diff div fit the height of player codes or solution codes [x]
4. support multiple solutions like before [ ]
5. maybe more views ? [ ]
6. fix the testing. [ ]

add ace-diff to coco

---

app/styles/play/campaign-view.sass
app/views/play/CampaignView.coffee

The home version map made scrollable on touchscreens.
Pls check screen recording gif:

Bug: on ipad, the home version map can not move by finger

---

app/core/Tracker2/index.js

store wasn't passed to google-tracker causing it to fail since .isAdmin check failed and thus promise got rejected
why wasn't this caught in console logs?
allSettled returns array of results with reject/success state where we can see result of promise. We weren't iterating over it thus ignoring the error

fix google-analytics tracking not working

---

app/lib/surface/Lank.coffee

Sometime we need to put texts on the game field that doesn't scaling on the camera zoom.

Added sayLabelOptions groundLayer:boolean to put texts on the game layer

---

app/views/ladder/LadderTabView.coffee

issue: our `my-row` doesn't contains a `ageBracket` so always show "open". 
this pr to fix this issue

add ageBracket for leaderboard-my-row

---

app/views/ladder/components/Leaderboard.vue

`Array.concat` is no longer supported in node14. using `array.concat` instead :joy:

fix Array.concat

---

app/views/play/level/tome/editor/autocomplete.coffee

In the level we have settings to change component based autocomplete to level specific.
The current PR extends it and allow entries there work as additions and extend autocomplete without extending doc pallete.

Level autocompleteReplacement can work as additions

---

app/lib/surface/Dimmer.coffee

Currently we highlight all "talking" thangs, it can be useful for "auto" highlighting, however I can't imagine the case for that and I'd prefer to manually control what to highlight instead of dimming what we don't need.

Don't dim talking thangs

---

app/lib/surface/LankBoss.coffee

For early levels we don't want to show the target mark as it ovelays with ground points. With the option in UI system showTargetMark we can disable it for certain levels. By default this option is true.

World.UI can control when we want to show target mark

---

app/styles/courses/teacher-class-view.sass

now the details panel is 9999 z-index and cover other div and makes other div unclickable 😂

make details unclickable so that it won't cover other div

---

app/views/teachers/TeacherStudentView.coffee

Ignored all `ladder` and `project` levels from performance calulation.
In order to keep other values intact, I've duplicated all calculations  with `performance` prefix.

Fix student pacing suggestion calculation to ignore arena/project levels

---

ozaria/site/components/teacher-dashboard/BaseResourceHub/index.vue

The left-hand panel ovarlaid on top of the footer. See fix on screenshot below:

DT Resource Hub: Left Panel visual polish bug

---

ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ModuleRow.vue

Row height fixed, in order to border on hover not to change height. Pls check difference below:
Before / After

DT: Curriculum Guide content rows shouldn't move upon hover

---

app/components/common/Navigation.coco.vue
app/components/common/Navigation.ozar.vue
app/templates/base-flat.coco.pug
app/templates/base-flat.ozar.pug
app/views/core/CocoView.coco.coffee
app/views/core/CocoView.ozar.coffee
static-mock.coffee

Most pages with `?landing=true` in the URL (including target /parents page) will now hide extraneous header/footer nav, focusing new visitors on the product offering at hand.
Not sure if this is the cleanest way to do this kind of conditional top nav display in Vue, and base-flat footer `if` isn't very elegant.

Add ?landing=true option for more focused top/bottom nav

---

app/views/efficacy/EfficacyView.vue

The texts generated by `data-i18n` tags doesn't load automatically for vue components in production.
Using `$t` function instead solved the problem.
It was quite hard to reproduce the issue locally, but the following scenario seem to be worked:
- Open `/efficacy` in incognito window (texts loaded)
- Open Inspector / Application / Storage
- Hit "Clear Storage"
- Wait a few seconds
- Hit "Clear Storage" again
- Now reload the page by clicking into the title bar and hit "Enter" on the keyboard. (Cmd+R doesn't work, by using that the texts appeared)
After the scenario above the `data-i18n` texts were empty, but the `$t` ones appeared.

Fix texts on /efficacy page

---

app/core/store/modules/audio.js
app/lib/AudioPlayer.coffee
app/lib/surface/LankBoss.coco.coffee
app/lib/surface/LankBoss.ozar.coffee
app/lib/world/Grid.coffee
app/lib/world/world.coffee
app/schemas/subscriptions/misc.coffee
app/schemas/subscriptions/surface.coffee
app/styles/play/level/screen-reader-surface-view.sass
app/styles/play/play-level-view.sass
app/templates/play/level/screen-reader-surface.pug
app/templates/play/menu/options-view.ozar.pug
app/templates/play/play-level-view.pug
app/views/core/CocoView.coco.coffee
app/views/core/CocoView.ozar.coffee
app/views/play/level/DialogueAnimator.coffee
app/views/play/level/ScreenReaderSurfaceView.coffee
ozaria/engine/cinematic/dialogsystem/DialogSystem.js
ozaria/site/styles/play/menu/game-menu-modal.sass
ozaria/site/styles/play/menu/options-view.sass
ozaria/site/styles/play/play-level-view.sass
ozaria/site/templates/play/play-level-view.pug
ozaria/site/views/play/level/DialogueAnimator.coffee
ozaria/site/views/play/level/PlayLevelView.js
ozaria/site/views/play/menu/OptionsView.coffee

Replaces `<table role="grid">`-based screen reader implementation with a new custom `<div role="application">`-based one. Cleans up a lot of the code. Gets the grid spacing much tighter and more correct, and starts to only navigate navigable cells with a cursor.
Compare to old screen reader view:
While I was at it, I updated some music/sound handling in Ozaria to give more control over independent music tracks and interface sound panning.
Don't squash this one, each commit is useful history.

Screen reader updates

---

app/styles/home-view.scss

- ozaria home max-width increased for large screens
- text sizes also increased based on viewport width

ozaria.com: Responsiveness for larger screens

---

app/components/common/MetaManager.vue
app/core/store/modules/layoutChrome.js
app/lib/surface/LankBoss.ozar.coffee
app/lib/world/world.coffee
app/locale/en.ozar.coffee
app/schemas/subscriptions/surface.coffee
app/styles/play/level/screen-reader-surface-view.sass
app/templates/play/level/level-playback-view.coco.pug
app/templates/play/level/level-playback-view.ozar.pug
app/templates/play/level/screen-reader-surface.pug
app/views/play/level/LevelPlaybackView.coffee
app/views/play/level/ScreenReaderSurfaceView.coffee
app/views/play/level/tome/SpellView.coffee
ozaria/site/components/common/BaseModal.vue
ozaria/site/components/common/LayoutChrome.vue
ozaria/site/components/common/ModalTransition.vue
ozaria/site/views/play/level/LevelPlaybackView.coffee
ozaria/site/views/play/level/PlayLevelView.js
ozaria/site/views/play/level/TutorialPlayComponent.vue
ozaria/site/views/play/level/tome/SpellView.coffee
package-lock.json
package.json

* **Shorten page titles when in screen reader mode**
* **PlayLevelView keyboard navigation and button labeling improvements**
* **Ozaria sound on/off now toggles user.volume**
Before, it was saving mute/unmute to local storage. I think ideally, user.volume would get added to the `me` store module
to better integrate with Vue, but this seemed to do the job for now.
* **Fix Oz PlayLevelView keyboard navigation**
This fixes several keyboard accessibility issues on the PlayLevelView, its code editor, and some of its modals. Some of this is using the new focus-trap package, which is something we should be generally using on all modals so that keyboard tab navigation doesn't leak out of the modal to all the content behind the modal. This only applies it to the ModalTransition (victory modal) …

More screen reader updates

---

app/locale/en.coffee
app/templates/teachers/share-licenses-joiner-row.coco.pug
app/views/teachers/ShareLicensesJoinerRow.coco.coffee
ozaria/site/components/teacher-dashboard/modals/ModalShareLicenses/SharedPoolRow.vue

Confirm modal shown if teacher is removed from shared licenses.
Coco:
Ozar:

DT: show reminder that licenses won't be revoked on removing shared teacher licenses

---

app/components/common/MetaManager.vue

The unintentional 'ozar' string removed from codecombat titles.
Pls check screenshot below:

Remove 'ozar' from codecombat title

---

app/components/common/MetaManager.vue

~ same as https://github.com/codecombat/codecombat/pull/6749 but `description` instead of `title`

Remove 'ozar' from codecombat meta description

---

app/lib/LevelLoader.coco.coffee
app/templates/play/ladder/my_matches_tab.coco.pug
app/templates/play/ladder/play_modal.pug
app/views/ladder/LadderView.coco.coffee
app/views/ladder/components/Leaderboard.coffee
app/views/ladder/components/Leaderboard.vue
app/views/play/level/ControlBarView.coffee
app/views/play/level/PlayLevelView.coffee
app/views/play/level/modal/CourseVictoryModal.coffee

This is so we can add Ace of Coders to CS6, and eventually refactor the type: "course-ladder" arenas to use the new structure.
Currently it doesn't work, because if you play Ace of Coders from the classroom as a student, you arrive on:
/play/level/ace-of-coders?course=5817d673e85d1220db624ca4&course-instance=5afb10979bb5895ee2557c90
So the "Back to ladder" link in the top left is formatted like this:
/play/ladder/ace-of-coders/course/5afb10979bb5895ee2557c90
But then after playing again, you go to:
/play/level/ace-of-coders?team=humans&league=5afb10979bb5895ee2557c90
And then the "Back to ladder" link becomes:
/play/ladder/ace-of-coders/clan/5afb10979bb5895ee2557c90
–which is a 404, because it's trying to load a clan instead of a course instance.
Maybe we should be making most of these …

Start working on making type: "ladder" levels work in classroom

---

ozaria/site/components/char-customization/ModalCharCustomization/index.vue
ozaria/site/components/common/ModalTransition.vue

1. make sure we re-enable hero-selection button if name is missing
2. make sure we call deactivate on focus-trap when we dismiss the victory modal
3. make delay little shorter since 1s is easy to conflict with user click (`Error: initialFocus refers to no known node`)

make sure we call deactivate on focus-trap

---

.github/workflows/node.js.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

app/components/common/Navigation.coco.vue
app/components/common/Navigation.ozar.vue
app/styles/bootstrap/_navbar.scss
app/styles/home-view.scss
app/templates/base-flat.coco.pug
app/templates/base-flat.ozar.pug
app/templates/core/auth-modal.ozar.pug
app/templates/core/create-account-modal/create-account-modal.coco.pug
app/templates/core/create-account-modal/create-account-modal.ozar.pug
app/templates/home-view.ozar.pug
app/views/core/ModalView.coffee
app/views/core/RootView.coco.coffee
app/views/core/RootView.ozar.coffee
ozaria/site/components/char-customization/ModalCharCustomization/index.vue
ozaria/site/components/play/PageUnitMap/common/UnitMapLevelDot.vue
ozaria/site/components/play/PageUnitMap/hoc2019modal/ModalSignIn.vue
ozaria/site/components/play/PageUnitMap/hoc2019modal/ModalStartJourney.vue
ozaria/site/components/play/PageUnitMap/hoc2019modal/StudentSignup/ModalStudentClassCode.vue
ozaria/site/components/play/PageUnitMap/index.vue
ozaria/site/components/sign-up/PageEducatorSignup/PageStartSignup.vue
ozaria/site/components/teacher-dashboard/common/SecondaryTeacherNavigation.vue

Make all Backbone modals activate focus trap by default, and add Vue modal focus trap code to several modals.
Fix some button and link roles, hrefs, etc. to allow them to be keyboard navigable.
Couple minor line-level merges in here, too, as well as removing PD "new" label while I was at it.

Keyboard accessibility for Oz home page, char select, and world map

---

app/core/Router.coco.coffee
app/core/Router.ozar.coffee
app/locale/en.coffee
app/templates/teachers/teacher-course-solution-view.coco.pug
app/templates/teachers/teacher-course-solution-view.ozar.pug
app/views/special_event/HoC2018Component.coco.vue
app/views/special_event/HoC2018Component.ozar.vue
app/views/teachers/TeacherCourseSolutionView.coffee

Updated the HoC teachers' notes page to add goblins-hoc activity (visible just to admins until we add some more resources for it).
Also made it so that the TeacherCoursesView can view solutions for campaigns, not just courses.

Add goblins HoC activity and teacher solutions for campaigns

---

.gitignore
compile-static-templates.coffee
development/utils.js
karma.conf.js
package.json
server_setup.coffee
setup-aether.js
webpack.base.config.js

- Webpack output path will be `public_coco` or `public_ozar` based on actual product.
- The proxy server will also serve from either `public_coco` or `public_ozar`.
- new npm  scripts added, you can use `npm run dev:ozaria` and `npm run proxy:ozaria`. ozaria will be served at `localhost:3001` while coco will be accessible at `localhost:3000` as before, but you can use the old `npm run proxy` and `npm run dev` commands and set `COCO_PRODUCT` and `COCO_PORT` env variables manually.

Add ability to run CodeCombat and Ozaria simultaneously.

---

ozaria/site/views/play/level/TutorialPlayComponent.vue
ozaria/site/views/play/level/tome/SpellView.coffee

Clicking back/forward buttons on Vega messages the focus returns back to the code editor. (If the editor is not hidden behind grey overlay):

Oz Levels - Focus from Vega messages to code editor

---

app/core/Tracker2/MakelogTracker.js
app/core/Tracker2/index.js
app/styles/style-flat.coco.sass
app/styles/style-flat.ozar.sass
app/templates/base-flat.coco.pug
app/templates/base-flat.ozar.pug

Add a changelog link to the footer that can display our public changelog in a widget, as well as a number count of unread changelog updates next to it for this site visitor.
This is gated to CoCo admin-only for now until we decide to do more with it.

Add changelog feature via Makelog

---

app/core/utils.coco.coffee
app/core/utils.ozar.coffee
app/views/ladder/LadderView.coco.coffee
app/views/landing-pages/league/PageLeagueGlobal.vue

This PR removes the ability to obtain Ned Fulmer. We still need to figure out how we should change/remove the custom pages for Ned. Also, upon pushing this PR, we need to set Ned Fulmer's releasePhase property to "beta" so it doesn't show up on the hero selection page.
What it does:
* Simple change so joining the clan no longer grants the Ned Fulmer hero
* Remove Ned's team offer in ladder page.
What needs to be worked on later:

Remove Ned Fulmer

---

app/schemas/subscriptions/editor.coffee
app/styles/editor/editor.sass
app/styles/editor/level/thang/level-thang-edit-view.sass
app/styles/editor/level/thangs-tab-view.sass
app/styles/editor/thang/thang-type-edit-view.sass
app/templates/editor/level/level-edit-view.pug
app/templates/editor/level/thang/key-thang-tab-view.pug
app/views/editor/component/ThangComponentConfigView.coffee
app/views/editor/component/ThangComponentsEditView.coffee
app/views/editor/level/LevelEditView.coffee
app/views/editor/level/thangs/KeyThangTabView.coffee
app/views/editor/level/thangs/LevelThangEditView.coffee
app/views/editor/level/thangs/ThangsTabView.coco.coffee
app/views/editor/level/thangs/ThangsTabView.ozar.coffee

When the level editor starts, if there is already a Hero Placeholder, Hero Placeholder 1, Referee, Level Manager JS, etc., then this adds a new convenience tab to edit that Thang, so it's easier to directly jump to its configuration and to keep persistent code editor windows open for use of external tooling.
This also adds a convenience function for automatically opening Programmable Components to the code and merges a couple minor coco/ozar differences (like not loading archived ThangTypes).

Add level editor tabs for key thangs like Hero and Referee

---

app/templates/account/subscription-view.pug

It seems, `data-i18n` will be automatically html encoded. By adding `[html]` prefix it can be switched off:

Subscription page not displaying correctly

---

app/components/license/LicenseDataPerUser.vue
app/views/school-administrator/teachers/SchoolAdminTeacherListView.vue

add a simple button to japan school admin `CodeCombat@fce-hd.co.jp` since they really like it.
also add a fall back teacherID for removedMembers. see https://github.com/codecombat/codecombat-server/compare/yuqiang/JapanSchoolDashboardUpdates?expand=1 also

show license_stats button for japan school admin

---

app/locale/en.coffee
app/templates/home-view.coco.pug
app/templates/home-view.ozar.pug
app/views/HomeView.coco.coffee
app/views/HomeView.ozar.coffee

Remove the separate `HoC banner` from homepages, and display its content in the already existing `top-banner` instead:

HoC Banner fix

---

app/components/common/DirectContactModal.vue
app/components/common/Footer.vue
app/views/HomeView.coco.coffee
app/views/core/CocoView.coffee
app/views/core/CocoView.ozar.coffee
ozaria/site/components/common/DirectContactModal.vue

The behavior of "Contact" buttons fixed: 
- for non-teachers: open 'mailto:support@codecombat.com' link
- for teachers: open contact modal where they choose either Support or Sales, the Zendesk messenger will be shown
The "Email" button was removed from contact modal, and support email address is shown instead.

Fix Contact Link

---

app/templates/play/ladder/my_matches_tab.coco.pug
app/views/ladder/components/Leaderboard.coffee
app/views/ladder/components/Leaderboard.vue

simply add team column in leaderboard. 
in future, we can try to drop the `my-matches` tab when user doesn't have matches. and better to have a better `team name` selector (currently we select team from user clan in a not so stable order)

simply add clan column in league leaderboard

---

app/templates/core/create-account-modal/setup-account-panel.coco.pug

Do not escape html tags in signup message

Fix Google signup HTML message

---

app/core/Tracker2/FacebookPixelTracker.js
app/core/application.coffee
app/templates/static/layout.static.coco.pug
app/templates/static/layout.static.ozar.pug

Previously, we always loaded and initialized it, but sometimes removed it while it was initializing, leading to errors when we removed `window.fbq` mid-load. Now we wait to initialize it until we have loaded the user and know whether we want to initialize it, and also wait to remove it at that time.

Use another method to initialize/remove fbq to avoid errors

---

app/core/Router.coco.coffee
app/core/Router.ozar.coffee

`codecombat.com/Roblox` or `codecombat.com/roblox` was requested to work regardless of letter cases.
Other two routes moved to new logic to avoid duplications.
Now the router works case insensitively for the routes `/roblox`, `/careers` and `/premium`

Some routes made case insensitive

---

app/views/core/CreateAccountModal/BasicInfoView.coffee
app/views/landing-pages/mobile/PageMobileView.vue

Call `trackEvent` when `/mobile` signup is done.
The event name is `codecobatMobileSignup` or `ozariaMobileSignup` depending on product.
Also ability added for _Create Teacher Account_ from to be prefilled by base64 encoded `prefill` data param instead of `firstName`, `lastName` and `email`:
Pls also check: https://github.com/codecombat/codecombat-server/pull/556

Track mobile signup event & Encode prefill data

---

app/core/aceUtils.coffee

bug: https://codecombat-core.slack.com/archives/C3BBBA01K/p1676513189688549
now:

fix cpp/java function autocomplete fill the types instead of params

---

app/styles/admin/codeplayback-view.sass
app/templates/admin/codeplayback-view.pug
app/views/admin/CodePlaybackView.coffee
app/views/play/level/tome/SpellView.coffee
vendor/scripts/spade.js

I dunno how you folks review so I added everyone 🙏.
Backwards compatible Spade/codelogs change to keep track of UI events (like running code or resetting code). Spade was reformatted from tabs to spaces so it bricked the diff... Lemme know if that's a problem.
Updated Codelogs UI w/ flashing text areas indicating when an 'event' occurred during playback.
Red lines in the timeline indicate 'events'

Update Spade to keep track of UI events

---

app/locale/en.coffee
app/styles/courses/teacher-classes-view.sass
app/templates/courses/teacher-classes-view.coco.pug
app/views/courses/PodcastItemContainer.vue
app/views/courses/TeacherClassesView.coco.coffee
app/views/podcast/BodyComponent.vue
app/views/podcast/PodcastItemComponent.vue

Latest podcast episode added to bottom of "My Classes" view.
The new `PodcastItemComponent` was extracted from `podcast/BodyComponent` in order to make it available anywhere else as a single entity.

CoCo /teachers/classes: add an embed of latest podcast episode

---

app/styles/play/play-level-view.sass

i add `important` here: https://github.com/codecombat/codecombat/pull/6850
but it makes gd levels breaking 
while this time i remove the `important`, both level works fine :joy:

game dev levels cannot 100% canvas

---

app/core/initialize.coffee

this code works since 2016 so i think it won't be a bug. but today i met the userObject to be undefined in China. (maybe related to some server bug). so i think it's better to add such check

what if window.userObject is undefined?

---

app/styles/ai/ai.sass
app/templates/ai/ai.pug
app/views/ai/AIView.js
webpack.base.config.js
webpack.development.config.js

I made some slight changes to how embedding works in codecombat/ai#24. This brings your branch inline with those changes:
- Threw out `dist-embed` in favor of just a `dist`
- AI app is now absolutely positioned within a parent container, so it needs to be embedded in a positioned `#ai-wrapper`, so I changed root to match that.
- I did this to try and make "full screen pages" from within the embedded app, but it looks like that's not exactly working.

Updates for new embed setup

---

ozaria/site/components/teacher-dashboard/BaseSingleClass/index.vue

The `closePanel` function was previously removed by mistake. 
Now it's added back.
`beforeRoute` hooks were failing, since they were calling it: 
https://github.com/codecombat/codecombat/blob/a93ebbd5f9978a0569d364fb36acf843cf57b3a3/ozaria/site/components/teacher-dashboard/BaseSingleClass/index.vue#L367

Fix issue with class selection drop-down menu not working correctly

---

app/templates/courses/teacher-class-view.pug
app/views/play/CampaignView.coco.coffee

It seems that by mistake the new Ozaria locking logic was also implemented in some codecombat files.
Change reverted, and seems to be working as expected:

Fix: CodeCombat Level Lock Feature Not Working Correctly

---

app/locale/en.coffee
app/models/User.coffee
app/schemas/models/user.coffee
app/templates/account/account-settings-view.coco.pug
app/templates/account/account-settings-view.ozar.pug
app/views/account/AccountSettingsView.coco.coffee
app/views/account/AccountSettingsView.ozar.coffee

"Current Password" field added to Account Settings page.
The new field is NOT shown - and required - if:
- user has facebook / google / etc login method - since in these cases they could login even without a password, maybe they don't even have one
- user just logged in with temporary password requested by "forgotten password" button. In this case we set the `newPasswordRequired` flag on the user to know that they won't need the old password for setting a new one.

COD-Q123-7 - Current Password Not Required When Performing A Password Change

---

ozaria/site/common/ozariaUtils.js

It was not 100% sure that `Object.values()` returns the levels always in the same order. 
Now it is sure that the first stage will come first to prevent issues caused by skipping a level unintetionally.

Fix: ensure the capstone stage order in getNextLevel logic

---

app/components/common/Footer.vue
app/views/core/CocoView.coffee

Old contact modal added back for non-teacher users:

Footer: restore "Contact" link functionality

---

app/locale/en.coffee
app/views/core/CocoView.coffee

OOO message is shown after `Contact` link is clicked. Normal functionality continues after user seen the popup.
We use localStorage to show message only once for the user.

Support Team OOO message for Team Week

---

app/core/auth.coffee
app/schemas/models/user.coffee
app/templates/admin/administer-user-modal.pug
app/views/admin/AdministerUserModal.coffee

display a `useUserTimeZone` option when user timezone is different from server timezone. (the screenshot from china which server timezone is Asia/Shanghai, so  when user timezone is Los angeles it shows) .see https://github.com/codecombat/codecombat-server/pull/625 server changes

support use user timezone when admin add prepaid

---

app/styles/ai/ai.sass
app/templates/ai/ai.pug
app/views/ai/AIView.js

Headless UI wants its modal to be a child of `<body>`, which is outside of the old `#ai-wrapper`. The solution is to use a class on both sibling divs (the AI container and the HeadlessUI modal) instead of the `#ai-wrapper` id.
This PR adds a `.tailwind-wrapper` class to the AI Root node since that's now the CSS selector wrapper, and renames `#ai-wrapper` to `#ai-root` just to be more explicit about the difference.

Separate ai root & tailwind root(s)

---

ozaria/site/components/teacher-dashboard/BaseResourceHub/index.vue

It seems the problem was that we tried to check the prepaids while they were not yet loaded. 
Now, that fetching is added, everything seems to be working correctly. 
Pls check screenshots of a paid teacher account below. All CS2+ resources set to `hidden:"paid-only"`
(after taking the screenshot I've set all the resources to hidden:false)

Fix resource hub resource locking

---

app/lib/LevelBus.coffee

since this code is based on part of play-blue logic so the changes may seems little strange. let me describe something here.
1. when play against another player in arena, we load opponent's code into `session.code['hero-placeholder-1'].plan` so the session has both plan for red and blue team so that the level can play normal with two players. i.e. we laod opponent's code in `levelLoader`
2. we would put the session at the beginning of spellview to update code and spells in `levelBus` so we update the `hero-placeholder-1` too.
-- that's the reason of some bugs, like when opponent uses cpp, since cpp code loaded in frontend is an AST tree encoded with UTF-16, so it's longer than our string length limitation for sessions. Also when i want to introduce play blue feature in arenas, red and …

don't put hero-placeholder-1

---

app/styles/play/play-level-view.sass

prior wrong pr.
https://github.com/codecombat/codecombat/pull/6956
https://github.com/codecombat/codecombat/pull/6850
important is not correct way to handle canvas-wrapper, but we need handle `real-time` after the `no-api` since real-time should have higher priority.

correct way to handle real-time canvas-wrapper

---

bower.json

to test it. clone the pr and run bower install or npm install to get latest esper.js. then see if the bug https://codecombat-core.slack.com/archives/C49HU8WLA/p1694833855629179 still exists.

bundle the babylon plugin into esper.js to make java works better

---

app/locale/en.coffee
app/templates/courses/courses-view.pug

By mistake we were showing the Ozar level for Coco students.
| BEFORE | AFTER |
| --- | --- |
| ![Screenshot 2023-10-17 at 5 27 27 PM](https://github.com/codecombat/codecombat/assets/11805970/63c6974a-4964-4f82-9ef4-df6370876e31) | <img width="619" alt="CodeCombat_-_Coding_games_to_learn_Python_and_JavaScript___CodeCombat" src="https://github.com/codecombat/codecombat/assets/11805970/dd16bf7b-1ca7-4eda-a921-589fdd761209"> |

fix no-classroom announcement for coco

---

app/models/CocoModel.coffee
test/app/views/teachers/ConvertToTeacherAccountView.spec.coffee

I noticed my user object keeps getting `undefined: 2` or similar values set to it. Not sure where, but when it happens, validation starts failing and the object can't save.
This makes it generally log and ignore `"undefined"` as a property key in CocoModel initialization and `set` calls.

Don't allow undefined keys on CocoModels

---

app/locale/en.coffee
app/schemas/models/classroom.schema.coffee
app/styles/courses/classroom-settings-modal.sass
app/templates/courses/classroom-settings-modal.pug
app/views/courses/ClassroomSettingsModal.coffee
app/views/play/level/LevelChatView.coffee
app/views/play/level/PlayLevelView.coffee

We have 3 options:
- Free form
- Fixed prompt only
- None
Live Chat is shown for students for both **Free from** and **Fixed prompt only** options.

Add option to let teachers turn on level chat for their students

---

app/core/Router.coffee
app/core/utils.coffee
app/core/vueRouter.js
app/views/play/CampaignView.coffee
ozaria/site/common/ozariaUtils.js
ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/IntroModuleRow.vue
ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ModuleRow.vue
ozaria/site/components/teacher-dashboard/BaseSingleClass/index.vue
ozaria/site/components/teacher-dashboard/BaseSingleClass/table/TableModuleHeader.vue
ozaria/site/components/teacher-dashboard/common/icons/ContentIcon.vue
ozaria/site/styles/common/variables.scss
test/app/core/utils.spec.coco.coffee
test/app/views/play/CampaignView.spec.coco.coffee

Pls check the [backend PR](https://github.com/codecombat/codecombat-server/pull/698) as well.
The new teacher dashboard can be accessed if you switch it on by running `localStorage.setItem('newDT', true);` in the console.
Level names are appearing Coco style (showing if practice, and level index as 1, 2, 3a, 3b etc...)
Level access settings are appearing for student as well:

WIP: Merge Teacher Dashboard

---

app/locale/en.coffee
app/models/User.coffee
app/styles/play/level/chat.sass
app/templates/play/level/chat.pug
app/templates/play/level/tome/problem_alert.pug
app/views/play/level/LevelChatView.coffee
app/views/play/level/PlayLevelView.coffee
app/views/play/level/tome/ProblemAlertView.coffee

Quick and dirty hack to not allow free-form chat (should really clean up the unneeded code)
Tweaked classroom settings language to be about hints rather than chat.
Using gpt-4-1106-preview by default now.
Still needing to be done on this:
- Show appropriate messages when quota is up (not subscription modal for non-home-users)
- Show remaining credits in UI
- Translate error questions into user's locale
- Add a free-form hint button that's not connected to errors
- Don't include previous message conversation history any more now that it's not a conversation
When we have that stuff, we can just turn it on for student users, too (since teachers already have the setting in class settings, and it defaults to 'off').
Closes AI-165 when it's done

Release level chat for errors generally for home users

---

app/views/core/RecoverModal.js

I can't really understand why, but the `filterKeyboardEvents` did not work (which was intended to filter all keyboard events but `Enter` key), and resulted that all keydown events triggered the form submit.
Now it is fixed and the form is submitted on _Enter key_ or _Send Recovery Password_ button tap

Fix Recover Account Modal

---

app/views/ladder/LadderTabView.js

Error below occurred [here](https://codecombat.com/play/ladder/frozen-fortress?tournament=64260960f1c07d0018299145)
`4909-df9f8ce9c739f16b8377.bundle.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'models')
at a.value (4909-df9f8ce9c739f16b8377.bundle.js:1:19674)`
- the http://localhost:3000/db/level/frozen-fortress/my_sessions?_=1702586407548 request returns `[]`
- which is because there are no matching LevelSession records:
- but the code tries to work with them 
- which leads to error
Check if `session` exists, to prevent error.

fix ladderTabView by checking if session exists

---

ozaria/site/common/ozariaUtils.js

It seems the `findNextLevelsBySession` logic ignored if level was skipped or not, and returned a `skipped` one as `next`.

ENG-153 - fix Lock / Unlock Issues

---

app/views/play/CampaignView.js

fix ENG-201
the how-old-are-you poll do not have nextPoll. so just not show current modal is good to go

skip age poll for library users

---

ozaria/site/views/play/level/tome/SpellView.coffee

fix ENG-275
since ace-diff set options as `maxLines: infinity` (and update ace-diff maybe lead to coco issues)
so add updateAceLines into ozaria updateLines too (coco does that)
can scroll again

make ace scrollable again

---

app/views/editor/level/components/LevelComponentEditView.js

fix ENG-295
since data.description can be object. we need stringify it

handle different types of data.description

---

app/views/core/CreateAccountModal/CreateAccountModal.js
app/views/core/RootView.coffee
app/views/core/SingletonAppVueComponentView.js
app/views/home/PageHome.vue

`#create-account` hashes are now working in new home page. Also the Payment response handling (`?payment-studentLicenses=success`) is ported into new home.
- No reference to CreateAccountModal in SingletonAppVue
- Payment response handling is now in PageHome

ENG-281 - Adamk/fix hash modal new home

---

app/lib/translate-utils.coffee

not sure why but one student met bug when `str` is undefined. so add an check

fix undefined bug in trasnlate-utils

---

app/core/vueRouter.js

When navigating from `/home` or from `/` using the vue router, it loaded first the page we were navigating from, ignoring the fact that those routes were already handled by the backbone router, and would normally not be handled by the vue router.
Condition added to vue router to only know about these routes when home page experiment is on.

ENG-422 - handle /home and / routes by vueRouter only new homepage is on

---

ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue

Missing method added, because it is called here: 
https://github.com/codecombat/codecombat/blob/master/ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue#L296

ENG-458 - Ozaria: course instances not created

---

app/lib/LevelLoader.coffee
app/locale/en.js
app/styles/play/level/level-loading-view.sass
app/templates/play/level/level-loading-view.pug
app/views/play/level/LevelLoadingView.coffee

Previously if student inspected the level slug on the map, and replaced in the url, they could play any level regardless if it was locked or not. Now we show this message if student tries to open a locked level:

ENG-157 - show error message if student tries to load a locked level

---

ozaria/site/components/teacher-dashboard/BaseSingleClass/table/TableClassFrame.vue
ozaria/site/components/teacher-dashboard/BaseSingleClass/table/TableModuleGrid.vue
ozaria/site/components/teacher-dashboard/BaseSingleClass/table/TableModuleHeader.vue

Grouping added to level selection. 
We can define levels that can only be selected (and locked/skipped) together.

ENG-210 - Allow lock/unlock as a group for capstones.

---

app/views/landing-pages/league/PageLeagueGlobal.vue

The Code Points CTA previously goes to play then to /teachers/classes. Now it directly goes to the dashboard.

Change Code Points CTA to direct to /teachers/classes/

---

app/models/ClassroomLib.js

Without this fix, when locking levels for a student for the first time, the whole level will appear as locked.
By this fix, only the selected ones will be locked.

Fix whole course locking issue

---

ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue

For some unknown reason, `createFreeCourseInstances` was only called in Ozaria.
By this fix course instances will be created for all free courses at classroom creation.

Google Classroom: create free courses for CoCo as well

---

ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue

The `levelChat` value in ModalEditClass was a Boolean, but was a [String in the schema](https://github.com/codecombat/codecombat/blob/17fb38f49ed3bc28c545f2cd547bdf2408151704/app/schemas/models/classroom.schema.js#L30), which lead to Validation Error when saving the class. 
By this fix, the levelChat value is saved as a String.

Convert levelChat value to String from Boolean in Classroom Modal

---

app/views/core/SingletonAppVueComponentView.js

Like on the teacher dashboard, where the ModalTeacherDetails might be about to show up (if they show up at the same time, input/focus gets stuck.)

Don't show the Roblox modal if we might be opening another modal

---

app/views/play/level/PlayLevelView.coffee
app/views/play/level/tome/SpellPaletteView.coffee

- If we have many APIs, never stack the control bar above the editor
- If we have many APIs, always have at least 3 columns of APIs
- If we have a ton of APIs and a large screen, at least 4 columns
- If we have a ton of APIs, hide granting item images
Fix CCJ-192, ENG-540
Large screen at corner case of aspect ratios and code widths and API amounts that previously had 2 columns and stacked control bar now has more space for APIs:
https://github.com/codecombat/codecombat/assets/99704/0150623e-bf5b-4adf-aed8-8b7027810f9e
Medium-large screen that previously had 2 columns now has 4:
https://github.com/codecombat/codecombat/assets/99704/5b2ddb02-5ec0-4eca-9bb3-a6d978233550

Increase minimum number of API columns in various screen layouts

---

ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ModuleRow.vue

ENG-564 - Curriculum guide doesn't escape level descriptions properly

---

app/templates/play/menu/my-code-view.pug
app/views/play/menu/MyCodeView.js
ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue
ozaria/site/views/play/level/tome/ProblemAlertView.coffee

fixes ENG-616
Ozaria didn't handle level-chat toggle correctly on edit class modal and student side
'Ask the AI' button in Game menu on Coco wasn't toggled based on class settings
We stored true/false in ozaria classroom levelChat config. It will be fixed via script for old entries

level chat fixes

---

ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue

fix ENG-645
our old vuelidateMixin only triggered when field updates. if the teacher click `save` directly it is not triggered. so adding a manual check in saveClass make sense

add manual check when save class

---

app/lib/LevelSetupManager.coffee
app/views/play/modal/PlayHeroesModal.js

Previously, they would be prompted to subscribe if it were a premium hero, and selecting anything would go back to teacher dashboard instead of reloading the level with new hero, code format, or code language.
This was one of the bugs:
(and if you did pick anything, it didn't include ?course= so redirected to teacher dashboard)
Now that works, and you can pick premium heroes in teacher or student mode in CCJ.

Let teachers change hero/language for CCJ from curriculum guide

---

app/views/courses/ClassroomSettingsModal.js
ozaria/site/components/teacher-dashboard/modals/ModalEditClass.vue

It still has a (beta) label on it, but it's no longer restricted to the teachers explicitly marked as beta testers.

Allow all teachers to set classroom code formats to blocks, blocks-and-code, blocks-icons

---

app/core/api/thang-types.js
app/lib/LevelLoader.coffee
app/lib/LevelSetupManager.coffee
app/lib/ThangTypeConstants.coffee
app/models/Level.js
app/models/User.js
app/schemas/models/thang_type.js
app/templates/play/modal/play-heroes-modal.pug
app/views/courses/CoursesView.js
app/views/courses/HeroSelectModal.js
app/views/play/CampaignView.js
app/views/play/level/tome/SpellPaletteView.coffee
app/views/play/modal/PlayHeroesModal.js

This hooks up ThangType constants for the new pet heroes, makes the logic for when to display pet-style hero selection also encompass whether the campaign is Junior (not just the level), and tries to swap back to pet heroes when a player would get into a CodeCombat Junior level with a normal warrior hero.
There's also a start of handling student hero choice between heroes in the student dashboard, but that'll need more work once we really know whether a student is just going to be doing CCJ or also other courses in advance, on account creation.

Use a new set of pet heroes in CodeCombat Junior

---

app/core/Router.js

fix ENG-700
the bug comes from new home-beta page is a vue component and parent signup is also a vue component and click parent path trigger the `routeDirectly` in router which returns early for vue. and we have close modal logic in `this.openView` but won't trigger for vue routes. so add one

close backbone modal when route vue paths

---

app/views/play/CampaignView.js

Fixed map sometimes not loading bug

---

ozaria/site/components/teacher-dashboard/BaseCurriculumGuide/components/ChapterInfo.vue

fix CCJ-224
codecombat doesn't allow teacher to open campaign view to play, so the button `play course` is not make sense to show in coco. let's hide it.

coco curriculum guide shouldn't have play-course

---

app/views/pd/PDBox.vue

- use the general `ContentBox` - to have similar box background we have on other pages
- make buttons bold
| BEFORE | AFTER |
| --- | --- |
| ![codecombat com_pd](https://github.com/user-attachments/assets/868149d4-3ea9-42f4-844a-6af3126ad26a) | ![localhost_3000_pd](https://github.com/user-attachments/assets/e2793675-2f4c-4aa4-8af6-b84ea76c8f21) |

ENG-1138 - PD page revisions

---

app/core/blocklyUtils.js
app/views/play/level/tome/SpellView.coffee

Some levels have statement limits, like under 6 lines of code, which is a soft limit that causes goal failure if you exceed it. Here we implement the same as a hard limit for blocks, using Blockly's `maxBlocks` limitation in the blocks that can be added from the toolbox. You can still click to insert blocks beyond the maximum, but they show as disabled, and you can't drag to insert them.

Fix CCJ-27: limit number of addable blocks for limited-line levels

---

app/lib/aether_utils.coffee
app/views/artisans/StudentSolutionsView.js
app/views/editor/verifier/VerifierTest.js
app/views/play/level/PlayLevelView.coffee
app/views/play/level/tome/Spell.coffee

CodeCombat levels interpret a max of 3M statements before throwing an error, which can take a while to trigger on infinite loops withs slower hardware.
CodeCombat Junior levels should be much simpler as a rule, and are fairly prone to infinite loops that don't have automatic yields inserted in them once we get into the later modules that use while loops, so this sets the limit to 100K statements, which should trigger on an infinite loop quite quickly.

Lower interpreter statement execution limit for CCJ levels

---

app/lib/level-generation.js
app/views/editor/campaign/CampaignEditorView.js
app/views/editor/verifier/VerifierTest.js
app/views/editor/verifier/VerifierView.js
app/views/play/level/tome/Spell.coffee

These are the usual defaults for levels at the point in the course we're making them at.
Press Shift+0 to do it (already have Shift+1-9). I guess modules 11 and 12 will just get done by hand ;)
Skips practice levels, otherwise it would probably crash.
Instead of assigning `health` -> `hero.health` statically at the start of the program, like is done in the programming.Programmable Component, we instead rewrite any bare instances of `health` to
`hero.health` in a way that's hopefully invisible to the player, so that references to `health` will get the current value.
Otherwise, code like `while health < 4:` does not work, because `health` is initialized to `4` and never updated as the hero takes damage.
Couldn't find another way around this given all the voodoo we do around making these …

CCJ level generation updates
